#!/bin/bash

# Usage: mas install

function trap_exit {
  RC=$?
  if [[ $RC != "0" ]]; then
    echo_warning "\nFatal Error[$RC]  See $LOGFILE for details"
  fi
  save_config
}
function trap_int {
  # Reset any modifications made to the terminal
  tset

  echo
  echo
  save_config
  exit 0
}

trap trap_exit EXIT
trap trap_int INT


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG_DIR="$HOME/.ibm-mas/config"
LOG_DIR="$HOME/.ibm-mas/logs"
LOGFILE=$LOG_DIR/mas.log

VERSION=latest

mkdir -p $LOG_DIR
mkdir -p $CONFIG_DIR

# export ANSIBLE_CONFIG=$DIR/ansible.cfg

# General purpose
. $DIR/functions/catalog_utils
. $DIR/functions/connect
. $DIR/functions/utils
. $DIR/functions/save_config
# MAS provisioning support
. $DIR/functions/provision_fyre
. $DIR/functions/provision_roks
. $DIR/functions/provision_aws
# MAS installation support
. $DIR/functions/install
. $DIR/functions/pipeline_config
. $DIR/functions/pipeline_install_operator
. $DIR/functions/pipeline_install_tasks
. $DIR/functions/pipeline_prepare
. $DIR/functions/pipeline_run
. $DIR/functions/pipeline_show_config
. $DIR/functions/update
. $DIR/functions/upgrade
. $DIR/functions/uninstall
# Airgap support
. $DIR/functions/setup_mirror_registry
. $DIR/functions/mirror_to_registry
. $DIR/functions/mirror_redhat_to_registry
. $DIR/functions/configure_ocp_for_mirror
# Manage OIDC for configtool
. $DIR/functions/configtool_oidc
# Must Gather
. $DIR/functions/must_gather

load_config
case $1 in
  fyre|provision-fyre)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite FYRE Cluster Provisioner (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    update_ansible_collections
    provision_fyre "$@"
    ;;

  roks|provision-roks)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite ROKS Cluster Provisioner (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    update_ansible_collections
    provision_roks "$@"
    ;;

  aws|provision-aws)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite AWS Cluster Provisioner (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    update_ansible_collections
    provision_aws "$@"
    ;;

  oidc|configtool-oidc)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite OIDC for Configuration Tool (v${VERSION})${TEXT_RESET}"
    echo
    reset_colors
    configtool_oidc "$@"
    ;;

  registry|setup-registry|setup-mirror-registry|setup-airgap-registry)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap Registry Setup (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    update_ansible_collections
    connect
    setup_mirror_registry
    ;;

  mirror|mirror-images)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap Image Mirror (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    update_ansible_collections
    mirror_to_registry "$@"
    ;;

  mirror-redhat|mirror-redhat-images)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap Red Hat Image Mirror (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    update_ansible_collections
    mirror_redhat_to_registry "$@"
    ;;


  configure-ocp-for-mirror|configure-airgap|configure-mirror|config-airgap|config-mirror)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap OCP Setup (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    update_ansible_collections
    configure_ocp_for_mirror "$@"
    ;;

  install)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Installer (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET} and ${COLOR_CYAN}${TEXT_UNDERLINE}https://tekton.dev/${TEXT_RESET}"
    echo
    echo "${TEXT_UNDERLINE}${TEXT_DIM}Current Limitations${TEXT_RESET}"
    echo "${TEXT_DIM}1. Maximo Assist, Predict, and Visual Inspection are not supported in disconnected installs as of MAS v8.10"
    echo
    reset_colors
    install "$@"
    ;;

  update)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Update Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET} and ${COLOR_CYAN}${TEXT_UNDERLINE}https://tekton.dev/${TEXT_RESET}"
    echo
    reset_colors
    update "$@"
    ;;

  upgrade)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Upgrade Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET} and ${COLOR_CYAN}${TEXT_UNDERLINE}https://tekton.dev/${TEXT_RESET}"
    echo
    reset_colors
    upgrade "$@"
    ;;

  uninstall)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Uninstall Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET} and ${COLOR_CYAN}${TEXT_UNDERLINE}https://tekton.dev/${TEXT_RESET}"
    echo
    reset_colors
    uninstall "$@"
    ;;

  mustgather|must-gather)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Must-Gather Tool (v${VERSION})${TEXT_RESET}"
    echo
    mustgather "$@"
    ;;

  *)
    echo "unknown parameter"
    exit 1
    ;;
esac
