#!/bin/bash

# Usage: mas install

function trap_exit {
  save_config
}

function trap_int {
  # Reset any modifications made to the terminal
  tset

  echo
  echo
  save_config
  exit 0
}

trap trap_exit EXIT
trap trap_int INT


CLI_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG_DIR="$HOME/.ibm-mas/config"
LOG_DIR="$HOME/.ibm-mas/logs"
LOGFILE=$LOG_DIR/mas.log

# Note: "latest" is overwritten with the actual version at build time
VERSION=latest

mkdir -p $LOG_DIR
mkdir -p $CONFIG_DIR

# General purpose internals
. $CLI_DIR/functions/internal/pipelines_install_operator
. $CLI_DIR/functions/internal/pipelines_install_tasks
. $CLI_DIR/functions/internal/catalog_utils
. $CLI_DIR/functions/internal/connect
. $CLI_DIR/functions/internal/utils
. $CLI_DIR/functions/internal/save_config
# MAS provisioning support
. $CLI_DIR/functions/provision_fyre
. $CLI_DIR/functions/provision_roks
. $CLI_DIR/functions/provision_aws
# MAS installation support
. $CLI_DIR/functions/install
. $CLI_DIR/functions/update
. $CLI_DIR/functions/upgrade
. $CLI_DIR/functions/uninstall
# Airgap support
. $CLI_DIR/functions/setup_registry
. $CLI_DIR/functions/teardown_registry
. $CLI_DIR/functions/mirror_images
. $CLI_DIR/functions/mirror_redhat
. $CLI_DIR/functions/configure_mirror
# Manage OIDC for configtool
. $CLI_DIR/functions/configtool_oidc
# Must Gather
. $CLI_DIR/functions/must_gather
# GitOps
. $CLI_DIR/functions/gitops_utils
. $CLI_DIR/functions/gitops_bootstrap
. $CLI_DIR/functions/gitops_cluster
. $CLI_DIR/functions/gitops_cis_compliance
. $CLI_DIR/functions/gitops_cos
. $CLI_DIR/functions/gitops_cp4d
. $CLI_DIR/functions/gitops_cp4d_service
. $CLI_DIR/functions/gitops_license
. $CLI_DIR/functions/gitops_mongo
. $CLI_DIR/functions/gitops_kafka
. $CLI_DIR/functions/gitops_suite
. $CLI_DIR/functions/gitops_suite_app_install
. $CLI_DIR/functions/gitops_suite_app_config
. $CLI_DIR/functions/gitops_suite_certs
. $CLI_DIR/functions/gitops_mas_config
. $CLI_DIR/functions/gitops_suite_dns
. $CLI_DIR/functions/gitops_suite_workspace
. $CLI_DIR/functions/gitops_deprovision_app_config
. $CLI_DIR/functions/gitops_deprovision_app_install
. $CLI_DIR/functions/gitops_deprovision_cos
. $CLI_DIR/functions/gitops_deprovision_suite
. $CLI_DIR/functions/gitops_deprovision_suite_config
. $CLI_DIR/functions/gitops_deprovision_suite_objectstorage_config
. $CLI_DIR/functions/gitops_deprovision_suite_workspace
. $CLI_DIR/functions/gitops_efs
. $CLI_DIR/functions/gitops_dro
. $CLI_DIR/functions/gitops_db2u
. $CLI_DIR/functions/gitops_db2u_database
. $CLI_DIR/functions/gitops_db2u_jdbc_config_rotate_password
. $CLI_DIR/functions/gitops_process_mongo_user
. $CLI_DIR/functions/gitops_aws_infrastructure
. $CLI_DIR/functions/gitops_rosa
. $CLI_DIR/functions/gitops_deprovision_rosa
. $CLI_DIR/functions/gitops_deprovision_cluster
. $CLI_DIR/functions/gitops_deprovision_mongo
. $CLI_DIR/functions/gitops_delete_kafka_config
. $CLI_DIR/functions/gitops_deprovision_efs
. $CLI_DIR/functions/gitops_deprovision_kafka
. $CLI_DIR/functions/gitops_deprovision_suite_idp_config
. $CLI_DIR/functions/gitops_deprovision_suite_smtp_config
. $CLI_DIR/functions/gitops_mas_fvt_preparer
. $CLI_DIR/functions/gitops_suite_watson_studio_config
. $CLI_DIR/functions/gitops_deprovision_suite_watson_studio_config
. $CLI_DIR/functions/gitops_deprovision_db2u_database
. $CLI_DIR/functions/gitops_nvidia_gpu

case $1 in
  fyre|provision-fyre)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite FYRE Cluster Provisioner (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    provision_fyre "$@"
    ;;

  roks|provision-roks)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite ROKS Cluster Provisioner (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    provision_roks "$@"
    ;;

  aws|provision-aws)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite AWS Cluster Provisioner (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    provision_aws "$@"
    ;;

  oidc|configtool-oidc)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite OIDC for Configuration Tool (v${VERSION})${TEXT_RESET}"
    echo
    reset_colors
    configtool_oidc "$@"
    ;;

  registry|setup-registry|setup-mirror-registry|setup-airgap-registry)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap Registry Setup (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    connect
    setup_mirror_registry
    ;;

  delete-registry|teardown-registry|teardown-mirror-registry|teardown-airgap-registry)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap Registry Tear Down (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    connect
    teardown_mirror_registry
    ;;

  mirror|mirror-images)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap Image Mirror (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    mirror_to_registry "$@"
    ;;

  mirror-redhat|mirror-redhat-images)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap Red Hat Image Mirror (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    mirror_redhat "$@"
    ;;


  configure-ocp-for-mirror|configure-airgap|configure-mirror|config-airgap|config-mirror)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap OCP Setup (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    configure_ocp_for_mirror "$@"
    ;;

  install)
    install "$@"
    ;;

  update)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Update Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET} and ${COLOR_CYAN}${TEXT_UNDERLINE}https://tekton.dev/${TEXT_RESET}"
    echo
    reset_colors
    update "$@"
    ;;

  upgrade)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Upgrade Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET} and ${COLOR_CYAN}${TEXT_UNDERLINE}https://tekton.dev/${TEXT_RESET}"
    echo
    reset_colors
    upgrade "$@"
    ;;

  uninstall)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Uninstall Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET} and ${COLOR_CYAN}${TEXT_UNDERLINE}https://tekton.dev/${TEXT_RESET}"
    echo
    reset_colors
    uninstall "$@"
    ;;

  mustgather|must-gather)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Must-Gather Tool (v${VERSION})${TEXT_RESET}"
    echo
    mustgather "$@"
    ;;
  gitops-bootstrap)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_bootstrap "$@"
    ;;

  gitops-mongo)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_mongo "$@"
    ;;

  gitops-process-mongo-user)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_process_mongo_user "$@"
    ;;

  gitops-cluster)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_cluster "$@"
    ;;

  gitops-cis-compliance)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_cis_compliance "$@"
    ;;

  gitops-cos)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_cos "$@"
    ;;

  gitops-cp4d)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_cp4d "$@"
    ;;

  gitops-cp4d-service)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_cp4d_service "$@"
    ;;

  gitops-suite-watson-studio-config)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_suite_watson_studio_config "$@"
    ;;

  gitops-deprovision-suite-watson-studio-config)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_suite_watson_studio_config "$@"
    ;;

  gitops-license)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_license "$@"
    ;;

  gitops-suite)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_suite "$@"
    ;;

  gitops-suite-app-install)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_suite_app_install "$@"
    ;;

  gitops-suite-app-config)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_suite_app_config "$@"
    ;;

  gitops-mas-config)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_mas_config "$@"
    ;;
 
  gitops-suite-dns)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_suite_dns "$@"
    ;;

  gitops-suite-certs)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_suite_certs "$@"
    ;;

  gitops-suite-workspace)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_suite_workspace "$@"
    ;;

  gitops-deprovision-app-config)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_app_config "$@"
    ;;

  gitops-deprovision-app-install)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_app_install "$@"
    ;;

  gitops-deprovision-suite-workspace)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_suite_workspace "$@"
    ;;

  gitops-deprovision-suite-config)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_suite_config "$@"
    ;;

  gitops-deprovision-suite)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_suite "$@"
    ;;

  gitops-deprovision-rosa)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_rosa "$@"
    ;;

  gitops-deprovision-cluster)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_cluster "$@"
    ;;

  gitops-deprovision-mongo)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_mongo "$@"
    ;;

  gitops-deprovision-cos)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_cos "$@"
    ;;

  gitops-deprovision-suite-objectstorage-config)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_suite_objectstorage_config "$@"
    ;;

  gitops-delete-kafka-config)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_delete_kafka_config "$@"
    ;;

  gitops-deprovision-efs)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_efs "$@"
    ;;

  gitops-deprovision-kafka)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_kafka "$@"
    ;;

  gitops-deprovision-suite-idp-config)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_suite_idp_config "$@"
    ;;

  gitops-deprovision-suite-smtp-config)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_suite_smtp_config "$@"
    ;;

  gitops-efs)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_efs "$@"
    ;;

  gitops-dro)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_dro "$@"
    ;;
  
  gitops-db2u)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_db2u "$@"
    ;;

  gitops-db2u-database)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_db2u_database "$@"
    ;;

  gitops-db2u-jdbc-config-rotate-password)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_db2u_jdbc_config_rotate_password "$@"
    ;;

  gitops-aws-infrastructure)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_aws_infrastructure "$@"
    ;;

  gitops-kafka)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_kafka "$@"
    ;;

  gitops-rosa)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_rosa "$@"
    ;;
  gitops-mas-fvt-preparer)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_mas_fvt_preparer "$@"
    ;;

  gitops-deprovision-db2u-database)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_deprovision_db2u_database "$@"
    ;;
  
  gitops-nvidia-gpu)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite GitOps Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/gitops/${TEXT_RESET}"
    echo
    reset_colors
    gitops_nvidia_gpu "$@"
    ;;

  *)
    echo "unknown parameter"
    exit 1
    ;;
esac
