#!/bin/bash

# Usage: mas install

function trap_exit {
  save_config
}

function trap_int {
  # Reset any modifications made to the terminal
  tset

  echo
  echo
  save_config
  exit 0
}

trap trap_exit EXIT
trap trap_int INT


CLI_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG_DIR="$HOME/.ibm-mas/config"
LOG_DIR="$HOME/.ibm-mas/logs"
LOGFILE=$LOG_DIR/mas.log

# Note: "latest" is overwritten with the actual version at build time
VERSION=latest

mkdir -p $LOG_DIR
mkdir -p $CONFIG_DIR

# General purpose internals
. $CLI_DIR/functions/internal/pipelines_install_operator
. $CLI_DIR/functions/internal/pipelines_install_tasks
. $CLI_DIR/functions/internal/catalog_utils
. $CLI_DIR/functions/internal/connect
. $CLI_DIR/functions/internal/utils
. $CLI_DIR/functions/internal/save_config
# MAS provisioning support
. $CLI_DIR/functions/provision_fyre
. $CLI_DIR/functions/provision_roks
. $CLI_DIR/functions/provision_aws
# MAS installation support
. $CLI_DIR/functions/install
. $CLI_DIR/functions/update
. $CLI_DIR/functions/upgrade
. $CLI_DIR/functions/uninstall
# Airgap support
. $CLI_DIR/functions/setup_registry
. $CLI_DIR/functions/teardown_registry
. $CLI_DIR/functions/mirror_images
. $CLI_DIR/functions/mirror_redhat
. $CLI_DIR/functions/configure_mirror
# Manage OIDC for configtool
. $CLI_DIR/functions/configtool_oidc
# Must Gather
. $CLI_DIR/functions/must_gather

case $1 in
  fyre|provision-fyre)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite FYRE Cluster Provisioner (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    provision_fyre "$@"
    ;;

  roks|provision-roks)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite ROKS Cluster Provisioner (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    provision_roks "$@"
    ;;

  aws|provision-aws)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite AWS Cluster Provisioner (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    provision_aws "$@"
    ;;

  oidc|configtool-oidc)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite OIDC for Configuration Tool (v${VERSION})${TEXT_RESET}"
    echo
    reset_colors
    configtool_oidc "$@"
    ;;

  registry|setup-registry|setup-mirror-registry|setup-airgap-registry)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap Registry Setup (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    connect
    setup_mirror_registry
    ;;

  delete-registry|teardown-registry|teardown-mirror-registry|teardown-airgap-registry)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap Registry Tear Down (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    connect
    teardown_mirror_registry
    ;;

  mirror|mirror-images)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap Image Mirror (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    mirror_to_registry "$@"
    ;;

  mirror-redhat|mirror-redhat-images)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap Red Hat Image Mirror (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    mirror_redhat "$@"
    ;;

  configure-ocp-for-mirror|configure-airgap|configure-mirror|config-airgap|config-mirror)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Air Gap OCP Setup (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET}"
    echo
    reset_colors
    configure_ocp_for_mirror "$@"
    ;;

  install)
    install "$@"
    ;;

  update)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Update Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET} and ${COLOR_CYAN}${TEXT_UNDERLINE}https://tekton.dev/${TEXT_RESET}"
    echo
    reset_colors
    update "$@"
    ;;

  upgrade)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Upgrade Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET} and ${COLOR_CYAN}${TEXT_UNDERLINE}https://tekton.dev/${TEXT_RESET}"
    echo
    reset_colors
    upgrade "$@"
    ;;

  uninstall)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Uninstall Manager (v${VERSION})${TEXT_RESET}"
    echo "Powered by ${COLOR_CYAN}${TEXT_UNDERLINE}https://github.com/ibm-mas/ansible-devops/${TEXT_RESET} and ${COLOR_CYAN}${TEXT_UNDERLINE}https://tekton.dev/${TEXT_RESET}"
    echo
    reset_colors
    uninstall "$@"
    ;;

  mustgather|must-gather)
    echo "${TEXT_UNDERLINE}IBM Maximo Application Suite Must-Gather Tool (v${VERSION})${TEXT_RESET}"
    echo
    mustgather "$@"
    ;;

  *)
    echo "unknown parameter"
    exit 1
    ;;
esac
