# mkdocs serve

site_name: Maximo Application Suite CLI
site_url: https://ibm-mas.github.io/cli

repo_name: GitHub
repo_url: https://github.com/ibm-mas/cli
edit_uri: blob/master/docs/

nav:
  - "OpenShift Management":
      - "IBM Cloud ROKS": guides/provision-roks.md
      - "AWS (IPI)": guides/provision-aws.md
      - "IBM DevIT FYRE": guides/provision-fyre.md
      - "Airgap Configuration": guides/configure-airgap.md
  - "Image Mirroring":
      - "Private Registry": guides/private-registry.md
      - "Image Mirroring (IBM)": guides/image-mirroring.md
      - "Image Mirroring (Red Hat)": commands/mirror-redhat-images.md
  - "Install and Configure":
      - "Install": guides/install.md
      - "Uninstall": guides/uninstall.md
      - "OIDC Config Tool": commands/configtool-oidc.md
      - "AI Service Install": guides/aiservice-install.md
  - "Update and Upgrade":
      - "Update": guides/update.md
      - "Upgrade": guides/upgrade.md
  - "Backup and Restore":
      - "Backup": guides/backup.md
      - "Restore": guides/restore.md
  - "Troubleshooting":
      - "Debug": commands/debug.md
      - "Must-Gather": guides/must-gather.md
  - "Examples":
      - "EAM Migration": examples/eam-migration.md
      - "Mirror Db2 Images": examples/mirror-db2.md
      - "Minimal RBAC": examples/minimal-rbac.md
      - "Image Validation": guides/image-validation.md
  - "Operator Catalogs":
      - "Overview": catalogs/index.md
      - "Jul 30 2026": catalogs/v9-260730-amd64.md
      - "Jun 25 2026": catalogs/v9-260625-amd64.md
      - "May 27 2026": catalogs/v9-260527-amd64.md
      - "Apr 30 2026": catalogs/v9-260430-amd64.md
  - "Reference":
      - "Dependencies": reference/dependencies.md
      - "Topology": reference/topology.md
      - "Cluster Extensions": reference/cluster-extensions.md
not_in_nav: |
  index.md
  catalogs/packages/*
  catalogs/v8-*
  catalogs/v9-*

theme:
  name: carbon
  prefix: IBM
  header_nav_items:
    - title: Ansible
      url: https://ibm-mas.github.io/ansible-devops/
    - title: CLI
      active: true

extra_css:
  - extra.css

markdown_extensions:
  - toc:
      permalink: true
  - admonition
    # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
    # Note
    # Abstract
    # Info
    # Tip
    # Success
    # Question
    # Warning
    # Failure
    # Danger
    # Bug
    # Example
    # Quote

plugins:
  - search: {}
  - mas_catalogs
  - mas_cli
  - redirects:
      redirect_maps:
        "guides/architecture/core.md": "https://www.ibm.com/docs/en/mas-cd/continuous-delivery?topic=reference-maximo-application-suite-core-services"
        "guides/backup-and-restore.md": "guides/backup.md"
        "guides/mas-pods-explained.md": "https://www.ibm.com/docs/en/mas-cd/continuous-delivery?topic=reference-maximo-application-suite-pod-details"
        "guides/choosing-the-right-catalog.md": "catalogs/index.md"
        "commands/mirror-images.md": "guides/image-mirroring.md"
        "commands/install.md": "guides/install.md"
        "commands/update.md": "guides/update.md"
        "commands/upgrade.md": "guides/upgrade.md"
        "commands/provision-fyre.md": "guides/provision-fyre.md"
        "commands/provision-roks.md": "guides/provision-roks.md"
        "commands/provision-rosa.md": "guides/provision-roks.md"
        "commands/provision-aws.md": "guides/provision-aws.md"
        "commands/configure-airgap.md": "guides/configure-airgap.md"
        "commands/setup-registry.md": "guides/private-registry.md"
        "commands/teardown-registry.md": "guides/private-registry.md"
        "commands/uninstall.md": "guides/uninstall.md"
        "commands/backup.md": "guides/backup.md"
        "commands/restore.md": "guides/restore.md"
        "commands/must-gather.md": "guides/must-gather.md"
  - glightbox:
      shadow: true
      caption_position: bottom
      auto_caption: true
      touchNavigation: false
      background: black
