---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mas:{{ mas_instance_id }}:install-pipeline:openshift-console
  namespace: openshift-console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mas:{{ mas_instance_id }}:install-pipeline:openshift-console
subjects:
  - kind: ServiceAccount
    name: mas-{{ mas_instance_id }}-install-pipeline
    namespace: mas-{{ mas_instance_id }}-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mas:{{ mas_instance_id }}:install-pipeline:openshift-console
  namespace: openshift-console
rules:
  # Pipeline task needs to read the console route to include cluster URL in Slack notifications
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
