---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mas:{{ mas_instance_id }}:install-pipeline:openshift-nfd
  namespace: openshift-nfd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mas:{{ mas_instance_id }}:install-pipeline:openshift-nfd
subjects:
  - kind: ServiceAccount
    name: mas-{{ mas_instance_id }}-install-pipeline
    namespace: mas-{{ mas_instance_id }}-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mas:{{ mas_instance_id }}:install-pipeline:openshift-nfd
  namespace: openshift-nfd
rules:
  # Nvidia GPU operator installation requires operator subscription
  - apiGroups:
      - operators.coreos.com
    resources:
      - installplans
      - operatorgroups
      - subscriptions
    verbs:
      - get
      - list
      - create
      - patch
  # Node Feature Discovery CRD management
  - apiGroups:
      - nfd.openshift.io
    resources:
      - nodefeaturediscoveries
    verbs:
      - get
      - list
      - create
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mas:{{ mas_instance_id }}:install-pipeline:nvidia-gpu-operator
  namespace: nvidia-gpu-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mas:{{ mas_instance_id }}:install-pipeline:nvidia-gpu-operator
subjects:
  - kind: ServiceAccount
    name: mas-{{ mas_instance_id }}-install-pipeline
    namespace: mas-{{ mas_instance_id }}-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mas:{{ mas_instance_id }}:install-pipeline:nvidia-gpu-operator
  namespace: nvidia-gpu-operator
rules:
  # Nvidia GPU operator installation requires operator subscription
  - apiGroups:
      - operators.coreos.com
    resources:
      - installplans
      - operatorgroups
      - subscriptions
    verbs:
      - get
      - list
      - create
      - patch
  # GPU operator CRD management
  - apiGroups:
      - nvidia.com
    resources:
      - clusterpolicies
    verbs:
      - get
      - list
      - create
      - patch
      - update
      - watch
