---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mas:{{ mas_instance_id }}:install-pipeline:redhat-ods-operator
  namespace: redhat-ods-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mas:{{ mas_instance_id }}:install-pipeline:redhat-ods-operator
subjects:
  - kind: ServiceAccount
    name: mas-{{ mas_instance_id }}-install-pipeline
    namespace: mas-{{ mas_instance_id }}-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mas:{{ mas_instance_id }}:install-pipeline:redhat-ods-operator
  namespace: redhat-ods-operator
rules:
  # RHOAI installation requires namespace management
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - patch
  
  # RHOAI operator subscription
  - apiGroups:
      - operators.coreos.com
    resources:
      - installplans
      - operatorgroups
      - subscriptions
    verbs:
      - get
      - list
      - create
      - patch
  
  # RHOAI requires secrets for registry credentials and database credentials
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - patch
      - delete
  
  # RHOAI requires service accounts
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - create
      - patch
  
  # RHOAI instance creation and management
  - apiGroups:
      - datasciencecluster.opendatahub.io
    resources:
      - datascienceclusters
    verbs:
      - get
      - create
      - patch
      - list
      - watch
  
  # RHOAI requires configmaps
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - patch
  
  # RHOAI requires PVCs
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - create
      - patch
      - list

  # RHOAI setup requires pod exec access to copy files and run commands
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - pods/exec
    verbs:
      - get
      - list
      - create

  # RHOAI requires cert-manager issuers and certificates for SSL
  - apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - certificates
    verbs:
      - get
      - create
      - patch
      - list
      - watch

  # RHOAI requires routes for external access
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - create
      - patch
      - list

  # RHOAI requires routes for external access
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - openshift-ai-llminferenceservice-multi-node-scc
      - openshift-ai-llminferenceservice-scc
    verbs:
      - get
      - patch
      - update
