#!/usr/bin/env python
# *****************************************************************************
# Copyright (c) 2024 IBM Corporation and other Contributors.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# *****************************************************************************

import sys
import logging
import logging.handlers

from jinja2.exceptions import TemplateNotFound
from urllib3.exceptions import MaxRetryError
from kubeconfig.exceptions import KubectlCommandError
from kubernetes.client.exceptions import ApiException

from mas.cli.uninstall.app import UninstallApp
logger = logging.getLogger(__name__)

if __name__ == '__main__':
    try:
        app = UninstallApp()
        app.uninstall(sys.argv)
    except KeyboardInterrupt as e:
        pass
    except ApiException as e:
        logger.exception(e, stack_info=True)
        app.fatalError(message=f"An error occured communicating with the target server: {e.reason} ({e.status})")
    except MaxRetryError as e:
        logger.exception(e, stack_info=True)
        app.fatalError(message="Unable to connect to API server", exception=e)
    except TemplateNotFound as e:
        logger.exception(e, stack_info=True)
        app.fatalError("Could not find template", exception=e)
    except KubectlCommandError as e:
        logger.exception(e, stack_info=True)
        app.fatalError("Could not execute kubectl command", exception=e)