#!/usr/bin/env python
# *****************************************************************************
# Copyright (c) 2024 IBM Corporation and other Contributors.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# *****************************************************************************

import logging
import logging.handlers
from sys import argv

from mas.cli.install.app import InstallApp
# from mas.cli.upgrade.app import UpgradeApp
from mas.cli.uninstall.app import UninstallApp

from urllib3.exceptions import MaxRetryError
from jinja2.exceptions import TemplateNotFound
from kubeconfig.exceptions import KubectlCommandError
from kubernetes.client.exceptions import ApiException

logger = logging.getLogger(__name__)

if __name__ == '__main__':
    try:
        function = argv[1]

        if function == "install":
            app = InstallApp()
            app.install(argv[2:])
        elif function == "uninstall":
            app = UninstallApp()
            app.uninstall(argv[2:])
        # elif function == "upgrade":
        #     app = UpgradeApp()
        #     app.upgrade(argv[2:])

    except KeyboardInterrupt as e:
        pass
    except ApiException as e:
        logger.exception(e, stack_info=True)
        app.fatalError(message=f"An error occured communicating with the target server: {e.reason} ({e.status})")
    except MaxRetryError as e:
        logger.exception(e, stack_info=True)
        app.fatalError(message="Unable to connect to API server", exception=e)
    except TemplateNotFound as e:
        logger.exception(e, stack_info=True)
        app.fatalError("Could not find template", exception=e)
    except KubectlCommandError as e:
        logger.exception(e, stack_info=True)
        app.fatalError("Could not execute kubectl command", exception=e)
