#!/bin/bash

function connect() {
  echo
  echo_h2 "1. Set Target OpenShift Cluster"

  PROMPT_FOR_LOGIN=false
  oc whoami &>> $LOGFILE
  if [[ $? == "0" ]]; then
    OCP_CONSOLE_ROUTE=$(oc -n openshift-console get route console -o=jsonpath='{.spec.host}')
    echo -e "Connected to OCP cluster: \n   ${COLOR_CYAN}${TEXT_UNDERLINE}https://$OCP_CONSOLE_ROUTE${COLOR_RESET}${TEXT_RESET}" | tee $LOGFILE
    if ! prompt_for_confirm_default_yes "Proceed with this cluster?"; then
      PROMPT_FOR_LOGIN=true
    fi
  else
    PROMPT_FOR_LOGIN=true
  fi

  if [[ $PROMPT_FOR_LOGIN == "true" ]]; then
    read -e -p "$COLOR_YELLOW  Server URL ..... $COLOR_MAGENTA> " -i "$OCP_LOGIN_URL" OCP_LOGIN_URL
    read -e -p "$COLOR_YELLOW  Login Token  ... $COLOR_MAGENTA> " -i "$OCP_LOGIN_TOKEN" OCP_LOGIN_TOKEN
    echo -ne "${COLOR_RESET}\033[1K"

    oc login --token=$OCP_LOGIN_TOKEN --server=$OCP_LOGIN_URL &>> $LOGFILE
    if [[ $? != "0" ]]; then
      echo_warning "Login to $OCP_LOGIN_URL failed"
      exit 1
    fi
    OCP_CONSOLE_ROUTE=$(oc -n openshift-console get route console -o=jsonpath='{.spec.host}')
    echo -e "Connected to OCP cluster: \n   ${COLOR_CYAN}${TEXT_UNDERLINE}https://$OCP_CONSOLE_ROUTE${TEXT_RESET}${COLOR_RESET}" | tee $LOGFILE
    prompt_for_confirm "Proceed with installation on this cluster?" || exit 0
  fi
  ALREADY_CONFIRMED=true
  echo -ne "${COLOR_RESET}\033[1K"
}


function confirm_connection() {
  oc whoami &>> $LOGFILE
  if [[ $? == "0" ]]; then
    OCP_CONSOLE_ROUTE=$(oc -n openshift-console get route console -o=jsonpath='{.spec.host}')
    echo -e "Connected to OCP cluster: \n   ${COLOR_CYAN}${TEXT_UNDERLINE}https://$OCP_CONSOLE_ROUTE${COLOR_RESET}${TEXT_RESET}" | tee $LOGFILE
  else
    echo_warning "You are not connected to an OCP cluster.  Run oc login, or use the CLI interactive mode."
    exit 1
  fi
}