#!/usr/bin/env bash

function gitops_suite_config_help() {
  [[ -n "$1" ]] && echo_warning "$1"
  reset_colors
  cat << EOM
Usage:
  mas gitops_suite_config [options]
Where ${COLOR_YELLOW}specified${TEXT_RESET} each option may also be defined by setting the appropriate environment variable.
When no options are specified on the command line, interactive-mode will be enabled by default.

Options:

GitOps Configuration:
  -d, --dir ${COLOR_YELLOW}GITOPS_WORKING_DIR${TEXT_RESET}           Working directory for GitOps repository
  -g, --gitops-version ${COLOR_YELLOW}GITOPS_VERSION${TEXT_RESET}    Version of ibm-mas/gitops to use
  -a, --account-id ${COLOR_YELLOW}ACCOUNT_ID${TEXT_RESET}            Account name that the cluster belongs to
  -c, --cluster-id ${COLOR_YELLOW}CLUSTER_ID${TEXT_RESET}            Cluster ID
  -m, --mas-instance-id ${COLOR_YELLOW}MAS_INSTANCE_ID${TEXT_RESET}  IBM Suite Maximo Application Suite Instance ID

Secrets Manager:
      --secrets-path ${COLOR_YELLOW}SECRETS_PATH${TEXT_RESET}                    Secrets Manager path
      --secrets-key-seperator ${COLOR_YELLOW}SECRETS_KEY_SEPERATOR${TEXT_RESET}  Secrets Manager key seperator string

MongoDb Provider Selection:
      --mongo-provider ${COLOR_YELLOW}MONGODB_PROVIDER${TEXT_RESET}  The mongodb provider to install. Only "aws" is supported

DRO Configuration:
      --dro-url ${COLOR_YELLOW}DRO_URL${TEXT_RESET}                                 The URL for the DRO instance
      --dro-contact-email ${COLOR_YELLOW}DRO_CONTACT_EMAIL${TEXT_RESET}             The email address to register with DRO
      --dro-contact-firstname ${COLOR_YELLOW}DRO_URL${TEXT_RESET}                   The first name to register with DRO
      --dro-contact-lastname ${COLOR_YELLOW}DRO_URL${TEXT_RESET}                    The last name to register with DRO
      --dro-ca-certificate-file ${COLOR_YELLOW}DRO_CA_CERTIFICATE_FILE${TEXT_RESET} The location of a file containing the DRO CA certificate

Automatic GitHub Push:
  -P, --github-push ${COLOR_YELLOW}GITHUB_PUSH${TEXT_RESET}        Enable automatic push to GitHub
  -H, --github-host ${COLOR_YELLOW}GITHUB_HOST${TEXT_RESET}        GitHub Hostname for your GitOps repository
  -O, --github-org  ${COLOR_YELLOW}GITHUB_ORG${TEXT_RESET}         Github org for your GitOps repository
  -R, --github-repo ${COLOR_YELLOW}GITHUB_REPO${TEXT_RESET}        Github repo for your GitOps repository
  -B, --git-branch ${COLOR_YELLOW}GIT_BRANCH${TEXT_RESET}          Git branch to commit to of your GitOps repository
  -M, --git-commit-msg ${COLOR_YELLOW}GIT_COMMIT_MSG${TEXT_RESET}  Git commit message to use when committing to of your GitOps repository
  -S , --github-ssh  ${COLOR_YELLOW}GIT_SSH${TEXT_RESET}           Git ssh key path

Other Commands:
  -h, --help                                      Show this help message
EOM
  [[ -n "$1" ]] && exit 1 || exit 0
}

function gitops_suite_config_noninteractive() {
  GITOPS_WORKING_DIR=$PWD/working-dir
  SECRETS_KEY_SEPERATOR="/"
  GIT_COMMIT_MSG="gitops-suite-config commit"
  export GITOPS_VERSION=${GITOPS_VERSION:-poc}

  # TODO: will need to add explicit args to pipeline when we start using this code to deploy to MCSP
  export REGION=${REGION:-${SM_AWS_REGION}}

  while [[ $# -gt 0 ]]
  do
    key="$1"
    shift
    case $key in
      -d|--dir)
        export GITOPS_WORKING_DIR=$1 && shift
        ;;
      -g|--gitops-version)
        export GITOPS_VERSION=$1 && shift
        ;;
      -a|--account-id)
        export ACCOUNT_ID=$1 && shift
        ;;
      -c|--cluster-id)
        export CLUSTER_ID=$1 && shift
        ;;
      -r|--region)
        export REGION=$1 && shift
        ;;
      -m|--mas-instance-id)
        export MAS_INSTANCE_ID=$1 && shift
        ;;

      # MongoDb Provider Selection
      --mongo-provider)
        export MONGODB_PROVIDER=$1 && shift
        ;;

      # DRO
      --dro-url)
        export DRO_URL=$1 && shift
        ;;
      --dro-contact-email)
        export DRO_CONTACT_EMAIL=$1 && shift
        ;;
      --dro-contact-firstname)
        export DRO_CONTACT_FIRSTNAME=$1 && shift
        ;;
      --dro-contact-lastname)
        export DRO_CONTACT_LASTNAME=$1 && shift
        ;;
      --dro-ca-certificate-file)
        export DRO_CA_CERTIFICATE_FILE=$1 && shift
        ;;

      # Secrets Manager
      --secrets-path)
        export SECRETS_PATH=$1 && shift
        ;;
      --secrets-key-seperator)
        export SECRETS_KEY_SEPERATOR=$1 && shift
        ;;

      # Automatic GitHub Push
      -P|--github-push)
        export GITHUB_PUSH=true
        ;;
      -H|--github-host)
        export GITHUB_HOST=$1 && shift
        ;;
      -O|--github-org)
        export GITHUB_ORG=$1 && shift
        ;;
      -R|--github-repo)
        export GITHUB_REPO=$1 && shift
        ;;
      -B|--git-branch)
        export GIT_BRANCH=$1 && shift
        ;;
      -M|--git-commit-msg)
        export GIT_COMMIT_MSG=$1 && shift
        ;;
       -S|--github-ssh)
        export GIT_SSH=$1 && shift
        ;;

      -h|--help)
        gitops_suite_config_help
        ;;
      *)
        # unknown option
        echo -e "${COLOR_RED}Usage Error: Unsupported option \"${key}\"${COLOR_RESET}\n"
        gitops_suite_config_help "Usage Error: Unsupported option \"${key}\" "
        exit 1
        ;;
      esac
  done

  [[ -z "$DRO_URL" ]] && gitops_suite_config_help "DRO_URL is not set"
  [[ -z "$DRO_CONTACT_EMAIL" ]] && gitops_suite_config_help "DRO_CONTACT_EMAIL is not set"
  [[ -z "$DRO_CONTACT_FIRSTNAME" ]] && gitops_suite_config_help "DRO_CONTACT_FIRSTNAME is not set"
  [[ -z "$DRO_CONTACT_LASTNAME" ]] && gitops_suite_config_help "DRO_CONTACT_LASTNAME is not set"
  [[ -z "$DRO_CA_CERTIFICATE_FILE" ]] && gitops_suite_config_help "DRO_CA_CERTIFICATE_FILE is not set"

  [[ -z "$GITOPS_WORKING_DIR" ]] && gitops_suite_config_help "GITOPS_WORKING_DIR is not set"
  [[ -z "$GITOPS_VERSION" ]] && gitops_suite_config_help "GITOPS_VERSION is not set"
  [[ -z "$CLUSTER_ID" ]] && gitops_suite_config_help "CLUSTER_ID is not set"
  [[ -z "$ACCOUNT_ID" ]] && gitops_suite_config_help "ACCOUNT_ID is not set"
  if [[ "$GITHUB_PUSH" == "true" ]]; then
    [[ -z "$GITHUB_HOST" ]] && gitops_suite_config_help "GITHUB_HOST is not set"
    [[ -z "$GITHUB_ORG" ]] && gitops_suite_config_help "GITHUB_ORG is not set"
    [[ -z "$GITHUB_REPO" ]] && gitops_suite_config_help "GITHUB_REPO is not set"
    [[ -z "$GIT_BRANCH" ]] && gitops_suite_config_help "GIT_BRANCH is not set"
  fi
}

function gitops_suite_config() {
  # Take the first parameter off (it will be create-gitops)
  shift
  if [[ $# -gt 0 ]]; then
    gitops_suite_config_noninteractive "$@"
  else
    echo "Not supported yet"
    exit 1
    gitops_suite_config_interactive
  fi

  mkdir -p ${GITOPS_WORKING_DIR}
  GITOPS_INSTANCE_DIR=${GITOPS_WORKING_DIR}/${GITHUB_REPO}/${ACCOUNT_ID}/${REGION}/${CLUSTER_ID}/${MAS_INSTANCE_ID}

  echo
  reset_colors
  echo_h2 "Review Settings"

  echo "${TEXT_DIM}"
  echo_h2 "Target" "    "
  echo_reset_dim "Account ID............................. ${COLOR_MAGENTA}${ACCOUNT_ID}"
  echo_reset_dim "Cluster ID ............................ ${COLOR_MAGENTA}${CLUSTER_ID}"
  echo_reset_dim "Instance Config Directory ............. ${COLOR_MAGENTA}${GITOPS_INSTANCE_DIR}"
  reset_colors

  echo "${TEXT_DIM}"
  echo_h2 "Secrets Manager" "    "
  echo_reset_dim "Secrets Path .......................... ${COLOR_MAGENTA}${SECRETS_PATH}"
  reset_colors

  echo "${TEXT_DIM}"
  echo_h2 "Mongo" "    "
  echo_reset_dim "Mongo Provider  ....................... ${COLOR_MAGENTA}${MONGODB_PROVIDER}"
  reset_colors

  echo "${TEXT_DIM}"
  echo_h2 "DRO" "    "
  echo_reset_dim "DRO Url  .............................. ${COLOR_MAGENTA}${DRO_URL}"
  echo_reset_dim "DRO Contact Email  .................... ${COLOR_MAGENTA}${DRO_CONTACT_EMAIL}"
  echo_reset_dim "DRO Contact First Name  ............... ${COLOR_MAGENTA}${DRO_CONTACT_FIRSTNAME}"
  echo_reset_dim "DRO Contact Last Name  ................ ${COLOR_MAGENTA}${DRO_CONTACT_LASTNAME}"
  echo_reset_dim "DRO Certificate File  ................. ${COLOR_MAGENTA}${DRO_CA_CERTIFICATE_FILE}"
  reset_colors

  echo "${TEXT_DIM}"
  echo_h2 "GitOps Source" "    "
  echo_reset_dim "GitOps URL ............................ ${COLOR_MAGENTA}https://github.com/ibm-mas/gitops"
  echo_reset_dim "GitOps Version ........................ ${COLOR_MAGENTA}${GITOPS_VERSION}"
  reset_colors

  echo "${TEXT_DIM}"
  if [[ "$GITHUB_PUSH" == "true" ]]; then
    echo_h2 "GitOps Target" "    "
    echo_reset_dim "Automatic Push ........................ ${COLOR_GREEN}Enabled"
    echo_reset_dim "Working Directory ..................... ${COLOR_MAGENTA}${GITOPS_WORKING_DIR}"
    echo_reset_dim "Host .................................. ${COLOR_MAGENTA}${GITHUB_HOST}"
    echo_reset_dim "Organization .......................... ${COLOR_MAGENTA}${GITHUB_ORG}"
    echo_reset_dim "Repository ............................ ${COLOR_MAGENTA}${GITHUB_REPO}"
    echo_reset_dim "Branch ................................ ${COLOR_MAGENTA}${GIT_BRANCH}"
  else
    echo_h2 "GitOps Target" "    "
    echo_reset_dim "Automatic Push ........................ ${COLOR_RED}Disabled"
    echo_reset_dim "Working Directory ..................... ${COLOR_MAGENTA}${GITOPS_WORKING_DIR}"
  fi
  reset_colors

  echo "${TEXT_DIM}"
  echo_h2 "IBM Suite License Service" "    "
  echo_reset_dim "SLS URL  .............................. ${COLOR_MAGENTA}https://sls.mas-${MAS_INSTANCE_ID}-sls.svc"
  reset_colors

  echo "${TEXT_DIM}"
  echo_h2 "IBM Maximo Application Suite" "    "
  echo_reset_dim "Instance ID ........................... ${COLOR_MAGENTA}${MAS_INSTANCE_ID}"
  reset_colors

  # Define cluster-level secrets used
  # ---------------------------------------------------------------------------
  # Note that these cluster-level secrets are set up by gitops-mongo
  export SECRET_KEY_MONGO_INFO=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}mongo#info
  export SECRET_KEY_DRO_API_TOKEN=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}dro#dro_api_token
  export DRO_CA_CERTIFICATE=$(cat ${DRO_CA_CERTIFICATE_FILE})

  # Get the cluster-level secrets used
  # ---------------------------------------------------------------------------
  CURRENT_DIR=$PWD
  TEMP_DIR=$CURRENT_DIR/tmp-suite-config
  rm -rf $TEMP_DIR
  mkdir -p $TEMP_DIR

  # by default yaml. pass aws, in case if configuring with DocDB
  export MONGODB_PROVIDER=${MONGODB_PROVIDER:-"yaml"}

  export MONGO_SECRET_FILE=$TEMP_DIR/mongo-secret.json
  export MONGO_CONFIG_FILE=$TEMP_DIR/mongo-info.yaml

  sm_login

  if [ $MONGODB_PROVIDER == 'yaml' ]; then
    sm_get_secret_file ${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}mongo $MONGO_SECRET_FILE
  elif [ $MONGODB_PROVIDER == 'aws' ]; then
    sm_get_secret_file ${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}mongo $MONGO_SECRET_FILE
  fi

  jq -r .info $MONGO_SECRET_FILE > $MONGO_CONFIG_FILE

  # wait till SLS licenseservice is in ready state starts
  wait_period=0
  while true
  do
    wait_period=$(($wait_period+30))
    if [ $wait_period -gt 600 ];then
      echo_reset_dim "${COLOR_RED}SLS licenseservice is not  ready, exiting"
      exit 1
    else
      sleep 30
    fi
    #export LICENSE_SERVICE_INITIALIZED_STATUS=`oc get licenseservice/sls -n mas-${MAS_INSTANCE_ID}-sls  -o=jsonpath="{.status.conditions[?(@.type=='Initialized')].status}"`
    export LICENSE_SERVICE_READY_STATUS=`oc get licenseservices.sls.ibm.com/sls -n mas-${MAS_INSTANCE_ID}-sls  -o=jsonpath="{.status.conditions[?(@.type=='Ready')].status}"`
    echo "LICENSE_SERVICE_INITIALIZED_STATUS .... ${COLOR_MAGENTA}${LICENSE_SERVICE_INITIALIZED_STATUS}"
    echo "LICENSE_SERVICE_READY_STATUS .......... ${COLOR_MAGENTA}${LICENSE_SERVICE_READY_STATUS}"
    if [[ "$LICENSE_SERVICE_READY_STATUS" == "True" ]]; then
      break
    fi
  done
  # wait till SLS licenseservice is in ready state done

  # Get the instance-level values to used
  # ---------------------------------------------------------------------------
  #Need to get the sls CA certificate and the sls registration key from sls-suite-registration configmap
  # We could move this into a pre-sync job maybe so that changes in sls can be synced with the config via argo
  export SLS_REGISTRATION_KEY=$(oc get cm sls-suite-registration -n mas-${MAS_INSTANCE_ID}-sls -o jsonpath='{.data.registrationKey}')
  export SLS_CA_CERTIFICATE=$(oc get cm sls-suite-registration -n mas-${MAS_INSTANCE_ID}-sls -o jsonpath='{.data.ca}')
  export SECRET_NAME_MONGO=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}mongo
  export SECRET_KEY_MONGO_USERNAME=${SECRET_NAME_MONGO}#username
  export SECRET_KEY_MONGO_PASSWORD=${SECRET_NAME_MONGO}#password

  # Instance-level secrets to create
  # ---------------------------------------------------------------------------
  export SECRET_NAME_SLS=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}sls
  export SECRET_KEY_SLS_REGISTRATION_KEY=${SECRET_NAME_SLS}#registration_key

  # Create SLS Registration key for this MAS Instance
  # ---------------------------------------------------------------------------
  echo " $SECRET_NAME_SLS "{\"registration_key\": \"$SLS_REGISTRATION_KEY\"}""
  sm_update_secret $SECRET_NAME_SLS "{\"registration_key\": \"$SLS_REGISTRATION_KEY\" }"

  if [ -z $GIT_SSH ]; then
    export GIT_SSH="false"
  fi


  # Clone github target repo
  # ---------------------------------------------------------------------------
  if [ "$GITHUB_PUSH" == "true" ]; then
    echo
    echo_h2 "Cloning GitHub repo $GITHUB_ORG $GITHUB_REPO"
    clone_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_WORKING_DIR $GIT_SSH
  fi
  mkdir -p ${GITOPS_INSTANCE_DIR}

  # Generate ArgoApps
  # ---------------------------------------------------------------------------
  # Per MAS instance
  echo "- IBM MAS Core Configs"
  jinja -X .+ -d $MONGO_CONFIG_FILE $CLI_DIR/templates/gitops/appset-configs/ibm-mas-core/ibm-mas-configs.yaml.j2 -o ${GITOPS_INSTANCE_DIR}/ibm-mas-configs.yaml

  # Commit and push to github target repo
  # ---------------------------------------------------------------------------
  if [ "$GITHUB_PUSH" == "true" ]; then

    echo
    echo_h2 "Commit and push changes to GitHub repo $GITHUB_ORG $GITHUB_REPO"
    save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_INSTANCE_DIR "${GIT_COMMIT_MSG}"
    remove_git_repo_clone $GITOPS_WORKING_DIR/$GITHUB_REPO

    # Align with https://github.com/ibm-mas/gitops/blob/0adcff6b58e267ea016a513012ecddc0dfabfc66/README.md?plain=1#L11
    export ROOT_APP_NAME="mas-root"

    # Align with https://github.com/ibm-mas/gitops/blob/f057eb850c455ad34e067b1e79c752af8f745aa2/application-sets/ibm-mas-core.yaml#L41
    GENERATED_APP_NAME_CORE="ibm-mas-core-${ACCOUNT_ID}-${REGION}-${CLUSTER_ID}-${MAS_INSTANCE_ID}"

    # Align with https://github.com/ibm-mas/gitops/blob/14a6f2367176e99de561d07bc16607aabe03199f/application-sets/ibm-sls.yaml#L38
    GENERATED_APP_NAME_SLS="ibm-sls-${ACCOUNT_ID}-${REGION}-${CLUSTER_ID}-${MAS_INSTANCE_ID}"


    argocd_login
    argocd_sync "${ROOT_APP_NAME}"
    argocd_hard_refresh "${GENERATED_APP_NAME_CORE}"
    argocd_hard_refresh "${GENERATED_APP_NAME_SLS}"

    check_argo_app_synced "${GENERATED_APP_NAME_CORE}" "${ROOT_APP_NAME}" mas-${MAS_INSTANCE_ID}-core
    check_argo_app_healthy "${GENERATED_APP_NAME_CORE}" "${ROOT_APP_NAME}"

    check_argo_app_synced "${GENERATED_APP_NAME_SLS}" "${ROOT_APP_NAME}" mas-${MAS_INSTANCE_ID}-sls
    check_argo_app_healthy "${GENERATED_APP_NAME_SLS}" "${ROOT_APP_NAME}"


  fi

}
