#!/usr/bin/env bash


function gitops_rds_db2_database_help() {
  [[ -n "$1" ]] && echo_warning "$1"
  reset_colors
  cat << EOM
Usage:
  mas gitops_rds_db2_database [options]
Where ${COLOR_YELLOW}specified${TEXT_RESET} each option may also be defined by setting the appropriate environment variable.
When no options are specified on the command line, interactive-mode will be enabled by default.

GitOps Configuration:
  -d, --dir ${COLOR_YELLOW}GITOPS_WORKING_DIR${TEXT_RESET}           Directory for GitOps repository
  -a, --account-id ${COLOR_YELLOW}ACCOUNT_ID${TEXT_RESET}            Account name that the cluster belongs to
  -r, --region-id ${COLOR_YELLOW}REGION_ID${TEXT_RESET}              Region ID
  -c, --cluster-id ${COLOR_YELLOW}CLUSTER_ID${TEXT_RESET}            Cluster ID

IBM Maximo Application Suite:
      -m, --mas-instance-id ${COLOR_YELLOW}MAS_INSTANCE_ID${TEXT_RESET}   IBM Suite Maximo Application Suite Instance ID      
      --mas-app-id ${COLOR_YELLOW}MAS_APP_ID${TEXT_RESET}                 IBM Suite Maximo Application Suite App that will use this db2u instance      

IBM RDS DB2:
      --db2-instance-registry-yaml ${COLOR_YELLOW}DB2_INSTANCE_REGISTRY_YAML${TEXT_RESET}                     Yaml file containing the rds db2 cluster instance registry section.
      --db2-instance-dbm-config-yaml ${COLOR_YELLOW}DB2_INSTANCE_DBM_CONFIG_YAML${TEXT_RESET}                 Yaml file containing the rds db2 cluster instance dbm config section.
      --db2-database-db-config-yaml ${COLOR_YELLOW}DB2_DATABASE_DB_CONFIG_YAML${TEXT_RESET}                   Yaml file containing the rds db2 cluster database db config section.
      --db2-addons-audit-config-yaml ${COLOR_YELLOW}DB2_ADDONS_AUDIT_CONFIG_YAML${TEXT_RESET}                 Yaml file containing the rds db2 cluster addons audit config section.
      --jdbc-connection-url-additional-params ${COLOR_YELLOW}JDBC_CONNECTION_URL_ADDITIONAL_PARAMS${TEXT_RESET}  Additional parameters for JDBC connection URL
      --replica-db  ${COLOR_YELLOW}REPLICA_DB${TEXT_RESET}                                                       Flag to know that this is ReplicaDB instance
      --rds-db2-backup-manage ${COLOR_YELLOW}RDS_DB2_BACKUP_MANAGE${TEXT_RESET}                                  Flag to know that this is RDS DB2 backup instance manage
      --rds-db2-backup-iot ${COLOR_YELLOW}RDS_DB2_BACKUP_IOT${TEXT_RESET}                                        Flag to know that this is RDS DB2 backup instance IOT
      --rds-bd2-backup-facilities ${COLOR_YELLOW}RDS_DB2_BACKUP_FACILITIES${TEXT_RESET}                          Flag to know that this is RDS DB2 backup instance manage 

Secrets Manager:
      --secrets-path ${COLOR_YELLOW}SECRETS_PATH${TEXT_RESET}                     Secrets Manager path
      --secrets-key-seperator ${COLOR_YELLOW}SECRETS_KEY_SEPERATOR${TEXT_RESET}   Secrets Manager key seperator string      

Automatic GitHub Push:
  -P, --github-push ${COLOR_YELLOW}GITHUB_PUSH${TEXT_RESET}        Enable automatic push to GitHub
  -H, --github-host ${COLOR_YELLOW}GITHUB_HOST${TEXT_RESET}        GitHub Hostname for your GitOps repository
  -O, --github-org  ${COLOR_YELLOW}GITHUB_ORG${TEXT_RESET}         Github org for your GitOps repository
  -R, --github-repo ${COLOR_YELLOW}GITHUB_REPO${TEXT_RESET}        Github repo for your GitOps repository
  -B, --git-branch ${COLOR_YELLOW}GIT_BRANCH${TEXT_RESET}          Git branch to commit to of your GitOps repository
  -M, --git-commit-msg ${COLOR_YELLOW}GIT_COMMIT_MSG${TEXT_RESET}  Git commit message to use when committing to of your GitOps repository
  -S , --github-ssh  ${COLOR_YELLOW}GIT_SSH${TEXT_RESET}           Git ssh key path

Other Commands:
  -h, --help                                      Show this help message
EOM
  [[ -n "$1" ]] && exit 1 || exit 0
}

function gitops_rds_db2_database_noninteractive() {
  GITOPS_WORKING_DIR=$PWD/working-dir
  SECRETS_KEY_SEPERATOR="/"
  GIT_COMMIT_MSG="gitops-db2u-database commit"

  # TODO: will need to add explicit args to pipeline when we start using this code to deploy to MCSP
  export REGION=${REGION:-${SM_AWS_REGION}}
  export REGION_ID=${REGION_ID:-${REGION}}
  export CLUSTER_URL=${CLUSTER_URL:-"https://kubernetes.default.svc"} # use an in-cluster argocd worker (which fvtsaas does)

  while [[ $# -gt 0 ]]
  do
    key="$1"
    shift
    case $key in
      # GitOps Configuration
      -d|--dir)
        export GITOPS_WORKING_DIR=$1 && shift
        ;;
      -g|--gitops-version)
        echo "${COLOR_YELLOW}WARNING: the -g|--gitops-version parameter is deprecated; it has no effect and will be removed in a future release${COLOR_RESET}"
        shift
        ;;
      -a|--account-id)
        export ACCOUNT_ID=$1 && shift
        ;;
      -c|--cluster-id)
        export CLUSTER_ID=$1 && shift
        ;;
      -r|--region)
        export REGION_ID=$1 && shift
        ;;
      -u|--cluster-url)
        export CLUSTER_URL=$1 && shift
        ;;

      # RDS Config yaml files
      --db2-instance-registry-yaml)
        export DB2_INSTANCE_REGISTRY_YAML=$1 && shift
        ;;
      --db2-instance-dbm-config-yaml)
        export DB2_INSTANCE_DBM_CONFIG_YAML=$1 && shift
        ;;
      --db2-addons-audit-config-yaml)
        export DB2_ADDONS_AUDIT_CONFIG_YAML=$1 && shift
        ;;
      --db2-database-db-config-yaml)
        export DB2_DATABASE_DB_CONFIG_YAML=$1 && shift
        ;;

      # MAS
      -m|--mas-instance-id)
        export MAS_INSTANCE_ID=$1 && shift
        ;;
      --mas-app-id)
        export MAS_APP_ID=$1 && shift
        ;;
      --mas-annotations)
        export MAS_ANNOTATIONS=$1 && shift
        ;;

      # Secrets Manager
      --secrets-path)
        export SECRETS_PATH=$1 && shift
        ;;
      --secrets-key-seperator)
        export SECRETS_KEY_SEPERATOR=$1 && shift
        ;;

      # RDS-DB2
      --jdbc-connection-url-additional-params)
        export JDBC_CONNECTION_URL_ADDITIONAL_PARAMS=$1 && shift
        ;;
      --replica-db)
        export REPLICA_DB=$1 && shift
        ;;
      --rds-db2-backup-manage)
        export RDS_DB2_BACKUP_MANAGE=$1 && shift
        ;;
      --rds-db2-backup-iot)
        export RDS_DB2_BACKUP_IOT=$1 && shift
        ;;
      --rds-db2-backup-facilities)
        export RDS_DB2_BACKUP_FACILITIES=$1 && shift
        ;;
      # Automatic GitHub Push
      -P|--github-push)
        export GITHUB_PUSH=true
        ;;
      -H|--github-host)
        export GITHUB_HOST=$1 && shift
        ;;
      -O|--github-org)
        export GITHUB_ORG=$1 && shift
        ;;
      -R|--github-repo)
        export GITHUB_REPO=$1 && shift
        ;;
      -B|--git-branch)
        export GIT_BRANCH=$1 && shift
        ;;
      -M|--git-commit-msg)
        export GIT_COMMIT_MSG=$1 && shift
        ;;
      -S|--github-ssh)
        export GIT_SSH=$1 && shift
        ;;

      # Other Commands
      -h|--help)
        gitops_rds_db2_database_help
        ;;
      *)
        # unknown option
        echo -e "${COLOR_RED}Usage Error: Unsupported option \"${key}\"${COLOR_RESET}\n"
        gitops_rds_db2_database_help  "Usage Error: Unsupported option \"${key}\" "
        exit 1
        ;;
      esac
  done

  [[ -z "$SM_AWS_ACCESS_KEY_ID" ]] &&  gitops_rds_db2_database_help "SM_AWS_ACCESS_KEY_ID is not set"
  [[ -z "$SM_AWS_SECRET_ACCESS_KEY" ]] && gitops_rds_db2_database_help "SM_AWS_SECRET_ACCESS_KEY is not set"
  [[ -z "$SM_AWS_REGION" ]] && gitops_rds_db2_database_help "SM_AWS_REGION is not set"
  [[ -z "$SECRETS_PATH" ]] && gitops_rds_db2_database_help "SECRETS_PATH is not set"

  [[ -z "$GITOPS_WORKING_DIR" ]] && gitops_rds_db2_database_help "GITOPS_WORKING_DIR is not set"
  [[ -z "$ACCOUNT_ID" ]] && gitops_rds_db2_database_help "ACCOUNT_ID is not set"
  [[ -z "$REGION_ID" ]] && gitops_rds_db2_database_help "REGION_ID is not set"
  [[ -z "$CLUSTER_ID" ]] && gitops_rds_db2_database_help "CLUSTER_ID is not set"
  
  #rds-db2
  [[ -z "$MAS_INSTANCE_ID" ]] && gitops_rds_db2_database_help "MAS_INSTANCE_ID is not set"
  [[ -z "$MAS_APP_ID" ]] && gitops_rds_db2_database_help "MAS_APP_ID is not set"
  
  #MAS
  [[ -z "$MAS_INSTANCE_ID" ]] && gitops_rds_db2_database_help "MAS_INSTANCE_ID is not set"
  [[ -z "$MAS_APP_ID" ]] && gitops_rds_db2_database_help "MAS_APP_ID is not set"
  
  if [[ "$GITHUB_PUSH" == "true" ]]; then
    [[ -z "$GITHUB_HOST" ]] && gitops_rds_db2_database_help "GITHUB_HOST is not set"
    [[ -z "$GITHUB_ORG" ]] && gitops_rds_db2_database_help "GITHUB_ORG is not set"
    [[ -z "$GITHUB_REPO" ]] && gitops_rds_db2_database_help "GITHUB_REPO is not set"
    [[ -z "$GIT_BRANCH" ]] && gitops_rds_db2_database_help "GIT_BRANCH is not set"
  fi

}

function gitops_rds_db2_database() {
  # Take the first parameter off (it will be create-gitops)
  shift
  if [[ $# -gt 0 ]]; then
    gitops_rds_db2_database_noninteractive "$@"
  else
    echo "Not supported yet"
    exit 1
    gitops_rds_db2_database_interactive
  fi

  # catch errors
  set -o pipefail
  trap 'echo "[ERROR] Error occurred at $BASH_SOURCE, line $LINENO, exited with $?"; exit 1' ERR

  mkdir -p ${GITOPS_WORKING_DIR}
  GITOPS_INSTANCE_DIR=${GITOPS_WORKING_DIR}/${GITHUB_REPO}/${ACCOUNT_ID}/${CLUSTER_ID}/${MAS_INSTANCE_ID}
  CONFIGS_FILE="${GITOPS_INSTANCE_DIR}/ibm-dbs-rds-databases.yaml"

  # NOTE: must align with lock branch name used by gitops_deprovision_db2u_database script
  # as both of these scrtipts modify the same file
  GIT_LOCK_BRANCH=$(git_lock_branch_name "gitops-rds-db2-database" "${ACCOUNT_ID}" "${CLUSTER_ID}" "${MAS_INSTANCE_ID}")

  #Defaults
  if [[ -z $REPLICA_DB ]]; then
    export REPLICA_DB="false"
  fi
  if [[ -z $DB2_INSTANCE_NAME ]]; then
    export DB2_INSTANCE_NAME=rds-${MAS_INSTANCE_ID}-${MAS_APP_ID}
  fi
  export DB2_NAMESPACE="rds-${MAS_INSTANCE_ID}"

  if [ -z $GIT_SSH ]; then
    export GIT_SSH="false"
  fi

  echo
  reset_colors
  echo_h2 "Review Settings "

  echo "${TEXT_DIM}"
  echo_h2 "Target" "    "
  echo_reset_dim "Account ID ............................ ${COLOR_MAGENTA}${ACCOUNT_ID}"
  echo_reset_dim "Region ID ............................. ${COLOR_MAGENTA}${REGION_ID}"
  echo_reset_dim "Cluster ID ............................ ${COLOR_MAGENTA}${CLUSTER_ID}"
  echo_reset_dim "Instance Config Directory ............. ${COLOR_MAGENTA}${GITOPS_INSTANCE_DIR}"
  reset_colors

  echo "${TEXT_DIM}"
  if [[ "$GITHUB_PUSH" == "true" ]]; then
    echo_h2 "GitOps Target" "    "
    echo_reset_dim "Automatic Push ........................ ${COLOR_GREEN}Enabled"
    echo_reset_dim "Working Directory ..................... ${COLOR_MAGENTA}${GITOPS_WORKING_DIR}"
    echo_reset_dim "Host .................................. ${COLOR_MAGENTA}${GITHUB_HOST}"
    echo_reset_dim "Organization .......................... ${COLOR_MAGENTA}${GITHUB_ORG}"
    echo_reset_dim "Repository ............................ ${COLOR_MAGENTA}${GITHUB_REPO}"
    echo_reset_dim "Branch ................................ ${COLOR_MAGENTA}${GIT_BRANCH}"
    echo_reset_dim "Lock Branch ........................... ${COLOR_MAGENTA}${GIT_LOCK_BRANCH}"
  else
    echo_h2 "GitOps Target" "    "
    echo_reset_dim "Automatic Push ........................ ${COLOR_RED}Disabled"
    echo_reset_dim "Working Directory ..................... ${COLOR_MAGENTA}${GITOPS_WORKING_DIR}"
  fi
  reset_colors

  echo "${TEXT_DIM}"
  echo_h2 "Secrets Manager" "    "
  echo_reset_dim "Secrets Path ............................ ${COLOR_MAGENTA}${SECRETS_PATH}"
  reset_colors

  echo "${TEXT_DIM}"
  echo_h2 "IBM Maximo Application Suite" "    "
  echo_reset_dim "MAS Instance ID ......................... ${COLOR_MAGENTA}${MAS_INSTANCE_ID}"
  echo_reset_dim "MAS Application ID ...................... ${COLOR_MAGENTA}${MAS_APP_ID}"
  reset_colors

  echo "${TEXT_DIM}"
  echo_h2 "DB2 Cluster Configuration" "    "
  echo_reset_dim "DB2 Namespace ................................. ${COLOR_MAGENTA}${DB2_NAMESPACE}"
  echo_reset_dim "db2-instance-name ............................. ${COLOR_MAGENTA}${DB2_INSTANCE_NAME}"
  echo_reset_dim "mas-app-id  ................................... ${COLOR_MAGENTA}${MAS_APP_ID}"
  echo_reset_dim "replica-db .................................... ${COLOR_MAGENTA}${REPLICA_DB}"
  echo_reset_dim "RDS_DB2_BACKUP_MANAGE........................... ${COLOR_MAGENTA}${RDS_DB2_BACKUP_MANAGE}"
  echo_reset_dim "RDS_DB2_BACKUP_IOT........................... ${COLOR_MAGENTA}${RDS_DB2_BACKUP_IOT}"
  echo_reset_dim "RDS_DB2_BACKUP_FACILITIES...................... ${COLOR_MAGENTA}${RDS_DB2_BACKUP_FACILITIES}"
  echo_reset_dim "db2-instance-registry-yaml .................... ${COLOR_MAGENTA}${DB2_INSTANCE_REGISTRY_YAML}"
  echo_reset_dim "db2-instance-dbm-config-yaml .................. ${COLOR_MAGENTA}${DB2_INSTANCE_DBM_CONFIG_YAML}"
  echo_reset_dim "db2-database-db-config-yaml ................... ${COLOR_MAGENTA}${DB2_DATABASE_DB_CONFIG_YAML}"
  echo_reset_dim "db2-addons-audit-config-yaml .................. ${COLOR_MAGENTA}${DB2_ADDONS_AUDIT_CONFIG_YAML}"
  reset_colors

  AVP_TYPE=aws  # Support for IBM will be added later
  sm_login

  TEMP_DIR=$GITOPS_WORKING_DIR/tmp-db2u-database
  mkdir -p $TEMP_DIR

  # Getting provided db2cluster configs
  # ---------------------------------------------------------------------------
  if [[ -n "$DB2_DATABASE_DB_CONFIG_YAML" ]]; then
    echo
    echo_h2 "Using db2 database db config provided for $MAS_APP_ID at $DB2_DATABASE_DB_CONFIG_YAML"
    export DB2_DATABASE_DB_CONFIG=$(cat ${DB2_DATABASE_DB_CONFIG_YAML})
  fi
  if [[ -n "$DB2_INSTANCE_DBM_CONFIG_YAML" ]]; then
    echo
    echo_h2 "Using db2 instance dm config provided for $MAS_APP_ID at $DB2_INSTANCE_DBM_CONFIG_YAML"
    export DB2_INSTANCE_DBM_CONFIG=$(cat ${DB2_INSTANCE_DBM_CONFIG_YAML})
  fi
  if [[ -n "$DB2_ADDONS_AUDIT_CONFIG_YAML" ]]; then
    echo
    echo_h2 "Using db2 addons audit config provided for $MAS_APP_ID at $DB2_ADDONS_AUDIT_CONFIG_YAML"
    export DB2_ADDONS_AUDIT_CONFIG=$(cat ${DB2_ADDONS_AUDIT_CONFIG_YAML})
  fi
  if [[ -n "$DB2_INSTANCE_REGISTRY_YAML" ]]; then
    echo
    echo_h2 "Using db2 instance registry config provided for $MAS_APP_ID at $DB2_INSTANCE_REGISTRY_YAML"
    export DB2_INSTANCE_REGISTRY=$(cat ${DB2_INSTANCE_REGISTRY_YAML})
  fi

  #secret prefix creation
  CONFIG_SECRETS_PREFIX=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}jdbc${SECRETS_KEY_SEPERATOR}${DB2_INSTANCE_NAME}${SECRETS_KEY_SEPERATOR}config
  CREDENTIALS_SECRETS_PREFIX=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}jdbc${SECRETS_KEY_SEPERATOR}${DB2_INSTANCE_NAME}${SECRETS_KEY_SEPERATOR}credentials

  # db2rds params from aws config secrets
  export HOST=${CONFIG_SECRETS_PREFIX}#db2_endpoint
  export PORT=${CONFIG_SECRETS_PREFIX}#db2_port
  export DBNAME=${CONFIG_SECRETS_PREFIX}#db2_name
  export JDBC_CONNECTION_URL=${CONFIG_SECRETS_PREFIX}#jdbc_connection_url
  export RDS_ADMIN_DB_NAME=${CONFIG_SECRETS_PREFIX}#db2_admin_db_name

  # db2rds params from aws credentials secrets
  export USER_NAME=${CREDENTIALS_SECRETS_PREFIX}#username
  export PASSWORD=${CREDENTIALS_SECRETS_PREFIX}#password

  # db2rds params from saas-env
  export REPLICA_DB=${REPLICA_DB}
  export JDBC_CONNECTION_URL_ADDITIONAL_PARAMS=${JDBC_CONNECTION_URL_ADDITIONAL_PARAMS}


  # Clone github target repo
    # ---------------------------------------------------------------------------
    if [ "$GITHUB_PUSH" == "true" ]; then
      # only create the lock branch if we plan to actually push changes to git
      clone_and_lock_target_git_repo  "${GITHUB_HOST}" "${GITHUB_ORG}" "${GITHUB_REPO}" "${GIT_BRANCH}" "${GITOPS_WORKING_DIR}" "${GIT_SSH}" "${GIT_LOCK_BRANCH}"
    fi
    mkdir -p ${GITOPS_INSTANCE_DIR}
  
    # Generate ArgoApps
    # ---------------------------------------------------------------------------
    echo
    echo_h2 "Generating RDS DB2 Database Configuration"
    echo
  
    # If the file doesn't exist, create a blank one
    if ! [ -f ${CONFIGS_FILE} ]; then
      jinjanate_commmon $CLI_DIR/templates/gitops/appset-configs/cluster/instance/db2-databases/ibm-dbs-rds-databases-common.yaml.j2 $CONFIGS_FILE
    fi
  
    # Remove any existing config with this name
    yq 'del(.ibm_dbs_rds_databases[] | select(.db2_instance_name == "'${DB2_INSTANCE_NAME}'"))' $CONFIGS_FILE > $TEMP_DIR/configs.yaml

    # Create new file
    echo -n "" > ${TEMP_DIR}/newconfig.yaml
    # Render the appropriate template for the config into a new file. For standby database, it will be generated only if it is a replica task and replica is enabled.
    jinjanate_commmon $CLI_DIR/templates/gitops/appset-configs/cluster/instance/db2-databases/ibm-dbs-rds-databases.yaml.j2 | yq '{"ibm_dbs_rds_databases": [] + .}' > ${TEMP_DIR}/newconfig.yaml

    # Merge the two files
    yq eval-all '. as $item ireduce ({}; . *+ $item)' $TEMP_DIR/configs.yaml ${TEMP_DIR}/newconfig.yaml > $CONFIGS_FILE

    # sort the configs by db2_instance_name.
    # This way, we maintain the same ordering of configs in the file (even though we may have deleted and recreated a config if it's an update)
    # This eliminates confusing commits to gitops-envs and allows us to determine if anything has actually changed
    yq -i '.ibm_dbs_rds_databases |= sort_by(.db2_instance_name)' $CONFIGS_FILE
  
    echo_h2 "Updated configuration file (${CONFIGS_FILE})"
    if [ -f ${CONFIGS_FILE} ]; then
      cat $CONFIGS_FILE
    else
      echo "<file was deleted>"
    fi
  
    # Commit and push to github target repo
    # ---------------------------------------------------------------------------
    if [ "$GITHUB_PUSH" == "true" ]; then
      echo
      echo_h2 "Commit and push changes to GitHub repo $GITHUB_ORG $GITHUB_REPO"
      save_and_unlock_target_git_repo "${GITHUB_REPO}" "${GIT_BRANCH}" "${GITOPS_WORKING_DIR}" "${GIT_COMMIT_MSG}" "${GIT_LOCK_BRANCH}" DB2_CONFIG_CHANGED
      remove_git_repo_clone $GITOPS_WORKING_DIR/$GITHUB_REPO
    fi
  
    rm -rf $TEMP_DIR

}

