#!/usr/bin/env bash

function gitops_odh_help() {
  [[ -n "$1" ]] && echo_warning "$1"
  reset_colors
  cat << EOM
Usage:
  mas gitops_odh [options]

Where ${COLOR_YELLOW}specified${TEXT_RESET} each option may also be defined by setting the appropriate environment variable.
When no options are specified on the command line, interactive-mode will be enabled by default.

GitOps Configuration:
  -d, --dir ${COLOR_YELLOW}GITOPS_WORKING_DIR${TEXT_RESET}           Directory for GitOps repository
  -a, --account-id ${COLOR_YELLOW}ACCOUNT_ID${TEXT_RESET}            Account name that the cluster belongs to
  -r, --region-id ${COLOR_YELLOW}CLUSTER_ID${TEXT_RESET}             Region ID
  -c, --cluster-id ${COLOR_YELLOW}CLUSTER_ID${TEXT_RESET}            Cluster ID
  -m, --mas-instance-id ${COLOR_YELLOW}MAS_INSTANCE_ID${TEXT_RESET}  IBM Suite Maximo Application Suite Instance ID

Secrets Manager:
      --secrets-path ${COLOR_YELLOW}SECRETS_PATH${TEXT_RESET}                    Secrets Manager path
      --secrets-key-seperator ${COLOR_YELLOW}SECRETS_KEY_SEPERATOR${TEXT_RESET}  Secrets Manager key seperator string

ODH Configuration:
      --odh-channel
      --odh-catalog-source
      --odh-operator-version
      --odh-namespace
      --pull-secret-name
      --opendatahub-name
      --opendatahub-operator-group
      --opendatahub-installplan
      --opendatahub-channel
      --opendatahub-source
      --opendatahub-source-namespace

Pipeline Configuration:
      --odh-pipeline-name
      --odh-pipeline-namespace
      --odh-pipeline-operator-name
      --odh-pipeline-source
      --odh-pipeline-source-namespace
      --odh-pipeline-channel
      --odh-pipeline-installplan
      --pipeline-catalog-source

Service Mesh:
      --service-mesh-namespace
      --service-mesh-channel
      --service-mesh-catalog-source
      --service-mesh-source-namespace

Serverless:
      --serverless-namespace
      --serverless-channel
      --serverless-operator-name
      --serverless-operator-source
      --serverless-operator-source-namespace

Authorino:
      --authorino-catalog-source

Storage:
      --storage-provider
      --storage-accesskey
      --storage-secretkey
      --storage-host
      --storage-port
      --storage-ssl
      --storage-region
      --pipelines-bucket
      --primary-storage-class

Database:
      --db-host
      --db-port
      --db-user
      --db-database
      --db-secret-name
      --db-secret-value

Automatic GitHub Push:
  -P, --github-push ${COLOR_YELLOW}GITHUB_PUSH${TEXT_RESET}        Enable automatic push to GitHub
  -H, --github-host ${COLOR_YELLOW}GITHUB_HOST${TEXT_RESET}        GitHub Hostname for your GitOps repository
  -O, --github-org  ${COLOR_YELLOW}GITHUB_ORG${TEXT_RESET}         Github org for your GitOps repository
  -R, --github-repo ${COLOR_YELLOW}GITHUB_REPO${TEXT_RESET}        Github repo for your GitOps repository
  -B, --git-branch ${COLOR_YELLOW}GIT_BRANCH${TEXT_RESET}          Git branch to commit to of your GitOps repository
  -M, --git-commit-msg ${COLOR_YELLOW}GIT_COMMIT_MSG${TEXT_RESET}  Git commit message to use when committing to of your GitOps repository
  -S , --github-ssh  ${COLOR_YELLOW}GIT_SSH${TEXT_RESET}           Git ssh key path

Other Commands:
  -h, --help                                      Show this help message
EOM
  [[ -n "$1" ]] && exit 1 || exit 0
}


function gitops_odh_noninteractive() {
  GITOPS_WORKING_DIR=$PWD/working-dir  
  SECRETS_KEY_SEPERATOR="/"
  GIT_COMMIT_MSG="gitops-odh commit"



  export OPENSHIFT_NAMESPACE="${OPENSHIFT_NAMESPACE:-"openshift-operators"}"
  #export ODH_PIPELINE_CHANNEL="${ODH_PIPELINE_CHANNEL:-"latest"}"
  #export ODH_PIPELINE_INSTALLPLAN="${ODH_PIPELINE_INSTALLPLAN:-"Automatic"}"
  export PIPELINE_CATALOG_SOURCE="${PIPELINE_CATALOG_SOURCE:-"redhat-operators"}"
  export SERVICE_MESH_NAMESPACE="${SERVICE_MESH_NAMESPACE:-"openshift-operators"}"
  export SERVICE_MESH_CHANNEL="${SERVICE_MESH_CHANNEL:-"stable"}"
  export SERVICE_MESH_CATALOG_SOURCE="${SERVICE_MESH_CATALOG_SOURCE:-"redhat-operators"}"
  export SERVICE_MESH_SOURCENAMESPACE="${SERVICE_MESH_SOURCENAMESPACE:-"openshift-marketplace"}"
  export OPERATOR_NAME="${OPERATOR_NAME:-"openshift-pipelines-operator-rh"}"
  export SERVERLESS_CHANNEL="${SERVERLESS_CHANNEL:-"stable"}"
  export AUTHORINO_CATALOG_SOURCE="${AUTHORINO_CATALOG_SOURCE:-"community-operators"}"
  export ODH_CHANNEL="${ODH_CHANNEL:-"fast"}"
  export ODH_CATALOG_SOURCE="${ODH_CATALOG_SOURCE:-"community-operators"}"
  export ODH_OPERATOR_VERSION="${ODH_OPERATOR_VERSION:-"opendatahub-operator.v2.19.0"}"
  export ODH_NAMESPACE="${ODH_NAMESPACE:-"opendatahub"}"

  export AIBROKER_NAMESPACE="${AIBROKER_NAMESPACE:-"mas-${MAS_INSTANCE_ID}-aibroker"}"
  # skip pull_secret_name, it is a secret reference

  export ODH_PIPELINE_NAME="${ODH_PIPELINE_NAME:-"openshift-pipelines-operator"}"
  export ODH_PIPELINE_NAMESPACE="${ODH_PIPELINE_NAMESPACE:-"openshift-operators"}"
  export ODH_PIPELINE_OPERATOR_NAME="${ODH_PIPELINE_OPERATOR_NAME:-"openshift-pipelines-operator-rh"}"
  export ODH_PIPELINE_SOURCE="${ODH_PIPELINE_SOURCE:-"redhat_operators"}"
  export ODH_PIPELINE_SOURCE_NAMESPACE="${ODH_PIPELINE_SOURCE_NAMESPACE:-"openshift_marketplace"}"

  export SERVERLESS_NAMESPACE="${SERVERLESS_NAMESPACE:-"openshift-serverless"}"
  export SERVERLESS_OPERATOR_NAME="${SERVERLESS_OPERATOR_NAME:-"serverless-operator"}"
  export SERVERLESS_OPERATOR_SOURCE="${SERVERLESS_OPERATOR_SOURCE:-"redhat-operators"}"
  export SERVERLESS_OPERATOR_SOURCE_NAMESPACE="${SERVERLESS_OPERATOR_SOURCE_NAMESPACE:-"openshift-marketplace"}"

  export OPENDATAHUB_OPERATORGROUP_NAME="${OPENDATAHUB_OPERATORGROUP_NAME:-"opendatahub-operator-group"}"
  #export OPENDATAHUB_NAME="${OPENDATAHUB_NAME:-"opendatahub-operator"}"
  #export OPENDATAHUB_NAMESPACE="${OPENDATAHUB_NAMESPACE:-"opendatahub"}"
  export OPENDATAHUB_INSTALLPLAN_APPROVAL="${OPENDATAHUB_INSTALLPLAN_APPROVAL:-"Manual"}"
  export OPENDATAHUB_CHANNEL="${OPENDATAHUB_CHANNEL:-"fast"}"
  export OPENDATAHUB_SOURCE="${OPENDATAHUB_SOURCE:-"community-operators"}"
  export OPENDATAHUB_SOURCE_NAMESPACE="${OPENDATAHUB_SOURCE_NAMESPACE:-"openshift-marketplace"}"

  export MAS_AIBROKER_STORAGE_PROVIDER="${MAS_AIBROKER_STORAGE_PROVIDER:-"minio"}"
  export MAS_AIBROKER_STORAGE_SSL="${MAS_AIBROKER_STORAGE_SSL:-"true"}"
  export MAS_AIBROKER_STORAGE_REGION="${MAS_AIBROKER_STORAGE_REGION:-"us-east-2"}"
  export PRIMARY_STORAGE_CLASS="${PRIMARY_STORAGE_CLASS:-"nfs-client"}"




  while [[ $# -gt 0 ]]; do
    key="$1"; shift
    case $key in
      -d|--dir) export GITOPS_WORKING_DIR="$1"; shift ;;
      -a|--account-id) export ACCOUNT_ID="$1"; shift ;;
      -c|--cluster-id) export CLUSTER_ID="$1"; shift ;;
      -m|--mas-instance-id) export MAS_INSTANCE_ID="$1"; shift ;;
      # AWS Secrets Manager Configuration
      --sm-aws-secret-region)
        export SM_AWS_REGION=$1
        export REGION_ID=$1
        shift
        ;;
      --sm-aws-access-key)
        export SM_AWS_ACCESS_KEY_ID=$1 && shift
        ;;
      --sm-aws-secret-key)
        export SM_AWS_SECRET_ACCESS_KEY=$1 && shift
        ;;
      --secrets-path)
        export SECRETS_PATH=$1 && shift
        ;;

            # Automatic GitHub Push
      -P|--github-push)
        export GITHUB_PUSH=true
        ;;
      -H|--github-host)
        export GITHUB_HOST=$1 && shift
        ;;
      -O|--github-org)
        export GITHUB_ORG=$1 && shift
        ;;
      -R|--github-repo)
        export GITHUB_REPO=$1 && shift
        ;;
      -S|--github-ssh)
        export GIT_SSH=$1 && shift
        ;;
      -B|--git-branch)
        export GIT_BRANCH=$1 && shift
        ;;
      -M|--git-commit-msg)
        export GIT_COMMIT_MSG=$1 && shift
        ;;


      --odh-channel)
        export ODH_CHANNEL=$1 && shift
        ;;
      --odh-catalog-source)
        export ODH_CATALOG_SOURCE=$1 && shift
        ;;
      --odh-operator-version)
        export ODH_OPERATOR_VERSION=$1 && shift
        ;;
      --odh-namespace)
        export ODH_NAMESPACE=$1 && shift
        ;;
      --openshift-namespace)
        export OPENSHIFT_NAMESPACE=$1 && shift
        ;;
      --pull-secret-name)
        export PULL_SECRET_NAME=$1 && shift
        ;;

      --opendatahub-name)
        export OPENDATAHUB_NAME=$1 && shift
        ;;
      --opendatahub-operator-group)
        export OPENDATAHUB_OPERATORGROUP_NAME=$1 && shift
        ;;
      --opendatahub-installplan)
        export OPENDATAHUB_INSTALLPLAN_APPROVAL=$1 && shift
        ;;
      --opendatahub-channel)
        export OPENDATAHUB_CHANNEL=$1 && shift
        ;;
      --opendatahub-source)
        export OPENDATAHUB_SOURCE=$1 && shift
        ;;
      --opendatahub-namespace)
        export OPENDATAHUB_NAMESPACE=$1 && shift
        ;;
      --opendatahub-source-namespace)
        export OPENDATAHUB_SOURCE_NAMESPACE=$1 && shift
        ;;
      --odh-pipeline-name)
        export ODH_PIPELINE_NAME=$1 && shift
        ;;
      --odh-pipeline-namespace)
        export ODH_PIPELINE_NAMESPACE=$1 && shift
        ;;
      --odh-pipeline-operator-name)
        export ODH_PIPELINE_OPERATOR_NAME=$1 && shift
        ;;
      --odh-pipeline-source)
        export ODH_PIPELINE_SOURCE=$1 && shift
        ;;
      --odh-pipeline-source-namespace)
        export ODH_PIPELINE_SOURCE_NAMESPACE=$1 && shift
        ;;
      --odh-pipeline-channel)
        export ODH_PIPELINE_CHANNEL=$1 && shift
        ;;
      --odh-pipeline-installplan)
        export ODH_PIPELINE_INSTALLPLAN=$1 && shift
        ;;
      --pipeline-catalog-source)
        export PIPELINE_CATALOG_SOURCE=$1 && shift
        ;;

      --service-mesh-namespace)
        export SERVICE_MESH_NAMESPACE=$1 && shift
        ;;
      --service-mesh-channel)
        export SERVICE_MESH_CHANNEL=$1 && shift
        ;;
      --service-mesh-catalog-source)
        export SERVICE_MESH_CATALOG_SOURCE=$1 && shift
        ;;
      --service-mesh-source-namespace)
        export SERVICE_MESH_SOURCE_NAMESPACE=$1 && shift
        ;;

      --serverless-namespace)
        export SERVERLESS_NAMESPACE=$1 && shift
        ;;
      --serverless-channel)
        export SERVERLESS_CHANNEL=$1 && shift
        ;;
      --serverless-operator-name)
        export SERVERLESS_OPERATOR_NAME=$1 && shift
        ;;
      --serverless-operator-source)
        export SERVERLESS_OPERATOR_SOURCE=$1 && shift
        ;;
      --serverless-operator-source-namespace)
        export SERVERLESS_OPERATOR_SOURCE_NAMESPACE=$1 && shift
        ;;

      --authorino-catalog-source)
        export AUTHORINO_CATALOG_SOURCE=$1 && shift
        ;;

      --aibroker-namespace)
        export AIBROKER_NAMESPACE=$1 && shift
        ;;

      --storage-provider)
        export MAS_AIBROKER_STORAGE_PROVIDER=$1 && shift
        ;;
      --storage-accesskey)
        export MAS_AIBROKER_STORAGE_ACCESSKEY=$1 && shift
        ;;
      --storage-secretkey)
        export MAS_AIBROKER_STORAGE_SECRETKEY=$1 && shift
        ;;
      --storage-host)
        export MAS_AIBROKER_STORAGE_HOST=$1 && shift
        ;;
      --storage-port)
        export MAS_AIBROKER_STORAGE_PORT=$1 && shift
        ;;
      --storage-ssl)
        export MAS_AIBROKER_STORAGE_SSL=$1 && shift
        ;;
      --storage-region)
        export MAS_AIBROKER_STORAGE_REGION=$1 && shift
        ;;
      --storage-pipelines-bucket)
        export MAS_AIBROKER_STORAGE_PIPELINES_BUCKET=$1 && shift
        ;;

      --db-host)
        export MAS_AIBROKER_DB_HOST=$1 && shift
        ;;
      --db-port)
        export MAS_AIBROKER_DB_PORT=$1 && shift
        ;;
      --db-user)
        export MAS_AIBROKER_DB_USER=$1 && shift
        ;;
      --db-database)
        export MAS_AIBROKER_DB_DATABASE=$1 && shift
        ;;
      --db-secret-name)
        export MAS_AIBROKER_DB_SECRET_NAME=$1 && shift
        ;;
      --db-secret-value)
        export MAS_AIBROKER_DB_SECRET_VALUE=$1 && shift
        ;;

      --primary-storage-class)
        export PRIMARY_STORAGE_CLASS=$1 && shift
        ;;

      --operator-name)
        export OPERATOR_NAME=$1 && shift
        ;;

      # GitHub
      -P|--github-push) export GITHUB_PUSH=true ;;
      -H|--github-host) export GITHUB_HOST="$1"; shift ;;
      -O|--github-org) export GITHUB_ORG="$1"; shift ;;
      -R|--github-repo) export GITHUB_REPO="$1"; shift ;;
      -B|--git-branch) export GIT_BRANCH="$1"; shift ;;
      -M|--git-commit-msg) export GIT_COMMIT_MSG="$1"; shift ;;
      -S|--github-ssh) export GIT_SSH="$1"; shift ;;

      -h|--help) gitops_odh_help ;;
      *) gitops_odh_help "Unknown option $key" ;;
    esac
  done

  [[ -z "$GITOPS_WORKING_DIR" ]] && gitops_odh_help "Missing GITOPS_WORKING_DIR"
  [[ -z "$ACCOUNT_ID" ]] && gitops_odh_help "Missing ACCOUNT_ID"
  [[ -z "$CLUSTER_ID" ]] && gitops_odh_help "Missing CLUSTER_ID"
  [[ -z "$MAS_INSTANCE_ID" ]] && gitops_odh_help "Missing MAS_INSTANCE_ID"

  if [[ "$GITHUB_PUSH" == "true" ]]; then
    [[ -z "$GITHUB_HOST" ]] && gitops_odh_help "GITHUB_HOST is not set"
    [[ -z "$GITHUB_ORG" ]] && gitops_odh_help "GITHUB_ORG is not set"
    [[ -z "$GITHUB_REPO" ]] && gitops_odh_help "GITHUB_REPO is not set"
    [[ -z "$GIT_BRANCH" ]] && gitops_odh_help "GIT_BRANCH is not set"
  fi
  #odh variables
  [[ -z "$ODH_PIPELINE_CHANNEL" ]] && gitops_odh_help "ODH_PIPELINE_CHANNEL is not set. Please provide the ODH PIPELINE CHANNEL using --odh-pipeline-channel."
  [[ -z "$ODH_PIPELINE_INSTALLPLAN" ]] && gitops_odh_help "ODH_PIPELINE_INSTALLPLAN is not set. Please provide the OODH_PIPELINE_INSTALLPLAN using --odh-pipeline-installplan."
  [[ -z "$OPENDATAHUB_NAME" ]] && gitops_odh_help "OPENDATAHUB_NAME is not set. Please provide the OPENDATAHUB NAME using --opendatahub-name."
  [[ -z "$OPENDATAHUB_NAMESPACE" ]] && gitops_odh_help "OPENDATAHUB_NAMESPACE is not set. Please provide the OPENDATAHUB NAMESPACE using --opendatahub-namespace."

}

function gitops_odh() {
  # Remove the subcommand (e.g., "create-gitops")
  shift
  if [[ $# -gt 0 ]]; then
    gitops_odh_noninteractive "$@"
  else
    echo "Interactive mode not implemented."
    exit 1
  fi

  # Error trap
  set -o pipefail
  trap 'echo "[ERROR] Error occurred at $BASH_SOURCE, line $LINENO, exited with $?"; exit 1' ERR

  # Prepare directories
  rm -rf "$GITOPS_WORKING_DIR"
  mkdir -p "${GITOPS_WORKING_DIR}"
  #GITOPS_CLUSTER_DIR="${GITOPS_WORKING_DIR}/${GITHUB_REPO}/${CLUSTER_ID}"
  GITOPS_CLUSTER_DIR=${GITOPS_WORKING_DIR}/${GITHUB_REPO}/${ACCOUNT_ID}/${CLUSTER_ID}/${MAS_INSTANCE_ID}
  

  echo
  echo_h2 "Review Settings"
  echo "${TEXT_DIM}"
  echo_h2 "Target"
  echo_reset_dim "Account ID ............................ ${COLOR_MAGENTA}${ACCOUNT_ID}"
  echo_reset_dim "Cluster ID ............................ ${COLOR_MAGENTA}${CLUSTER_ID}"
  echo_reset_dim "MAS Instance ID ....................... ${COLOR_MAGENTA}${MAS_INSTANCE_ID}"

  echo_reset_dim "Secrets Path .......................... ${COLOR_MAGENTA}${SECRETS_PATH}"
  reset_colors

  CURRENT_DIR=$PWD
  # TEMP_DIR=$CURRENT_DIR/aibroker01
  # mkdir -p $TEMP_DIR
  # echo_reset_dim "Temp Directory ........................ ${COLOR_MAGENTA}${TEMP_DIR}"
  
  AVP_TYPE=aws
  sm_login

  # Set up secret key and fetch secret
  export SECRET_ACCOUNT_PATH="${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}"
  export ODH_SECRET="${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}minio"


  export SECRET_KEY_IMAGE_PULL_SECRET_B64="${SECRET_ACCOUNT_PATH}ibm_entitlement#image_pull_secret_b64"

  # MinIO
  export SECRET_KEY_SM_MINIO_ACCESSKEY="${SECRET_ACCOUNT_PATH}minio#sm_minio_accesskey"
  export SECRET_KEY_SM_MINIO_SECRETKEY="${SECRET_ACCOUNT_PATH}minio#sm_minio_secretkey"
  export SECRET_KEY_SM_MINIO_HOST="${SECRET_ACCOUNT_PATH}minio#sm_minio_host"
  export SECRET_KEY_SM_MINIO_PORT="${SECRET_ACCOUNT_PATH}minio#sm_minio_port"
  export SECRET_KEY_SM_MINIO_BUCKET_DEFAULT="${SECRET_ACCOUNT_PATH}minio#sm_minio_bucket_default"

  # MariaDB
  export SECRET_KEY_SM_MARIADB_HOST="${SECRET_ACCOUNT_PATH}mariadb#sm_mariadb_host"
  export SECRET_KEY_SM_MARIADB_PORT="${SECRET_ACCOUNT_PATH}mariadb#sm_mariadb_port"
  export SECRET_KEY_SM_MARIADB_USER="${SECRET_ACCOUNT_PATH}mariadb#sm_mariadb_user"
  export SECRET_KEY_SM_MARIADB_DATABASE="${SECRET_ACCOUNT_PATH}mariadb#sm_mariadb_database"
  export SECRET_KEY_SM_MARIADB_SECRET_NAME="${SECRET_ACCOUNT_PATH}mariadb#sm_mariadb_secret_name"
  export SECRET_KEY_SM_MARIADB_SECRET_VALUE="${SECRET_ACCOUNT_PATH}mariadb#sm_mariadb_secret_value"



  export ODH_SECRET_FILE="$GITOPS_WORKING_DIR/odh-secret.json"
  if [ -z $GIT_SSH ]; then
    export GIT_SSH=false
  fi

  sm_verify_secret_exists ${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}minio "sm_minio_bucket_templates,sm_minio_bucket_tenants,sm_minio_bucket_pipelines,sm_minio_bucket_default"
  sm_verify_secret_exists ${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}mariadb "sm_mariadb_host,sm_mariadb_database"
  sm_get_secret_file "$ODH_SECRET" "$ODH_SECRET_FILE"
  #################################################################
   export MARIA_SECRET="${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}mariadb"
   export MARIA_SECRET_FILE="$GITOPS_WORKING_DIR/mariadb-secret.json"
   sm_get_secret_file "$MARIA_SECRET" "$MARIA_SECRET_FILE"
  ######################################################################
   #######################Checking condition Storage_provider#######################################
   #mas_aibroker_storage_provider
  ######################################################################
  # Reuse existing secret values if present
  TEMP_MINIO_ACCESS_KEY=$(jq -r .sm_minio_accesskey "$ODH_SECRET_FILE")
  if [[ -n ${TEMP_MINIO_ACCESS_KEY} ]]; then
    export MINIO_ACCESS_KEY="${TEMP_MINIO_ACCESS_KEY}"
    echo "gitops_odh : MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:0:3}<snip> is available in the secret, using existing value."
  fi

  TEMP_MINIO_SECRET_KEY=$(jq -r .sm_minio_secretkey "$ODH_SECRET_FILE")
  if [[ -n ${TEMP_MINIO_SECRET_KEY} ]]; then
    export MINIO_SECRET_KEY="${TEMP_MINIO_SECRET_KEY}"
    echo "gitops_odh : MINIO_SECRET_KEY=${MINIO_SECRET_KEY:0:3}<snip> is available in the secret, using existing value."
  fi

  TEMP_MARIADB_USER=$(jq -r .sm_mariadb_user "$ODH_SECRET_FILE")
  if [[ -n ${TEMP_MARIADB_USER} ]]; then
    export MARIADB_USER="${TEMP_MARIADB_USER}"
    echo "gitops_odh : MARIADB_USER=${MARIADB_USER} is available in the secret, using existing value."
  fi

  TEMP_MARIADB_SECRET_VALUE=$(jq -r .sm_mariadb_secret_value "$ODH_SECRET_FILE")
  if [[ -n ${TEMP_MARIADB_SECRET_VALUE} ]]; then
    export MARIADB_SECRET_VALUE="${TEMP_MARIADB_SECRET_VALUE}"
    echo "gitops_odh : MARIADB_SECRET_VALUE=${MARIADB_SECRET_VALUE:0:4}<snip> is available in the secret, using existing value."
  fi


  # Extract and export secrets
  export MINIO_ACCESS_KEY=$(jq -r .sm_minio_accesskey "$ODH_SECRET_FILE")
  export MINIO_SECRET_KEY=$(jq -r .sm_minio_secretkey "$ODH_SECRET_FILE")
  export MINIO_HOST=$(jq -r .sm_minio_host "$ODH_SECRET_FILE")
  export MINIO_PORT=$(jq -r .sm_minio_port "$ODH_SECRET_FILE")
  export MINIO_BUCKET=$(jq -r .sm_minio_bucket_default "$ODH_SECRET_FILE")

  export MARIADB_HOST=$(jq -r .sm_mariadb_host "$MARIA_SECRET_FILE")
  export MARIADB_PORT=$(jq -r .sm_mariadb_port "$MARIA_SECRET_FILE")
  export MARIADB_USER=$(jq -r .sm_mariadb_user "$MARIA_SECRET_FILE")
  export MARIADB_DATABASE=$(jq -r .sm_mariadb_database "$MARIA_SECRET_FILE")
  export MARIADB_SECRET_NAME=$(jq -r .sm_mariadb_secret_name "$$MARIA_SECRET_FILE")
  export MARIADB_SECRET_VALUE=$(jq -r .sm_mariadb_secret_value "$MARIA_SECRET_FILE")

  echo_h2 "ODH Secret Summary"
  echo_reset_dim "MINIO_HOST ............................. ${COLOR_MAGENTA}${MINIO_HOST}"
  echo_reset_dim "MINIO_BUCKET ........................... ${COLOR_MAGENTA}${MINIO_BUCKET}"
  echo_reset_dim "MARIADB_HOST ........................... ${COLOR_MAGENTA}${MARIADB_HOST}"
  echo_reset_dim "MARIADB_DATABASE ....................... ${COLOR_MAGENTA}${MARIADB_DATABASE}"
  reset_colors


  # Clone github target repo
  # ---------------------------------------------------------------------------
  if [ "$GITHUB_PUSH" == "true" ]; then
    echo "GITOPS_WORKING_DIR  ${GITOPS_WORKING_DIR}"
    echo "GITOPS_CLUSTER_DIR  ${GITOPS_CLUSTER_DIR}"
    echo_h2 "Cloning GitHub repo $GITHUB_ORG $GITHUB_REPO"
    clone_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_WORKING_DIR $GIT_SSH
  fi

  mkdir -p ${GITOPS_CLUSTER_DIR}
  # Render YAML
  echo_h2 "Generating OpenDataHub GitOps YAML"
  echo "${GITOPS_CLUSTER_DIR}"
  echo "Output: ${GITOPS_CLUSTER_DIR}/ibm-mas-odh-install.yaml"

  jinjanate_commmon $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-mas-odh-install.yaml.j2 ${GITOPS_CLUSTER_DIR}/ibm-mas-odh-install.yaml

  # Collect info block for secret update
  # yq eval '.' "${GITOPS_CLUSTER_DIR}/ibm-mas-odh-install.yaml" > "${GITOPS_CLUSTER_DIR}/odh-info.yaml"
  # UNESCAPED_INFO="$(cat ${GITOPS_CLUSTER_DIR}/odh-info.yaml)"
  # ESCAPED_INFO="${UNESCAPED_INFO//\"/\\\"}"

  TAGS="[{\"Key\": \"source\", \"Value\": \"gitops_odh\"}, {\"Key\": \"account\", \"Value\": \"${ACCOUNT_ID}\"}, {\"Key\": \"cluster\", \"Value\": \"${CLUSTER_ID}\"}]"

  # sm_update_secret "$ODH_SECRET" \
  #   "{\"minio_access_key\": \"${MINIO_ACCESS_KEY}\", \"minio_secret_key\": \"${MINIO_SECRET_KEY}\", \"mariadb_user\": \"${MARIADB_USER}\"}" \
  #   "$TAGS"
  #rm -rf "$TEMP_DIR"
  # GitHub push
  if [[ "$GITHUB_PUSH" == "true" ]]; then
    echo_h2 "Pushing changes to GitHub"
    echo "Github push" "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$GIT_BRANCH" "Working: " "${GITOPS_WORKING_DIR}/${GITHUB_REPO}" " Commit :" "$GIT_COMMIT_MSG"
    save_to_target_git_repo "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$GIT_BRANCH" "${GITOPS_WORKING_DIR}/${GITHUB_REPO}" "$GIT_COMMIT_MSG"
    remove_git_repo_clone "${GITOPS_WORKING_DIR}/${GITHUB_REPO}"
  fi

  # rm -rf "$TEMP_DIR"
  rm -rf "$ODH_SECRET_FILE"
  rm -rf "$MARIA_SECRET_FILE"
  echo_h2 "ODH GitOps completed."
}
