#!/usr/bin/env bash

function gitops_iac_help() {
  [[ -n "$1" ]] && echo_warning "$1"
  reset_colors
  cat << EOM


Usage:
  mas gitops-iac-efs [options]
Where ${COLOR_YELLOW}specified${TEXT_RESET} each option may also be defined by setting the appropriate environment variable.
When no options are specified on the command line, interactive-mode will be enabled by default.

Basic Configuration:
  -a, --account-id ${COLOR_YELLOW}ACCOUNT_ID${TEXT_RESET}                    Account name that the cluster belongs to
  -c, --cluster-id ${COLOR_YELLOW}CLUSTER_ID${TEXT_RESET}                    Cluster ID
  -m, --mas-instance-id ${COLOR_YELLOW}MAS_INSTANCE_ID${TEXT_RESET}          MAS Instance ID
  -r, --region-id ${COLOR_YELLOW}REGION_ID${TEXT_RESET}                      Region ID
  --region-name ${COLOR_YELLOW}REGION_NAME${TEXT_RESET}                      Region Name


Secrets Manager:
      --secrets-path ${COLOR_YELLOW}SECRETS_PATH${TEXT_RESET}                Secrets Manager path
      --secrets-key-seperator ${COLOR_YELLOW}SECRETS_KEY_SEPERATOR${TEXT_RESET}


Target Cluster (Optional):
      --cluster-url ${COLOR_YELLOW}CLUSTER_URL${TEXT_RESET}                  Set to target a remote Kubernetes cluster (defaults to 'https://kubernetes.default.svc')

Automatic GitHub Push (Optional):
  -P, --github-push ${COLOR_YELLOW}GITHUB_PUSH${TEXT_RESET}                  Enable automatic push to GitHub
  -H, --github-host ${COLOR_YELLOW}GITHUB_HOST${TEXT_RESET}                  GitHub Hostname for your GitOps repository
  -O, --github-org ${COLOR_YELLOW}GITHUB_ORG${TEXT_RESET}                    Github org for your GitOps repository
  -R, --github-repo ${COLOR_YELLOW}GITHUB_REPO${TEXT_RESET}                  Github repo for your GitOps repository
  -S, --github-ssh ${COLOR_YELLOW}GIT_SSH${TEXT_RESET}                       Git ssh key path
  -B, --git-branch ${COLOR_YELLOW}GIT_BRANCH${TEXT_RESET}                    Git branch to commit to of your GitOps repository
  -M, --git-commit-msg ${COLOR_YELLOW}GIT_COMMIT_MSG${TEXT_RESET}            Git commit message to use when committing to of your GitOps repository

Other Commands:
  -h, --help                                      Show this help message
EOM
  [[ -n "$1" ]] && exit 1 || exit 0
}

export GIT_COMMIT_MSG=${GIT_COMMIT_MSG:-"iac update"}

function gitops_iac_noninteractive() {
  GITOPS_WORKING_DIR=$PWD/working-dir
  SECRETS_KEY_SEPERATOR="/"

  # Set default values
  export CLUSTER_URL=${CLUSTER_URL:-"https://kubernetes.default.svc"}
  
  while [[ $# -gt 0 ]]
  do
    key="$1"
    shift
    case $key in
      # GitOps Configuration
      -d|--dir)
        export GITOPS_WORKING_DIR=$1 && shift
        ;;
      -a|--account-id)
        export ACCOUNT_ID=$1 && shift
        ;;
      -c|--cluster-id)
        export CLUSTER_ID=$1 && shift
        export CLUSTER_NAME=$1  # For backward compatibility
        ;;
      
      -m|--mas-instance-id)
        export MAS_INSTANCE_ID=$1 && shift
        ;;
      
      -r|--region-id)
        export REGION_ID=$1 && shift
        ;;

      # AWS Secrets Manager Configuration
      --sm-aws-secret-region)
        export SM_AWS_REGION=$1
        shift
        ;;
     --region-name)
        export REGION_NAME=$1 && shift
        ;;
      --sm-aws-access-key)
        export SM_AWS_ACCESS_KEY_ID=$1 && shift
        ;;
      --sm-aws-secret-key)
        export SM_AWS_SECRET_ACCESS_KEY=$1 && shift
        ;;
      --secrets-path)
        export SECRETS_PATH=$1 && shift
        ;;

      # EFS Configuration
      --is_efs)
        export IS_EFS=$1 && shift
        ;;
      --efs-source)
        export EFS_SOURCE=$1 && shift
        ;;
      --efs_manage_db2_performance_mode)
        export EFS_MANAGE_DB2_PERFORMANCE_MODE=$1 && shift
        ;;

      --efs_manage_db2_mount_count)
        export EFS_MANAGE_DB2_MOUNT_COUNT=$1 && shift
        ;;

      --efs_manage_db2_throughput_mode)
        export EFS_MANAGE_DB2_THROUGHPUT_MODE=$1 && shift
        ;;

      --efs_manage_main_performance_mode)
        export EFS_MANAGE_MAIN_PERFORMANCE_MODE=$1 && shift
        ;;

      --efs_manage_main_mount_count)
        export EFS_MANAGE_MAIN_MOUNT_COUNT=$1 && shift
        ;;

      --efs_manage_main_throughput_mode)
        export EFS_MANAGE_MAIN_THROUGHPUT_MODE=$1 && shift
        ;;

      --efs_iot_db2_performance_mode)
        export EFS_IOT_DB2_PERFORMANCE_MODE=$1 && shift
        ;;

      --efs_iot_db2_mount_count)
        export EFS_IOT_DB2_MOUNT_COUNT=$1 && shift
        ;;

      --efs_iot_db2_throughput_mode)
        export EFS_IOT_DB2_THROUGHPUT_MODE=$1 && shift
        ;;

      --efs_facilities_db2_performance_mode)
        export EFS_FACILITIES_DB2_PERFORMANCE_MODE=$1 && shift
        ;;

      --efs_facilities_db2_mount_count)
        export EFS_FACILITIES_DB2_MOUNT_COUNT=$1 && shift
        ;;

      --efs_facilities_db2_throughput_mode)
        export EFS_FACILITIES_DB2_THROUGHPUT_MODE=$1 && shift
        ;;

      --efs_facilities_main_performance_mode)
        export EFS_FACILITIES_MAIN_PERFORMANCE_MODE=$1 && shift
        ;;

      --efs_facilities_main_mount_count)
        export EFS_FACILITIES_MAIN_MOUNT_COUNT=$1 && shift
        ;;

      --efs_facilities_main_throughput_mode)
        export EFS_FACILITIES_MAIN_THROUGHPUT_MODE=$1 && shift
        ;;

      --efs_visualinspection_main_performance_mode)
        export EFS_VISUALINSPECTION_MAIN_PERFORMANCE_MODE=$1 && shift
        ;;

      --efs_visualinspection_main_mount_count)
        export EFS_VISUALINSPECTION_MAIN_MOUNT_COUNT=$1 && shift
        ;;

      --efs_visualinspection_main_throughput_mode)
        export EFS_VISUALINSPECTION_MAIN_THROUGHPUT_MODE=$1 && shift
        ;;
      # Target Cluster (Optional)
      --cluster-url)
        export CLUSTER_URL=$1 && shift
        ;;

      # Automatic GitHub Push
      -P|--github-push)
        export GITHUB_PUSH=true
        ;;
      -H|--github-host)
        export GITHUB_HOST=$1 && shift
        ;;
      -O|--github-org)
        export GITHUB_ORG=$1 && shift
        ;;
      -R|--github-repo)
        export GITHUB_REPO=$1 && shift
        ;;
      -S|--github-ssh)
        export GIT_SSH=$1 && shift
        ;;
      -B|--git-branch)
        export GIT_BRANCH=$1 && shift
        ;;
      -M|--git-commit-msg)
        export GIT_COMMIT_MSG=$1 && shift
        ;;

      # Other Commands
      -h|--help)
        gitops_iac_help
        ;;
      *)
        # unknown option
        echo -e "${COLOR_RED}Usage Error: Unsupported option \"${key}\"${COLOR_RESET}\n"
        gitops_iac_help "Usage Error: Unsupported option \"${key}\" "
        exit 1
        ;;
      esac
  done

  # Validate required parameters
  [[ -z "$GITOPS_WORKING_DIR" ]] && gitops_iac_help "GITOPS_WORKING_DIR is not set"
  [[ -z "$ACCOUNT_ID" ]] && gitops_iac_help "ACCOUNT_ID is not set"
  [[ -z "$CLUSTER_ID" ]] && gitops_iac_help "CLUSTER_ID is not set"
  [[ -z "$MAS_INSTANCE_ID" ]] && gitops_iac_help "MAS_INSTANCE_ID is not set"
  [[ -z "$REGION_ID" && -z "$SM_AWS_REGION" ]] && gitops_iac_help "REGION_ID or SM_AWS_REGION is not set"
  [[ -z "$REGION_NAME" ]] && gitops_iac_help "REGION_NAME is not set"
  [[ -z "$CLUSTER_URL" ]] && gitops_iac_help "CLUSTER_URL is not set"

  if [[ "$GITHUB_PUSH" == "true" ]]; then
    [[ -z "$GITHUB_HOST" ]] && gitops_iac_help "GITHUB_HOST is not set"
    [[ -z "$GITHUB_ORG" ]] && gitops_iac_help "GITHUB_ORG is not set"
    [[ -z "$GITHUB_REPO" ]] && gitops_iac_help "GITHUB_REPO is not set"
    [[ -z "$GIT_BRANCH" ]] && gitops_iac_help "GIT_BRANCH is not set"
  fi

}

function gitops_iac() {
  # Take the first parameter off (it will be create-gitops)
  shift
  if [[ $# -gt 0 ]]; then
    gitops_iac_noninteractive "$@"
  else
    echo "Not supported yet"
    exit 1
    gitops_iac_efs_interactive
  fi

  # catch errors
  set -o pipefail
  trap 'echo "[ERROR] Error occurred at $BASH_SOURCE, line $LINENO, exited with $?"; exit 1' ERR

  mkdir -p ${GITOPS_WORKING_DIR}
  GITOPS_CLUSTER_DIR=${GITOPS_WORKING_DIR}/${GITHUB_REPO}/${REGION_NAME}/instances/${MAS_INSTANCE_ID}

  echo
  reset_colors
  echo_h2 "Review Settings"

  echo "${TEXT_DIM}"
  echo_h2 "Target" "    "
  echo_reset_dim "Account ID ..................... ${COLOR_MAGENTA}${ACCOUNT_ID}"
  echo_reset_dim "Region Name .................... ${COLOR_MAGENTA}${REGION_NAME}"
  echo_reset_dim "Cluster ID ..................... ${COLOR_MAGENTA}${CLUSTER_ID}"
  echo_reset_dim "MAS Instance ID ................ ${COLOR_MAGENTA}${MAS_INSTANCE_ID}"
  echo_reset_dim "Cluster URL .................... ${COLOR_MAGENTA}${CLUSTER_URL}"
  echo_reset_dim "Cluster Config Directory ....... ${COLOR_MAGENTA}${GITOPS_CLUSTER_DIR}"
  reset_colors

  echo "${TEXT_DIM}"
  if [[ "$GITHUB_PUSH" == "true" ]]; then
    echo_h2 "GitOps Target" "    "
    echo_reset_dim "Automatic Push ................. ${COLOR_GREEN}Enabled"
    echo_reset_dim "Working Directory .............. ${COLOR_MAGENTA}${GITOPS_WORKING_DIR}"
    echo_reset_dim "Host ........................... ${COLOR_MAGENTA}${GITHUB_HOST}"
    echo_reset_dim "Organization ................... ${COLOR_MAGENTA}${GITHUB_ORG}"
    echo_reset_dim "Repository ..................... ${COLOR_MAGENTA}${GITHUB_REPO}"
    echo_reset_dim "Branch ......................... ${COLOR_MAGENTA}${GIT_BRANCH}"
  else
    echo_h2 "GitOps Target" "    "
    echo_reset_dim "Automatic Push ................. ${COLOR_RED}Disabled"
    echo_reset_dim "Working Directory .............. ${COLOR_MAGENTA}${GITOPS_WORKING_DIR}"
  fi
  reset_colors
   echo_reset_dim "IS EFS  ......................... ${COLOR_MAGENTA}${IS_EFS}"
  if [[ "$IS_EFS"  == "true" ]]; then
    echo "${TEXT_DIM}"
    echo_h2 "EFS Configuration" "    "
    echo_reset_dim "SOURCE ......................... ${COLOR_MAGENTA}${EFS_SOURCE}"
    echo_reset_dim "CREATION TOKEN ................. ${COLOR_MAGENTA}${EFS_CREATION_TOKEN}"
    echo_reset_dim "Performance Mode ............... ${COLOR_MAGENTA}${EFS_PERFORMANCE_MODE}"
    echo_reset_dim "Mount Count .................... ${COLOR_MAGENTA}${EFS_MOUNT_COUNT}"
    echo_reset_dim "Lifecycle Policy (IA) .......... ${COLOR_MAGENTA}${EFS_LIFECYCLE_POLICY_TRANSITION_TO_IA}"
    echo_reset_dim "Lifecycle Policy (Primary) ..... ${COLOR_MAGENTA}${EFS_LIFECYCLE_POLICY_TRANSITION_TO_PRIMARY_STORAGE_CLASS}"
    echo_reset_dim "Throughput Mode ................ ${COLOR_MAGENTA}${EFS_THROUGHPUT_MODE}"
    echo_reset_dim "Encrypted ...................... ${COLOR_MAGENTA}${EFS_ENCRYPTED}"
    reset_colors
  fi

  if [ -z $GIT_SSH ]; then
    export GIT_SSH=false
  fi

  # Clone github target repo
  # ---------------------------------------------------------------------------
  if [ "$GITHUB_PUSH" == "true" ]; then
    echo
    echo "GITOPS_WORKING_DIR  ${GITOPS_WORKING_DIR}"
    echo "GITOPS_CLUSTER_DIR  ${GITOPS_CLUSTER_DIR}"
    echo_h2 "Cloning GitHub repo $GITHUB_ORG $GITHUB_REPO"
    clone_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_WORKING_DIR $GIT_SSH
  fi
  mkdir -p ${GITOPS_CLUSTER_DIR}


  # ---------------------------------------------------------------------------
  echo "Checking and creating common files if not already present"
  create_common_files ${GITOPS_CLUSTER_DIR}


  # ---------------------------------------------------------------------------
  #  creating files for efs.tf only
  if [[ "$IS_EFS"  == "true" ]]; then
    echo
    echo_h2 "Generating IAC/EFS Configuration"
    echo "- IAC Base Config"

    echo "generating path for CLUSTER_CIDR_WORKLOAD_EXTERNAL"

    #Creating file path for extracting parameter value from cluster & vpc
    CLUSTER_CIDR_WORKLOAD_CLUSTER_PATH=${GITOPS_WORKING_DIR}/${GITHUB_REPO}/${REGION_NAME}/clusters/${CLUSTER_ID}
    MAIN_FILE_PATH=$CLUSTER_CIDR_WORKLOAD_CLUSTER_PATH/main.tf
    TERRAFORMTF_FILE_PATH=$CLUSTER_CIDR_WORKLOAD_CLUSTER_PATH/terraform.tfvars
    # VPC_CIDR_PATH=${GITOPS_WORKING_DIR}/${GITHUB_REPO}/${REGION_NAME}/vpcs/${VPC_NAME_VALUE}/main.tf

    #Creating value path for extracting parameter value from .tf file
    VPC_ID_DOT_PATH="vpc_id"
    VPC_NAME_DOT_PATH="vpc_name"
    CLUSTER_CIDR_WORKLOAD_EXTERNAL_DOT_PATH="locals.cluster.cidrs.workload_external"
    VPC_CIDR_WORKLOAD_INTERNAL_DOT_PATH="locals.cluster.cidrs.workload_internal"
    EFS_CIDR_REF_NAME=${CLUSTER_ID}-${MAS_INSTANCE_ID}-efs
    VPC_CIDR_WORKLOAD_DOT_PATH="locals.workloads[\"${EFS_CIDR_REF_NAME}\"].cidrs"

    #Extracting values from .tf file
    export CLUSTER_CIDR_WORKLOAD_EXTERNAL=$(get_tf_value "${MAIN_FILE_PATH}" "${CLUSTER_CIDR_WORKLOAD_EXTERNAL_DOT_PATH}")
    export CLUSTER_CIDR_WORKLOAD_INTERNAL=$(get_tf_value "${MAIN_FILE_PATH}" "${VPC_CIDR_WORKLOAD_INTERNAL_DOT_PATH}")
    export VPC_ID_VALUE=$(get_tf_value "${TERRAFORMTF_FILE_PATH}" "${VPC_ID_DOT_PATH}")
    export VPC_NAME_VALUE=$(get_tf_value "${TERRAFORMTF_FILE_PATH}" "${VPC_NAME_DOT_PATH}")
    VPC_CIDR_PATH=${GITOPS_WORKING_DIR}/${GITHUB_REPO}/${REGION_NAME}/vpcs/${VPC_NAME_VALUE}/main.tf
    export VPC_CIDR_WORKLOAD_INTERNAL=$(get_tf_value "${VPC_CIDR_PATH}" "${VPC_CIDR_WORKLOAD_DOT_PATH}")

    echo "CLUSTER_CIDR_WORKLOAD_EXTERNAL  ${CLUSTER_CIDR_WORKLOAD_EXTERNAL}"
    echo "CLUSTER_CIDR_WORKLOAD_INTERNAL  ${CLUSTER_CIDR_WORKLOAD_INTERNAL}"
    echo "VPC_CIDR_WORKLOAD_INTERNAL  ${VPC_CIDR_WORKLOAD_INTERNAL}"

    # Check if EFS parameters are set and export flags for template usage
    # Check for manage (db2 and main)
    if [[ -n "$EFS_MANAGE_DB2_PERFORMANCE_MODE" && -n "$EFS_MANAGE_DB2_MOUNT_COUNT" && -n "$EFS_MANAGE_DB2_THROUGHPUT_MODE" ]]; then
      export EFS_MANAGE=true
      echo "EFS_MANAGE set to true"
    else
      export EFS_MANAGE=false
    fi

    # Check for iot_db2
    if [[ -n "$EFS_IOT_DB2_PERFORMANCE_MODE" && -n "$EFS_IOT_DB2_MOUNT_COUNT" && -n "$EFS_IOT_DB2_THROUGHPUT_MODE" ]]; then
      export EFS_IOT=true
      echo "EFS_IOT set to true"
    else
      export EFS_IOT=false
    fi

    # Check for facilities (db2 and main)
    if [[ -n "$EFS_FACILITIES_DB2_PERFORMANCE_MODE" && -n "$EFS_FACILITIES_DB2_MOUNT_COUNT" && -n "$EFS_FACILITIES_DB2_THROUGHPUT_MODE" ]]; then
      export EFS_FACILITIES=true
      echo "EFS_FACILITIES set to true"
    else
      export EFS_FACILITIES=false
    fi

    # Check for visualinspection_main
    if [[ -n "$EFS_VISUALINSPECTION_MAIN_PERFORMANCE_MODE" && -n "$EFS_VISUALINSPECTION_MAIN_MOUNT_COUNT" && -n "$EFS_VISUALINSPECTION_MAIN_THROUGHPUT_MODE" ]]; then
      export EFS_VISUALINSPECTION=true
      echo "EFS_VISUALINSPECTION set to true"
    else
      export EFS_VISUALINSPECTION=false
    fi

    #Generating .tf files using templates
    echo "Generating main.tf file ${GITOPS_CLUSTER_DIR}/main.tf "
    jinjanate_commmon $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-iac-mainTF.yaml.j2 ${GITOPS_CLUSTER_DIR}/main.tf

    echo "Generating terraform.tfvars file ${GITOPS_CLUSTER_DIR}/terraform.tfvars"
    jinjanate_commmon $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-iac-terraformTFvars.yaml.j2 ${GITOPS_CLUSTER_DIR}/terraform.tfvars

    echo "Generating IAC EFS file ${GITOPS_CLUSTER_DIR}/efs.tf"
    jinjanate_commmon $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-iac-efs.yaml.j2 ${GITOPS_CLUSTER_DIR}/efs.tf

    echo "Generating IAC Variables file ${GITOPS_CLUSTER_DIR}/variables.tf"
    jinjanate_commmon $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-iac-variablesTF.yaml.j2 ${GITOPS_CLUSTER_DIR}/variables.tf

    echo $GIT_COMMIT_MSG
    GIT_COMMIT_MSG="${GIT_COMMIT_MSG}-efs"
  fi

  # Commit and push to github target repo with PR creation
  # ---------------------------------------------------------------------------
  if [ "$GITHUB_PUSH" == "true" ]; then
    echo
    echo_h2 "Creating Pull Request for changes in $GITHUB_ORG/$GITHUB_REPO"
    
    # Use the new function that checks for existing PRs and creates a new one
    # Capture the PR number returned by the function
    PR_NUMBER=$(git_commit_and_create_pr_if_none_exist \
      "$GITHUB_HOST" \
      "$GITHUB_ORG" \
      "$GITHUB_REPO" \
      "$GIT_BRANCH" \
      "${GITOPS_WORKING_DIR}/${GITHUB_REPO}" \
      "${GIT_COMMIT_MSG}")

    echo "Created PR #${PR_NUMBER}"
    # Clean up
    remove_git_repo_clone $GITOPS_WORKING_DIR/$GITHUB_REPO
    
    # Monitor PR status if PR was created
    if [[ -n "${PR_NUMBER}" && "${PR_NUMBER}" != "null" ]]; then
      
      echo_h2 "Monitoring PR #${PR_NUMBER} Status"
      ATLANTIS_UNLOCK_COMMENT_BODY="atlantis unlock"
      PR_PLAN_COMMENT=$(read_and_validate_pr_comments "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER")
      echo "PR_PLAN_COMMENT: "$PR_PLAN_COMMENT
      
      if [[ "$PR_PLAN_COMMENT" == "Passed" ]]; then
        echo "Going to approve PR: "${PR_NUMBER}
        echo "IAC DEV PAT TOKEN: "${IAC_DEV_GITHUB_PAT}
        APPROVED_PR=$(approve_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER" "$IAC_DEV_GITHUB_PAT")
        echo "PR approved ${APPROVED_PR}"
        if [[ "$APPROVED_PR" == "true" ]]; then
          sleep 120
          COMMENT_BODY="atlantis apply"
          ATLANTIS_APPLY_COMMENT=$(comment_on_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER" "$COMMENT_BODY")
          if [[ "$ATLANTIS_APPLY_COMMENT" == "true" ]]; then

            PR_APPLY_COMMENT=$(read_and_validate_pr_comments "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER" "apply")

            if [[ "$PR_APPLY_COMMENT" == "Passed" ]]; then
              MARGE_PR_STATUS=$(merge_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER" "Merge PR")
              if [[ "$MARGE_PR_STATUS" != "true" ]]; then
                echo_h2 "⚠️  Atlantis apply succeeded. Failed to merge PR. Please check the PR: 'https://${GITHUB_HOST}/${GITHUB_ORG}/${GITHUB_REPO}/pull/${PR_NUMBER}'"
                # close_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER"
                exit 1
              fi
            else
              echo_h2 "⚠️  Atlantis Apply Failed. Pipeline Failed."
              comment_on_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER" "$ATLANTIS_UNLOCK_COMMENT_BODY"
              close_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER"
              exit 1
            fi
          else
            echo_h2 "⚠️  Failed to add 'Atlantis Apply' on PR. PIPELINE FAILED. CLOSING PR."
            comment_on_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER" "$ATLANTIS_UNLOCK_COMMENT_BODY"
            close_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER"
            exit 1
          fi
        else
          echo_h2 "⚠️  Failed to approve PR. Closing PR. Pipeline Failed."
          comment_on_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER" "$ATLANTIS_UNLOCK_COMMENT_BODY"
          close_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER"
          exit 1
        fi
      else
        echo_h2 "⚠️  Atlantis Plan Failed. Closing PR. Pipeline Failed."
        comment_on_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER" "$ATLANTIS_UNLOCK_COMMENT_BODY"
        close_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER"
        exit 1
      fi
    else
      echo
      echo_h2 "⚠️  No PR number returned, pipeline failed."
      exit 1
    fi
  fi

  echo
  echo_h2 "✅ GitOps IAC EFS Configuration Complete"

  exit 0
}


