#!/usr/bin/env bash

function gitops_deprovision_suite_config_help() {
  [[ -n "$1" ]] && echo_warning "$1"
  reset_colors
  cat << EOM
Usage:
  mas gitops_deprovision_suite_config [options]
Where ${COLOR_YELLOW}specified${TEXT_RESET} each option may also be defined by setting the appropriate environment variable.
When no options are specified on the command line, interactive-mode will be enabled by default.

Options:

GitOps Configuration:
  -d, --dir ${COLOR_YELLOW}GITOPS_WORKING_DIR${TEXT_RESET}           Working directory for GitOps repository
  -g, --gitops-version ${COLOR_YELLOW}GITOPS_VERSION${TEXT_RESET}    Version of ibm-mas/gitops to use
  -a, --account-id ${COLOR_YELLOW}ACCOUNT_ID${TEXT_RESET}            Account name that the cluster belongs to
  -r, --region-id ${COLOR_YELLOW}CLUSTER_ID${TEXT_RESET}             Region ID
  -c, --cluster-id ${COLOR_YELLOW}CLUSTER_ID${TEXT_RESET}            Cluster ID
  -m, --mas-instance-id ${COLOR_YELLOW}MAS_INSTANCE_ID${TEXT_RESET}  IBM Suite Maximo Application Suite Instance ID
  -f, --force-removal ${COLOR_YELLOW}FORCE_REMOVAL${TEXT_RESET}      Force remove the ArgoCD Application, when deletion exceeds timeout  

Secrets Manager:
      --secrets-path ${COLOR_YELLOW}SECRETS_PATH${TEXT_RESET}                    Secrets Manager path
      --secrets-key-seperator ${COLOR_YELLOW}SECRETS_KEY_SEPERATOR${TEXT_RESET}  Secrets Manager key seperator string

Automatic GitHub Push:
  -P, --github-push ${COLOR_YELLOW}GITHUB_PUSH${TEXT_RESET}        Enable automatic push to GitHub
  -H, --github-host ${COLOR_YELLOW}GITHUB_HOST${TEXT_RESET}        GitHub Hostname for your GitOps repository
  -O, --github-org  ${COLOR_YELLOW}GITHUB_ORG${TEXT_RESET}         Github org for your GitOps repository
  -R, --github-repo ${COLOR_YELLOW}GITHUB_REPO${TEXT_RESET}        Github repo for your GitOps repository
  -B, --git-branch ${COLOR_YELLOW}GIT_BRANCH${TEXT_RESET}          Git branch to commit to of your GitOps repository
  -M, --git-commit-msg ${COLOR_YELLOW}GIT_COMMIT_MSG${TEXT_RESET}  Git commit message to use when committing to of your GitOps repository
  -S , --github-ssh  ${COLOR_YELLOW}GIT_SSH${TEXT_RESET}           Git ssh key path

Other Commands:
  -h, --help                                      Show this help message
EOM
  [[ -n "$1" ]] && exit 1 || exit 0
}

function gitops_deprovision_suite_config_noninteractive() {
  GITOPS_WORKING_DIR=$PWD/working-dir
  SECRETS_KEY_SEPERATOR="/"
  GIT_COMMIT_MSG="gitops-deprovision-suite-config commit"
  export GITOPS_VERSION=${GITOPS_VERSION:-poc}

  export REGION=${REGION:-${SM_AWS_REGION}}

  while [[ $# -gt 0 ]]
  do
    key="$1"
    shift
    case $key in
      -d|--dir)
        export GITOPS_WORKING_DIR=$1 && shift
        ;;
      -g|--gitops-version)
        export GITOPS_VERSION=$1 && shift
        ;;
      -a|--account-id)
        export ACCOUNT_ID=$1 && shift
        ;;
      -r|--region-id)
        export REGION=$1 && shift
        ;;
      -c|--cluster-id)
        export CLUSTER_ID=$1 && shift
        ;;
      -m|--mas-instance-id)
        export MAS_INSTANCE_ID=$1 && shift
        ;;
      -f|--force-removal)
        export FORCE_REMOVAL=$1 && shift
        ;;
      # Secrets Manager
      --secrets-path)
        export SECRETS_PATH=$1 && shift
        ;;
      --secrets-key-seperator)
        export SECRETS_KEY_SEPERATOR=$1 && shift
        ;;

      # Automatic GitHub Push
      -P|--github-push)
        export GITHUB_PUSH=true
        ;;
      -H|--github-host)
        export GITHUB_HOST=$1 && shift
        ;;
      -O|--github-org)
        export GITHUB_ORG=$1 && shift
        ;;
      -R|--github-repo)
        export GITHUB_REPO=$1 && shift
        ;;
      -B|--git-branch)
        export GIT_BRANCH=$1 && shift
        ;;
      -M|--git-commit-msg)
        export GIT_COMMIT_MSG=$1 && shift
        ;;
       -S|--github-ssh)
        export GIT_SSH=$1 && shift
        ;;

      -h|--help)
        gitops_deprovision_suite_config_help
        ;;
      *)
        # unknown option
        echo -e "${COLOR_RED}Usage Error: Unsupported option \"${key}\"${COLOR_RESET}\n"
        gitops_deprovision_suite_config_help  "Usage Error: Unsupported option \"${key}\" "
        exit 1
        ;;
      esac
  done

  [[ -z "$GITOPS_WORKING_DIR" ]] && gitops_deprovision_suite_config_help "GITOPS_WORKING_DIR is not set"
  [[ -z "$GITOPS_VERSION" ]] && gitops_deprovision_suite_config_help "GITOPS_VERSION is not set"
  [[ -z "$CLUSTER_ID" ]] && gitops_deprovision_suite_config_help "CLUSTER_ID is not set"
  [[ -z "$REGION" ]] && gitops_deprovision_app_config_help "REGION is not set"
  [[ -z "$ACCOUNT_ID" ]] && gitops_deprovision_suite_config_help "ACCOUNT_ID is not set"
  if [[ "$GITHUB_PUSH" == "true" ]]; then
    [[ -z "$GITHUB_HOST" ]] && gitops_deprovision_suite_config_help "GITHUB_HOST is not set"
    [[ -z "$GITHUB_ORG" ]] && gitops_deprovision_suite_config_help "GITHUB_ORG is not set"
    [[ -z "$GITHUB_REPO" ]] && gitops_deprovision_suite_config_help "GITHUB_REPO is not set"
    [[ -z "$GIT_BRANCH" ]] && gitops_deprovision_suite_config_help "GIT_BRANCH is not set"
  fi
}

function gitops_deprovision_suite_config() {
  # Take the first parameter off (it will be create-gitops)
  shift
  if [[ $# -gt 0 ]]; then
    gitops_deprovision_suite_config_noninteractive "$@"
  else
    echo "Not supported yet"
    exit 1
    gitops_deprovision_suite_config_interactive
  fi

  mkdir -p ${GITOPS_WORKING_DIR}
  GITOPS_INSTANCE_DIR=${GITOPS_WORKING_DIR}/${GITHUB_REPO}/${ACCOUNT_ID}/${REGION}/${CLUSTER_ID}/${MAS_INSTANCE_ID}/configs

  echo
  reset_colors
  echo_h2 "Review Settings"

  echo "${TEXT_DIM}"
  echo_h2 "Target" "    "
  echo_reset_dim "Account ID............................. ${COLOR_MAGENTA}${ACCOUNT_ID}"
  echo_reset_dim "Region ID ............................. ${COLOR_MAGENTA}${REGION}"
  echo_reset_dim "Cluster ID ............................ ${COLOR_MAGENTA}${CLUSTER_ID}"
  echo_reset_dim "Application Directory ................. ${COLOR_MAGENTA}${GITOPS_INSTANCE_DIR}"
  echo_reset_dim "Force Remove Application Flag ......... ${COLOR_MAGENTA}${FORCE_REMOVAL}"
  reset_colors

  echo "${TEXT_DIM}"
  echo_h2 "Secrets Manager" "    "
  echo_reset_dim "Secrets Path .......................... ${COLOR_MAGENTA}${SECRETS_PATH}"
  reset_colors

  echo "${TEXT_DIM}"
  echo_h2 "GitOps Source" "    "
  echo_reset_dim "GitOps URL ............................ ${COLOR_MAGENTA}https://github.com/ibm-mas/gitops"
  echo_reset_dim "GitOps Version ........................ ${COLOR_MAGENTA}${GITOPS_VERSION}"
  reset_colors

  echo "${TEXT_DIM}"
  if [[ "$GITHUB_PUSH" == "true" ]]; then
    echo_h2 "GitOps Target" "    "
    echo_reset_dim "Automatic Push ........................ ${COLOR_GREEN}Enabled"
    echo_reset_dim "Working Directory ..................... ${COLOR_MAGENTA}${GITOPS_WORKING_DIR}"
    echo_reset_dim "Host .................................. ${COLOR_MAGENTA}${GITHUB_HOST}"
    echo_reset_dim "Organization .......................... ${COLOR_MAGENTA}${GITHUB_ORG}"
    echo_reset_dim "Repository ............................ ${COLOR_MAGENTA}${GITHUB_REPO}"
    echo_reset_dim "Branch ................................ ${COLOR_MAGENTA}${GIT_BRANCH}"
  else
    echo_h2 "GitOps Target" "    "
    echo_reset_dim "Automatic Push ........................ ${COLOR_RED}Disabled"
    echo_reset_dim "Working Directory ..................... ${COLOR_MAGENTA}${GITOPS_WORKING_DIR}"
  fi
  reset_colors

  echo "${TEXT_DIM}"
  echo_h2 "IBM Suite License Service" "    "
  echo_reset_dim "SLS URL  .............................. ${COLOR_MAGENTA}https://sls.mas-${MAS_INSTANCE_ID}-sls.svc"
  reset_colors

  echo "${TEXT_DIM}"
  echo_h2 "IBM Maximo Application Suite" "    "
  echo_reset_dim "Instance ID ........................... ${COLOR_MAGENTA}${MAS_INSTANCE_ID}"
  reset_colors

  # Get the cluster-level secrets used
  # ---------------------------------------------------------------------------
  CURRENT_DIR=$PWD
  TEMP_DIR=$CURRENT_DIR/tmp-suite-config-deprovision
  rm -rf $TEMP_DIR
  mkdir -p $TEMP_DIR

  sm_login

  # Instance-level secrets to delete
  # ---------------------------------------------------------------------------
  export SECRET_NAME_SLS=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}sls

  # Delete SLS Registration key for this MAS Instance
  # ---------------------------------------------------------------------------
  echo " Deleting $SECRET_NAME_SLS"
  sm_delete_secret $SECRET_NAME_SLS 

  if [ -z $GIT_SSH ]; then
    export GIT_SSH="false"
  fi


  # Clone github target repo
  # ---------------------------------------------------------------------------
  if [ "$GITHUB_PUSH" == "true" ]; then
    echo
    echo_h2 "Cloning GitHub repo $GITHUB_ORG $GITHUB_REPO"
    clone_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_WORKING_DIR $GIT_SSH
  fi
  mkdir -p ${GITOPS_INSTANCE_DIR}

    
  if [ "$GITHUB_PUSH" == "true" ]; then
    argocd_login
  fi


  # Append the ;delete: true' flag iff the config file exists and the flag is not in there already

  # TODO: move this logic into a function for re-use - maybe even into gitops_utils for use in all the deprovision scripts
  if [[ -f "${GITOPS_INSTANCE_DIR}/wsapp-masdev-manage.ibm-mas-jdbc-config.yaml" ]]; then
    if [[ -z $(grep '^delete: true$' ${GITOPS_INSTANCE_DIR}/wsapp-masdev-manage.ibm-mas-jdbc-config.yaml) ]]; then
      echo "Adding delete: true flag to config"
      echo -e "\n\ndelete: true" >> ${GITOPS_INSTANCE_DIR}/wsapp-masdev-manage.ibm-mas-jdbc-config.yaml

      # Commit and push to github target repo
      # ---------------------------------------------------------------------------
      if [ "$GITHUB_PUSH" == "true" ]; then
        echo
        echo_h2 "Commit and push changes to GitHub repo $GITHUB_ORG $GITHUB_REPO"
        save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_INSTANCE_DIR "${GIT_COMMIT_MSG}"

        WSAPP_JDBC_CONFIG_APP="${MAS_INSTANCE_ID}-jdbc-wsapp-${MAS_WORKSPACE_ID}-${MAS_APP_ID}-configs.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"

        argocd_sync "${WSAPP_JDBC_CONFIG_APP}" # Trigger the cleanup job to run

        # wait for it to finish syncing now the delete: true flag has been set
        check_argo_app_synced "${WSAPP_JDBC_CONFIG_APP}"
        # once synced, the CR will have been deleted and we can move on
      fi
    fi
  fi

  if [[ -f "${GITOPS_INSTANCE_DIR}/system.ibm-mas-jdbc-config.yaml" ]]; then
    if [[ -z $(grep '^delete: true$' ${GITOPS_INSTANCE_DIR}/system.ibm-mas-jdbc-config.yaml) ]]; then
      echo "Adding delete: true flag to config"
      echo -e "\n\ndelete: true" >> ${GITOPS_INSTANCE_DIR}/system.ibm-mas-jdbc-config.yaml

      # Commit and push to github target repo
      # ---------------------------------------------------------------------------
      if [ "$GITHUB_PUSH" == "true" ]; then
        echo
        echo_h2 "Commit and push changes to GitHub repo $GITHUB_ORG $GITHUB_REPO"
        save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_INSTANCE_DIR "${GIT_COMMIT_MSG}"

        SYSTEM_JDBC_CONFIG_APP="${MAS_INSTANCE_ID}-jdbc-system.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"

        argocd_sync "${SYSTEM_JDBC_CONFIG_APP}" # Trigger the cleanup job to run

        # wait for it to finish syncing now the delete: true flag has been set
        check_argo_app_synced "${SYSTEM_JDBC_CONFIG_APP}"
        # once synced, the CR will have been deleted and we can move on
      fi
    fi
  fi

  if [[ -f "${GITOPS_INSTANCE_DIR}/system.ibm-mas-sls-config.yaml" ]]; then
    if [[ -z $(grep '^delete: true$' ${GITOPS_INSTANCE_DIR}/system.ibm-mas-sls-config.yaml) ]]; then
      echo "Adding delete: true flag to config"
      echo -e "\n\ndelete: true" >> ${GITOPS_INSTANCE_DIR}/system.ibm-mas-sls-config.yaml

      # Commit and push to github target repo
      # ---------------------------------------------------------------------------
      if [ "$GITHUB_PUSH" == "true" ]; then
        echo
        echo_h2 "Commit and push changes to GitHub repo $GITHUB_ORG $GITHUB_REPO"
        save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_INSTANCE_DIR "${GIT_COMMIT_MSG}"

        SLS_CONFIG_APP="${MAS_INSTANCE_ID}-sls-system.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"

        argocd_sync "${SLS_CONFIG_APP}" # Trigger the cleanup job to run

        # wait for it to finish syncing now the delete: true flag has been set
        check_argo_app_synced "${SLS_CONFIG_APP}"
        # once synced, the CR will have been deleted and we can move on
      fi
    fi
  fi


  if [[ -f "${GITOPS_INSTANCE_DIR}/system.ibm-mas-mongo-config.yaml" ]]; then
    if [[ -z $(grep '^delete: true$' ${GITOPS_INSTANCE_DIR}/system.ibm-mas-mongo-config.yaml) ]]; then
      echo "Adding delete: true flag to config"
      echo -e "\n\ndelete: true" >> ${GITOPS_INSTANCE_DIR}/system.ibm-mas-mongo-config.yaml

      # Commit and push to github target repo
      # ---------------------------------------------------------------------------
      if [ "$GITHUB_PUSH" == "true" ]; then
        echo
        echo_h2 "Commit and push changes to GitHub repo $GITHUB_ORG $GITHUB_REPO"
        save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_INSTANCE_DIR "${GIT_COMMIT_MSG}"

        MONGO_CONFIG_APP="${MAS_INSTANCE_ID}-mongo-system.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"

        argocd_sync "${MONGO_CONFIG_APP}" # Trigger the cleanup job to run

        # wait for it to finish syncing now the delete: true flag has been set
        check_argo_app_synced "${MONGO_CONFIG_APP}"
        # once synced, the CR will have been deleted and we can move on
      fi
    fi
  fi

  if [[ -f "${GITOPS_INSTANCE_DIR}/system.ibm-mas-bas-config.yaml" ]]; then
    if [[ -z $(grep '^delete: true$' ${GITOPS_INSTANCE_DIR}/system.ibm-mas-bas-config.yaml) ]]; then
      echo "Adding delete: true flag to config"
      echo -e "\n\ndelete: true" >> ${GITOPS_INSTANCE_DIR}/system.ibm-mas-bas-config.yaml

      # Commit and push to github target repo
      # ---------------------------------------------------------------------------
      if [ "$GITHUB_PUSH" == "true" ]; then
        echo
        echo_h2 "Commit and push changes to GitHub repo $GITHUB_ORG $GITHUB_REPO"
        save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_INSTANCE_DIR "${GIT_COMMIT_MSG}"

        BAS_CONFIG_APP="${MAS_INSTANCE_ID}-bas-system.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"

        argocd_sync "${BAS_CONFIG_APP}" # Trigger the cleanup job to run

        # wait for it to finish syncing now the delete: true flag has been set
        check_argo_app_synced "${BAS_CONFIG_APP}"
        # once synced, the CR will have been deleted and we can move on
      fi
    fi
  fi

  # Delete config file that triggers system-configs ArgoCD application to render charts for this config type
  # ---------------------------------------------------------------------------
  rm ${GITOPS_INSTANCE_DIR}/wsapp-masdev-manage.ibm-mas-jdbc-config.yaml
  rm ${GITOPS_INSTANCE_DIR}/system.ibm-mas-jdbc-config.yaml
  rm ${GITOPS_INSTANCE_DIR}/system.ibm-mas-sls-config.yaml
  rm ${GITOPS_INSTANCE_DIR}/system.ibm-mas-mongo-config.yaml
  rm ${GITOPS_INSTANCE_DIR}/system.ibm-mas-bas-config.yaml

  # Commit and push to github target repo
  # ---------------------------------------------------------------------------
  if [ "$GITHUB_PUSH" == "true" ]; then
    echo
    echo_h2 "Commit and push changes to GitHub repo $GITHUB_ORG $GITHUB_REPO"
    save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_INSTANCE_DIR "${GIT_COMMIT_MSG}"
    remove_git_repo_clone $GITOPS_WORKING_DIR/$GITHUB_REPO

    INSTANCE_ROOT_APP="instance.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"

    # TODO: currently hard-coded to support only the known system/wsapp JDBC bindings
    WSAPP_JDBC_CONFIG_APP="${MAS_INSTANCE_ID}-jdbc-wsapp-${MAS_WORKSPACE_ID}-${MAS_APP_ID}-configs.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"
    SYSTEM_JDBC_CONFIG_APP="${MAS_INSTANCE_ID}-jdbc-system.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"
    MONGO_CONFIG_APP="${MAS_INSTANCE_ID}-mongo-system.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"
    BAS_CONFIG_APP="${MAS_INSTANCE_ID}-bas-system.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"
    SLS_CONFIG_APP="${MAS_INSTANCE_ID}-sls-system.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"

    argocd_login
    argocd_prune_sync "${INSTANCE_ROOT_APP}" ## trigger the config app set to notice the deletion of the config file

    check_argo_app_deleted ${WSAPP_JDBC_CONFIG_APP} "mas"
    check_argo_app_deleted ${SYSTEM_JDBC_CONFIG_APP} "mas"
    check_argo_app_deleted ${MONGO_CONFIG_APP} "mas"
    check_argo_app_deleted ${BAS_CONFIG_APP} "mas"
    check_argo_app_deleted ${SLS_CONFIG_APP} "mas"
    
  fi
}
