#!/bin/bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MG_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd "../must-gather" && pwd )"

function mustgather() {
  # Take the first parameter off (it will be "must-gather")
  shift

  # Set defaults
  SUMMARY_ONLY=false
  POD_LOGS=true
  OUTPUT_DIR=/tmp/must-gather

  # Process command flags
  while [[ $# -gt 0 ]]
  do
    key="$1"
    shift
    case $key in
    -d|--directory)
      OUTPUT_DIR=$1; shift
      ;;
    --summary-only)
      SUMMARY_ONLY=true
      ;;
    --no-pod-logs)
      POD_LOGS=false
      ;;
    *)
      # unknown option
      echo -e "${COLOR_RED}Usage Error: Unsupported option \"${key}\"${COLOR_RESET}\n"
      mirror_to_registry_help
      exit 1
      ;;
    esac
  done

  OUTPUT_DIR=${OUTPUT_DIR}/$(date +"%Y%m%d-%H%M%S")
  mkdir -p $OUTPUT_DIR

  echo "Must gather will be saved to: $OUTPUT_DIR"

  # Generate Dependency Report
  # -----------------------------------------------------------------------------
  echo_h2 "Generate Dependency Report"
  echo "- Cluster Namespaces"
  oc get namespaces -o wide > ${OUTPUT_DIR}/namespaces.txt

  echo "- IBM CloudPak Foundation Services"
  $MG_DIR/mg-summary-ibm-common-services 2&> ${OUTPUT_DIR}/ibm-common-services.txt

  echo "- IBM CloudPak for Data"
  $MG_DIR/mg-summary-cp4d 2&> ${OUTPUT_DIR}/cp4d.txt

  echo "- IBM Db2 universal Operator"
  $MG_DIR/mg-summary-db2u 2&> ${OUTPUT_DIR}/db2u.txt

  # Find MAS instances
  # -----------------------------------------------------------------------------
  MAS_INSTANCE_IDS=$(oc get suite --all-namespaces -o jsonpath='{.items[*].metadata.name}')

  # Generate Detailed Report
  # -----------------------------------------------------------------------------
  echo ""
  for MAS_INSTANCE_ID in $MAS_INSTANCE_IDS
  do
    echo_h2 "Maximo Application Suite Must Gather: ${MAS_INSTANCE_ID}"

    for MAS_APP_ID in core assist iot monitor manage optimizer visualinspection
    do
      MAS_APP_NAMESPACE=mas-${MAS_INSTANCE_ID}-${MAS_APP_ID}
      NAMESPACE_LOOKUP=$(oc get namespace $MAS_APP_NAMESPACE --ignore-not-found)

      if [[ "$NAMESPACE_LOOKUP" != "" ]]
      then
        echo -e "- Performing must-gather in namespace ${MAS_APP_NAMESPACE}"
        # MAS-specific must-gather
        $MG_DIR/mg-summary-mas-${MAS_APP_ID} $MAS_APP_NAMESPACE > ${OUTPUT_DIR}/mas-${MAS_INSTANCE_ID}-${MAS_APP_ID}.txt
        $MG_DIR/mg-collect-mas-${MAS_APP_ID} $MAS_APP_NAMESPACE $OUTPUT_DIR

        # Generic Kubernetes must-gather
        if [[ "$SUMMARY_ONLY" == false ]]
        then
          $MG_DIR/mg-collect-pods $MAS_APP_NAMESPACE $POD_LOGS $OUTPUT_DIR/resources
          for RESOURCE in configmaps secrets services routes pvc deployments statefulsets
          do
            $MG_DIR/mg-collect-resources $MAS_APP_NAMESPACE $RESOURCE $OUTPUT_DIR/resources
          done
        fi
      fi
    done
  done

  true
}
