#!/bin/bash

function echo_reset_dim() {
  echo "${COLOR_RESET}${TEXT_DIM}    $1"
}

function pipeline_show_config() {
  if [[ ! -e "$CONFIG_DIR/pipelinerun-$MAS_INSTANCE_ID.yaml" ]]; then
    echo_warning "No pipelinerun configuration exists for '$MAS_INSTANCE_ID'"
    exit 1
  fi

  reset_colors
  echo_h2 "\n14. Review Settings"
  echo "${TEXT_DIM}"
  echo_h2 "IBM Maximo Application Suite" "    "
  echo_reset_dim "Instance ID ............... ${COLOR_MAGENTA}${MAS_INSTANCE_ID}"
  echo_reset_dim "Workspace ID .............. ${COLOR_MAGENTA}${MAS_WORKSPACE_ID}"
  echo_reset_dim "Workspace Name ............ ${COLOR_MAGENTA}${MAS_WORKSPACE_NAME}"
  if [[ "${USE_NON_PROD_MODE}" == "true" ]]; then
    echo_reset_dim "Operation Mode ............ ${COLOR_MAGENTA}Non-production"
  else
    echo_reset_dim "Operation Mode ............ ${COLOR_MAGENTA}Production"
  fi

  if [[ "${MAS_DOMAIN}" != "" ]]; then
    echo_reset_dim "Domain Name ............... ${COLOR_MAGENTA}${MAS_DOMAIN}"
    echo_reset_dim "DNS Provider .............. ${COLOR_MAGENTA}${DNS_PROVIDER:-Manually configured}"
    echo_reset_dim "Certificate Issuer ........ ${COLOR_MAGENTA}${MAS_CLUSTER_ISSUER:-Self-Signed}"
  fi
  echo_reset_dim "Catalog Source ............ ${COLOR_MAGENTA}${MAS_CATALOG_SOURCE}"
  echo_reset_dim "Subscription Channel ...... ${COLOR_MAGENTA}${MAS_CHANNEL}"
  echo_reset_dim "IBM Entitled Registry ..... ${COLOR_MAGENTA}${MAS_ICR_CP}"
  echo_reset_dim "IBM Open Registry ......... ${COLOR_MAGENTA}${MAS_ICR_CPOPEN}"
  echo_reset_dim "Entitlement Username ...... ${COLOR_MAGENTA}${MAS_ENTITLEMENT_USERNAME}"
  echo_reset_dim "Entitlement Key ........... ${COLOR_MAGENTA}${MAS_ENTITLEMENT_KEY:0:8}<snip>"

  reset_colors
  echo "${TEXT_DIM}"
  echo_h2 "IBM Maximo Application Suite Applications" "    "
  if [[ "${MAS_APP_CHANNEL_IOT}" == '' ]]
  then echo_reset_dim "IoT ...................... ${COLOR_RED}Skip Installation"
  else echo_reset_dim "IoT ...................... ${COLOR_MAGENTA}${MAS_APP_CHANNEL_IOT}"
  fi

  if [[ "${MAS_APP_CHANNEL_MONITOR}" == '' ]]
  then echo_reset_dim " - Monitor ............... ${COLOR_RED}Skip Installation"
  else echo_reset_dim " - Monitor ............... ${COLOR_MAGENTA}${MAS_APP_CHANNEL_MONITOR}"
  fi

  if [[ "${MAS_APP_CHANNEL_MANAGE}" == '' ]]
  then echo_reset_dim "Manage ................... ${COLOR_RED}Skip Installation"
  else echo_reset_dim "Manage ................... ${COLOR_MAGENTA}${MAS_APP_CHANNEL_MANAGE} (${MAS_APPWS_BINDINGS_JDBC_MANAGE} JDBC Config)"
  fi

  if [[ "${MAS_APP_CHANNEL_PREDICT}" == '' ]]
  then echo_reset_dim " - Predict ............... ${COLOR_RED}Skip Installation"
  else echo_reset_dim " - Predict ............... ${COLOR_MAGENTA}${MAS_APP_CHANNEL_PREDICT}"
  fi

  if [[ "${MAS_CHANNEL}" == '8.8.x' ]]; then
    if [[ "${MAS_APP_CHANNEL_OPTIMIZER}" == '' ]]
    then echo_reset_dim "Optimizer ................ ${COLOR_RED}Skip Installation"
    else echo_reset_dim "Optimizer ................ ${COLOR_MAGENTA}${MAS_APP_CHANNEL_OPTIMIZER} (${MAS_APP_PLAN_OPTIMIZER})"
    fi
  fi

  if [[ "${MAS_APP_CHANNEL_HPUTILITIES}" == '' ]]
  then echo_reset_dim "H & P Utilities .......... ${COLOR_RED}Skip Installation"
  else echo_reset_dim "H & P Utilities .......... ${COLOR_MAGENTA}${MAS_APP_CHANNEL_HPUTILITIES}"
  fi

  if [[ "${MAS_APP_CHANNEL_ASSIST}" == '' ]]
  then echo_reset_dim "Assist ................... ${COLOR_RED}Skip Installation"
  else echo_reset_dim "Assist ................... ${COLOR_MAGENTA}${MAS_APP_CHANNEL_ASSIST}"
  fi

  if [[ "${MAS_APP_CHANNEL_VISUALINSPECTION}" == '' ]]
  then echo_reset_dim "MVI ...................... ${COLOR_RED}Skip Installation"
  else echo_reset_dim "MVI ...................... ${COLOR_MAGENTA}${MAS_APP_CHANNEL_VISUALINSPECTION}"
  fi

  reset_colors
  echo "${TEXT_DIM}"
  echo_h2 "IBM Suite License Service" "    "
  echo_reset_dim "Catalog Source ............ ${COLOR_MAGENTA}${SLS_CATALOG_SOURCE}"
  echo_reset_dim "License ID ................ ${COLOR_MAGENTA}${SLS_LICENSE_ID}"
  echo_reset_dim "License File .............. ${COLOR_MAGENTA}${SLS_LICENSE_FILE}"
  echo_reset_dim "IBM Entitled Registry ..... ${COLOR_MAGENTA}${SLS_ICR_CP}"
  echo_reset_dim "IBM Open Registry ......... ${COLOR_MAGENTA}${SLS_ICR_CPOPEN}"
  echo_reset_dim "Entitlement Username ...... ${COLOR_MAGENTA}${SLS_ENTITLEMENT_USERNAME}"
  echo_reset_dim "Entitlement Key ........... ${COLOR_MAGENTA}${SLS_ENTITLEMENT_KEY:0:8}<snip>"

  reset_colors
  echo "${TEXT_DIM}"
  echo_h2 "IBM User Data Services" "    "
  echo_reset_dim "Contact Email ............. ${COLOR_MAGENTA}${UDS_CONTACT_EMAIL}"
  echo_reset_dim "First Name ................ ${COLOR_MAGENTA}${UDS_CONTACT_FIRSTNAME}"
  echo_reset_dim "Last Name ................. ${COLOR_MAGENTA}${UDS_CONTACT_LASTNAME}"

  if [[ "$DEPLOY_CP4D" == "run" ]]; then
    reset_colors
    echo "${TEXT_DIM}"
    echo_h2 "IBM Cloud Pak for Data" "    "
    echo_reset_dim "Entitlement Key ........... ${COLOR_MAGENTA}${IBM_ENTITLEMENT_KEY:0:8}<snip>"
    echo_reset_dim "Product Version ........... ${COLOR_MAGENTA}${CP4D_VERSION}"
  fi

  if [[ "$DB2_ACTION_SYSTEM" == "install" || "$DB2_ACTION_MANAGE" == "install" ]]; then
    reset_colors
    echo "${TEXT_DIM}"
    echo_h2 "IBM Db2" "    "
    echo_reset_dim "System Instance ........... ${COLOR_MAGENTA}${DB2_ACTION_SYSTEM}"
    echo_reset_dim "Dedicated Manage Instance . ${COLOR_MAGENTA}${DB2_ACTION_MANAGE}"

    echo_reset_dim "CPU Request ............... ${COLOR_MAGENTA}${DB2_CPU_REQUESTS:-Default}"
    echo_reset_dim "CPU Limit ................. ${COLOR_MAGENTA}${DB2_CPU_LIMITS:-Default}"
    echo_reset_dim "Memory Request ............ ${COLOR_MAGENTA}${DB2_MEMORY_REQUESTS:-Default}"
    echo_reset_dim "Memory Limit .............. ${COLOR_MAGENTA}${DB2_MEMORY_LIMITS:-Default}"

    echo_reset_dim "Meta Storage .............. ${COLOR_MAGENTA}${DB2_META_STORAGE_SIZE:-Default}"
    echo_reset_dim "Data Storage .............. ${COLOR_MAGENTA}${DB2_DATA_STORAGE_SIZE:-Default}"
    echo_reset_dim "Backup Storage ............ ${COLOR_MAGENTA}${DB2_BACKUP_STORAGE_SIZE:-Default}"
    echo_reset_dim "Temp Storage .............. ${COLOR_MAGENTA}${DB2_TEMP_STORAGE_SIZE:-Default}"
    echo_reset_dim "Transaction Logs Storage .. ${COLOR_MAGENTA}${DB2_LOGS_STORAGE_SIZE:-Default}"
  fi

  reset_colors
  echo "${TEXT_DIM}"
  echo_h2 "Storage Class Configuration" "    "
  echo_reset_dim "Storage Class Provider ... ${COLOR_MAGENTA}${STORAGE_CLASS_PROVIDER}"
  if [[ "$STORAGE_CLASS_PROVIDER" == "custom" ]]; then
    echo_reset_dim "ReadWriteOnce ............ ${COLOR_MAGENTA}${STORAGE_CLASS_RWO}"
    echo_reset_dim "ReadWriteMany ............ ${COLOR_MAGENTA}${STORAGE_CLASS_RWX}"
  fi

  if [[ "$SNO_MODE" == "true" ]]; then
    reset_colors
    echo "${TEXT_DIM}"
    echo_h2 "DB2 Configuration" "    "
    echo_reset_dim "Meta Storage Size ................ ${COLOR_MAGENTA}${DB2_META_STORAGE_SIZE}"
    echo_reset_dim "Data Storage Size ................ ${COLOR_MAGENTA}${DB2_DATA_STORAGE_SIZE}"
    echo_reset_dim "Backup Storage Size .............. ${COLOR_MAGENTA}${DB2_BACKUP_STORAGE_SIZE}"
    echo_reset_dim "Temp Storage Size ................ ${COLOR_MAGENTA}${DB2_TEMP_STORAGE_SIZE}"
    echo_reset_dim "Logs Storage Size ................ ${COLOR_MAGENTA}${DB2_LOGS_STORAGE_SIZE}"
  fi

  #JDBC Configuration
  if [[ "${CONFIGURE_EXTERNAL_DB}" == "true" ]]; then
    reset_colors
    echo "${TEXT_DIM}"
    echo_h2 "JDBC Configuration" "    "
    echo_reset_dim "DB User .................. ${COLOR_MAGENTA}${MAS_JDBC_USER}"
    echo_reset_dim "DB URL ................... ${COLOR_MAGENTA}${MAS_JDBC_URL}"
    echo_reset_dim "DB Schema ................ ${COLOR_MAGENTA}${MAS_APP_SETTINGS_DB2_SCHEMA}"
    echo_reset_dim "Tablespace ............... ${COLOR_MAGENTA}${MAS_APP_SETTINGS_TABLESPACE}"
    echo_reset_dim "Indexspace ............... ${COLOR_MAGENTA}${MAS_APP_SETTINGS_INDEXSPACE}"
    echo_reset_dim "SSL enabled .............. ${COLOR_MAGENTA}${SSL_ENABLED}" 
    echo_reset_dim "JDBC binding ............. ${COLOR_MAGENTA}${mas_appws_bindings_jdbc_manage}"
    
    if [[ "${SSL_ENABLED}" == "true" ]]; then
      echo_reset_dim "SSL Certificate Path ... ${COLOR_MAGENTA}${MAS_JDBC_CERT_LOCAL_FILE}"
    fi
  fi

  reset_colors
  echo "${TEXT_RESET}"
  prompt_for_confirm "Proceed with these settings" || exit 0

}
