#!/bin/bash

# - Set up namespace
# - Create tasks and pipeline resources
# - Set up RBAC
function pipeline_install_tasks() {
  # Install the MAS Tekton definitions
  cp $DIR/templates/ibm-mas-tekton.yaml $CONFIG_DIR/ibm-mas-tekton-$MAS_INSTANCE_ID.yaml
  sed -e "s/cli:latest/cli:$VERSION/g" $DIR/templates/deployment.yaml > $CONFIG_DIR/deployment-$MAS_INSTANCE_ID.yaml
  CLI_IMAGE=quay.io/ibmmas/cli:$VERSION

  if [[ "$AIRGAP_MODE" == "true" ]]; then
    prompt_for_confirm_default_yes "Override image tag '$VERSION' with digest?" USE_DIGEST
    if [[ "$USE_DIGEST" == "true" ]]; then
      skopeo inspect docker://quay.io/ibmmas/cli:$VERSION &> /dev/null
      if [[ "$?" == "0" ]]; then
        CLI_IMAGE_DIGEST=$(skopeo inspect docker://quay.io/ibmmas/cli:$VERSION 2>> $LOGFILE | jq -r ".Digest")
        if [[ "$CLI_IMAGE_DIGEST" == "" ]]; then
          echo_warning "Unable to retrieve image digest for quay.io/ibmmas/cli:$VERSION"
          exit 1
        fi
        echo "Using image digest $CLI_IMAGE_DIGEST"
      else
        echo "Unable to communicate with quay.io, please manually enter the digest."
        prompt_for_input "quay.io/ibmmas/cli image digest" CLI_IMAGE_DIGEST
      fi
      # Overwrite the tekton definitions with one that uses the looked up image digest
      sed -e "s/cli:$VERSION/cli@${CLI_IMAGE_DIGEST}/g" $DIR/templates/ibm-mas-tekton.yaml > $CONFIG_DIR/ibm-mas-tekton-$MAS_INSTANCE_ID.yaml
      sed -e "s/cli:latest/cli@$CLI_IMAGE_DIGEST/g" $DIR/templates/deployment.yaml > $CONFIG_DIR/deployment-$MAS_INSTANCE_ID.yaml
      CLI_IMAGE=quay.io/ibmmas/cli@$CLI_IMAGE_DIGEST
    fi
  fi

  # Set up namespace
  sed "s/{{mas_instance_id}}/$MAS_INSTANCE_ID/g" $DIR/templates/namespace.yaml > $CONFIG_DIR/namespace-$MAS_INSTANCE_ID.yaml
  oc apply -f $CONFIG_DIR/namespace-$MAS_INSTANCE_ID.yaml &>> $LOGFILE

  # Create tasks and pipeline resources in namespace
  oc -n mas-$MAS_INSTANCE_ID-pipelines apply -f $CONFIG_DIR/ibm-mas-tekton-$MAS_INSTANCE_ID.yaml &>> $LOGFILE

  # Set up RBAC in namespace
  sed "s/{{mas_instance_id}}/$MAS_INSTANCE_ID/g" $DIR/templates/rbac.yaml > $CONFIG_DIR/rbac-$MAS_INSTANCE_ID.yaml
  oc apply -f $CONFIG_DIR/rbac-$MAS_INSTANCE_ID.yaml &>> $LOGFILE
}


function pipeline_install_tasks_shared_namespace() {
  # Install the MAS Tekton definitions
  cp $DIR/templates/ibm-mas-tekton.yaml $CONFIG_DIR/ibm-mas-tekton-cluster.yaml
  sed -e "s/cli:latest/cli:$VERSION/g" $DIR/templates/deployment.yaml > $CONFIG_DIR/deployment-cluster.yaml
  CLI_IMAGE=quay.io/ibmmas/cli:$VERSION

  if [[ "$AIRGAP_MODE" == "true" ]]; then
    prompt_for_confirm_default_yes "Override image tag '$VERSION' with digest?" USE_DIGEST
    if [[ "$USE_DIGEST" == "true" ]]; then
      skopeo inspect docker://quay.io/ibmmas/cli:$VERSION &> /dev/null
      if [[ "$?" == "0" ]]; then
        CLI_IMAGE_DIGEST=$(skopeo inspect docker://quay.io/ibmmas/cli:$VERSION 2>> $LOGFILE | jq -r ".Digest")
        if [[ "$CLI_IMAGE_DIGEST" == "" ]]; then
          echo_warning "Unable to retrieve image digest for quay.io/ibmmas/cli:$VERSION"
          exit 1
        fi
        echo "Using image digest $CLI_IMAGE_DIGEST"
      else
        echo "Unable to communicate with quay.io, please manually enter the digest."
        prompt_for_input "quay.io/ibmmas/cli image digest" CLI_IMAGE_DIGEST
      fi
      # Overwrite the tekton definitions with one that uses the looked up image digest
      sed -e "s/cli:$VERSION/cli@$CLI_IMAGE_DIGEST/g" $DIR/templates/ibm-mas-tekton.yaml > $CONFIG_DIR/ibm-mas-tekton-cluster.yaml
      sed -e "s/cli:latest/cli@$CLI_IMAGE_DIGEST/g" $DIR/templates/deployment.yaml > $CONFIG_DIR/deployment-cluster.yaml
      CLI_IMAGE=quay.io/ibmmas/cli@$CLI_IMAGE_DIGEST
    fi
  fi

  # Set up namespace
  oc apply -f $DIR/templates/namespace-cluster.yaml &>> $LOGFILE

  # Create tasks and pipeline resources in namespace
  oc -n mas-pipelines apply -f $CONFIG_DIR/ibm-mas-tekton-cluster.yaml &>> $LOGFILE

  # Set up RBAC in namespace
  oc apply -f $DIR/templates/rbac-cluster.yaml &>> $LOGFILE
}
