#!/bin/bash

function pipeline_run() {
  echo
  echo_h2 "Launch Installation"
  # Start pipeline execution
  echo "oc -n mas-$MAS_INSTANCE_ID-pipelines create -f $CONFIG_DIR/pipelinerun-$MAS_INSTANCE_ID.yaml &>> $LOGFILE || exit 1"
  oc -n mas-$MAS_INSTANCE_ID-pipelines create -f $CONFIG_DIR/pipelinerun-$MAS_INSTANCE_ID.yaml &>> $LOGFILE || exit 1
  echo -e "${COLOR_GREEN}Installation started successfully${COLOR_RESET}"
  echo -e "\nView progress:\n  ${COLOR_CYAN}${TEXT_UNDERLINE}https://${OCP_CONSOLE_ROUTE}/pipelines/ns/mas-$MAS_INSTANCE_ID-pipelines${TEXT_RESET}${COLOR_RESET}"
  echo
}
