#!/bin/bash

. $DIR/functions/pipeline_config_sno
. $DIR/functions/pipeline_config_applications
. $DIR/functions/pipeline_config_dns
. $DIR/functions/pipeline_config_storage_classes
. $DIR/functions/pipeline_config_storage_classes_sno
. $DIR/functions/pipeline_config_db2

function pipeline_config() {
  echo_h2 "3. Configure Installation"

  MAS_CATALOG_SOURCE=ibm-operator-catalog

  # MAS instance ID
  if [[ ! -z "$1" ]]; then
    MAS_INSTANCE_ID=$1
  fi
  prompt_for_input "MAS Instance ID" MAS_INSTANCE_ID

  if [[ -n "$DEV_MODE" ]]; then
    # Development mode
    prompt_for_input "Select Catalog Source" MAS_CATALOG_VERSION "v8-master-amd64"
    prompt_for_input "Select Subscription Channel" MAS_CHANNEL "m1dev810"
  elif [[ -z "$AIRGAP_MODE" ]]; then
    # Online (GA) mode
    prompt_for_confirm "Use online catalog?" USE_ONLINE_CATALOG
    if [[ "$USE_ONLINE_CATALOG" == "true" ]]; then
      MAS_CATALOG_VERSION=v8-amd64
    else
      echo -e "${COLOR_YELLOW}Catalog Version:"
      echo "  1. v8 (2022-11-29)"
      echo "  2. v8 (2022-10-25)"
      echo "  3. v8 (2022-09-27)"
      echo "  4. v8 (2022-08-05)"
      prompt_for_input "Select Catalog Source" MAS_CATALOG_SELECTION "1"

      case $MAS_CATALOG_SELECTION in
        1|221025|2022-11-29)
          MAS_CATALOG_VERSION=v8-221129-amd64
          ;;
        2|221025|2022-10-25)
          MAS_CATALOG_VERSION=v8-221025-amd64
          ;;
        3|220927|2022-09-27)
          MAS_CATALOG_VERSION=v8-220927-amd64
          ;;
        4|220805|2022-08-05)
          MAS_CATALOG_VERSION=v8-220805-amd64
          ;;
        *)
          exit 1
          ;;
      esac
    fi

    if [[ "$SNO_MODE" == "true" ]]; then
      echo -e "${COLOR_YELLOW}MAS Version:"
      echo "  1. 8.9"
    else
      echo -e "${COLOR_YELLOW}MAS Version:"
      echo "  1. 8.9"
      echo "  2. 8.8"
      echo "  3. 8.7"
    fi
    prompt_for_input "Select Subscription Channel" MAS_CHANNEL_SELECTION "1"

    case $MAS_CHANNEL_SELECTION in
      1|8.9|8.9.x)
        MAS_CHANNEL=8.9.x
        ;;

      2|8.8|8.8.x)
        MAS_CHANNEL=8.8.x
        ;;

      3|8.7|8.7.x)
        MAS_CHANNEL=8.7.x
        ;;

      *)
        MAS_CHANNEL=$MAS_CHANNEL_SELECTION
        ;;
    esac
  else
    # Airgap (GA) mode
    echo -e "${COLOR_YELLOW}MAS Version:"
    echo "  1. 8.9.0 (2022-11-29)"
    echo "  2. 8.8.3 (2022-11-29)"
    echo "  3. 8.8.2 (2022-10-25)"
    echo "  4. 8.8.1 (2022-09-27)"
    echo "  5. 8.8.0 (2022-08-05)"
    prompt_for_input "Select Catalog Source" MAS_CHANNEL_SELECTION "1"

    case $MAS_CHANNEL_SELECTION in
      1|221129|2022-11-29)
        MAS_CHANNEL=8.9.x
        MAS_CATALOG_VERSION=v8-221129-amd64
        ;;
      2|221129|2022-11-29)
        MAS_CHANNEL=8.8.x
        MAS_CATALOG_VERSION=v8-221129-amd64
        ;;
      3|221025|2022-10-25)
        MAS_CHANNEL=8.8.x
        MAS_CATALOG_VERSION=v8-221025-amd64
        ;;
      4|220927|2022-09-27)
        MAS_CHANNEL=8.8.x
        MAS_CATALOG_VERSION=v8-220927-amd64
        ;;
      5|220805|2022-08-05)
        MAS_CHANNEL=8.8.x
        MAS_CATALOG_VERSION=v8-220805-amd64
        ;;

      *)
        echo_warning "Invalid selection"
        exit 1
        ;;
    esac
  fi
  true

  config_pipeline_sno
  config_pipeline_dns
  config_pipeline_applications
  config_pipeline_storage_classes
  if [[ "$SNO_MODE" == "true" ]]; then
    config_pipeline_storage_classes_sno
  else
    config_pipeline_storage_classes
  fi
  config_pipeline_storage_db2_size

  echo ""
  if [[ "$DEV_MODE" == "true" && -z "$AIRGAP_MODE" ]]; then
    # Development Mode -- offer the ability to set MAS and SLS source independently
    echo_h2 "7a. Configure Artifactory"
    prompt_for_input "Artifactory Username" ARTIFACTORY_USERNAME
    prompt_for_input "Artifactory API Key" ARTIFACTORY_APIKEY

    echo
    echo_h2 "7b. Configure IBM Container Registry"
    prompt_for_input "IBM Entitlement Key" IBM_ENTITLEMENT_KEY $IBM_ENTITLEMENT_KEY

    echo
    echo_h2 "7c. Configure IBM Container Registry (MAS)"
    prompt_for_input "IBM Container Registry (cp)" MAS_ICR_CP wiotp-docker-local.artifactory.swg-devops.com override
    prompt_for_input "IBM Container Registry (cpopen)" MAS_ICR_CPOPEN wiotp-docker-local.artifactory.swg-devops.com/cpopen override
#    prompt_for_input "Entitlement Username" MAS_ENTITLEMENT_USERNAME $ARTIFACTORY_USERNAME override
#    prompt_for_input "Entitlement Key" MAS_ENTITLEMENT_KEY $ARTIFACTORY_APIKEY override
    MAS_ENTITLEMENT_USERNAME=cp
    MAS_ENTITLEMENT_KEY=$IBM_ENTITLEMENT_KEY

    echo
    echo_h2 "7d. Configure IBM Container Registry (SLS)"
    prompt_for_input "IBM Container Registry (cp)" SLS_ICR_CP wiotp-docker-local.artifactory.swg-devops.com override
    prompt_for_input "IBM Container Registry (cpopen)" SLS_ICR_CPOPEN wiotp-docker-local.artifactory.swg-devops.com/cpopen override
#    prompt_for_input "Entitlement Username" SLS_ENTITLEMENT_USERNAME $ARTIFACTORY_USERNAME override
#    prompt_for_input "Entitlement Key" SLS_ENTITLEMENT_KEY $ARTIFACTORY_APIKEY override
    SLS_ENTITLEMENT_USERNAME=cp
    SLS_ENTITLEMENT_KEY=$IBM_ENTITLEMENT_KEY
  else
    # Production Mode -- everything comes from the same registry (IBM container registry)
    echo_h2 "7. Configure IBM Container Registry"
    prompt_for_input "IBM Entitlement Key" IBM_ENTITLEMENT_KEY $IBM_ENTITLEMENT_KEY

    # Use defaults
    MAS_ICR_CP=cp.icr.io/cp
    MAS_ICR_CPOPEN=icr.io/cpopen
    MAS_ENTITLEMENT_USERNAME=cp
    MAS_ENTITLEMENT_KEY=$IBM_ENTITLEMENT_KEY

    SLS_ICR_CP=cp.icr.io/cp
    SLS_ICR_CPOPEN=icr.io/cpopen
    SLS_ENTITLEMENT_USERNAME=cp
    SLS_ENTITLEMENT_KEY=$IBM_ENTITLEMENT_KEY
  fi

  COMMON_SERVICES_CATALOG_SOURCE=ibm-operator-catalog
  SLS_CATALOG_SOURCE=ibm-operator-catalog

  echo
  echo_h2 "8. Configure Product License"
  prompt_for_input "License ID" SLS_LICENSE_ID
  prompt_for_input "License File" SLS_LICENSE_FILE_LOCAL
  if [[ ! -e "$SLS_LICENSE_FILE_LOCAL" ]]; then
    echo_warning "Error: File does not exist: $SLS_LICENSE_FILE_LOCAL"
    exit 1
  fi
  SLS_LICENSE_FILE="/workspace/entitlement/$(basename $SLS_LICENSE_FILE_LOCAL)"

  echo
  echo_h2 "9. Configure UDS"
  prompt_for_input "UDS Contact Email" UDS_CONTACT_EMAIL
  prompt_for_input "UDS Contact First Name" UDS_CONTACT_FIRSTNAME
  prompt_for_input "UDS Contact Last Name" UDS_CONTACT_LASTNAME

}
