#!/bin/bash


function config_pipeline_additional_configs() {
  echo
  echo_h2 "8. Additional Configuration"
  echo "${TEXT_DIM}Additional resource definitions can be applied to the OpenShift Cluster during the MAS configuration step."
  echo "The primary purpose of this is to apply configuration for Maximo Application Suite itself, but you can use this to deploy ANY additional resource into your cluster."
  echo
  reset_colors

  if [[ -z "$LOCAL_MAS_CONFIG_DIR_ALREADY_CHOSEN" ]]; then
    # Ask the user if they want to load additional configs
    if prompt_for_confirm "Use additional configurations?"; then
      # Select local MAS_CONFIG_DIR
      prompt_for_input "+ Local config directory" LOCAL_MAS_CONFIG_DIR && export LOCAL_MAS_CONFIG_DIR
      echo
      use_additional_configs=yes
    fi
  else
    # If the user has already generated a config then we will lose additional configs
    use_additional_configs=yes
  fi

  if [[ "$use_additional_configs" == "yes" ]]; then
    ADDITIONAL_CONFIG_FILES=$LOCAL_MAS_CONFIG_DIR/*.yaml
    if [ "$ADDITIONAL_CONFIG_FILES" == "" ]; then
      echo_warning "No configuration files (*.yaml) were found in $LOCAL_MAS_CONFIG_DIR"
      exit 1
    fi

    echo "The following additional configurations will be applied:"
    for FILE in $ADDITIONAL_CONFIG_FILES; do
      echo " - $(basename $FILE)"
    done

    echo
    prompt_for_confirm "Are these the correct configuration files to apply?" || exit 0

    bash $DIR/tools/cfgmgr add $CONFIG_DIR/additional-configs-$MAS_INSTANCE_ID.yaml $LOCAL_MAS_CONFIG_DIR
    echo
  else
    LOCAL_MAS_CONFIG_DIR=""
  fi
}
