#!/bin/bash

function pipeline_install_operator() {
  # Install pipelines support
  echo
  echo_h2 "Install OpenShift Pipelines Operator"
  PIPELINES_CHANNEL=$(oc get packagemanifests openshift-pipelines-operator-rh -o jsonpath="{.status.defaultChannel}")

  if [[ "$PIPELINES_CHANNEL" == "" ]]; then
    echo_warning "Unable to determine correct subscription channel for OpenShift Pipelines on this cluster"
    exit 1
  fi

  PIPELINES_SOURCE=$(oc get packagemanifests openshift-pipelines-operator-rh -o jsonpath="{.status.catalogSource}")
  PIPELINES_SOURCE_NAMESPACE=$(oc get packagemanifests openshift-pipelines-operator-rh -o jsonpath="{.status.catalogSourceNamespace}")

  sed \
    -e "s/{{pipelines_channel}}/$PIPELINES_CHANNEL/g" \
    -e "s/{{pipelines_source}}/$PIPELINES_SOURCE/g" \
    -e "s/{{pipelines_source_namespace}}/$PIPELINES_SOURCE_NAMESPACE/g" \
    $DIR/templates/subscription.yaml | oc apply -f - &>> $LOGFILE

  echo -en "\033[s" # Save cursor position
  echo -n "Installing OpenShift Pipelines Operator ($PIPELINES_CHANNEL) ..."

  oc get crd tasks.tekton.dev &>> $LOGFILE
  LOOKUP_RESULT=$?
  while [ "$LOOKUP_RESULT" == "1" ]; do
    echo "Waiting 5s for tasks.tekton.dev CRD to be installed before checking again ..." &>> $LOGFILE
    sleep 5
    oc get crd tasks.tekton.dev &>> $LOGFILE
    LOOKUP_RESULT=$?
  done

  echo "Wait for Pipeline operator to be ready" &>> $LOGFILE
  oc wait --for=condition=Established  crd tasks.tekton.dev --timeout=30m &>> $LOGFILE

  echo "Wait for Tekton config to be available" &>> $LOGFILE
  oc get TektonConfig config &>> $LOGFILE
  LOOKUP_RESULT=$?
  while [ "$LOOKUP_RESULT" == "1" ]; do
    echo "Waiting 5s for TektonConfig to be created before checking again ..." &>> $LOGFILE
    sleep 5
    oc get TektonConfig config &>> $LOGFILE
    LOOKUP_RESULT=$?
  done

  # Note: We need to use --type merge because it's a custom resource
  echo "Patch Tekton config to enable alpha API fields and scope when expressions to tasks" &>> $LOGFILE
  oc patch TektonConfig config --type merge -p '{"spec":{"pipeline":{"enable-api-fields": "alpha", "scope-when-expressions-to-task": true}}}'  &>> $LOGFILE

  # Increase the default task timeout, which will take effect in OCP 4.11 and newer
  echo "Set the default pipeline tasks timeout to 12 hours" &>> $LOGFILE
  oc patch cm config-defaults -n openshift-pipelines --type merge -p '{"data":{"default-timeout-minutes": "720"}}' &>> $LOGFILE

  echo -en "\033[1K" # Clear current line
  echo -en "\033[u" # Restore cursor position
  echo "${COLOR_GREEN}OpenShift Pipelines Operator is installed and ready${COLOR_RESET}"
  echo
}
