#!/bin/bash

function check_workload_scale_dir(){
  WORKLOAD_SCALE_PROFILE=Custom

  if [[ ! -d "$WORKLOAD_SCALE_DIR" ]]; then
    echo_warning "Error: Directory does not exist: $WORKLOAD_SCALE_DIR"
    exit 1
  fi
}

function set_workload_scale_envs() {
  WORKLOAD_SCALE_DIR_NAME=guaranteed
  [ "$WORKLOAD_SCALE_PROFILE" == "BestEffort" ] && WORKLOAD_SCALE_DIR_NAME=best-effort
  WORKLOAD_SCALE_DIR="/mascli/templates/pod-templates/${WORKLOAD_SCALE_DIR_NAME}"
}

function config_pipeline_workload_scale() {
  # Change echo_h3 depending on where we call this func
  echo_h3 "Configure Scaling Profile"
  echo "The CLI supports three profiles out of the box, and allows you to define your own custom profile as well."
  echo "Make a selection from the list below. For more information about the profiles, see https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/"
  echo
  echo "1. Guaranteed"
  echo "2. Burstable (default)"
  echo "3. BestEffort"
  echo "4. Custom"
  echo

  prompt_for_number "Select Profile" MAS_SCALE_PROFILE_SELECTION 2

  case $MAS_SCALE_PROFILE_SELECTION in
  1)
    WORKLOAD_SCALE_PROFILE=Guaranteed
    set_workload_scale_envs
    ;;
  2)
    WORKLOAD_SCALE_PROFILE=Burstable
    ;;
  3)
    WORKLOAD_SCALE_PROFILE=BestEffort
    set_workload_scale_envs
    ;;
  4)
    prompt_for_input "Custom configurations directory" WORKLOAD_SCALE_DIR
    check_workload_scale_dir
    ;;
  *)
    echo_warning "Invalid selection. Choose between 1 and 4"
    exit 1
    ;;
  esac
  echo
}
