#!/bin/bash

function setup_mirror_registry() {
  echo
  echo_h2 "Configure Installation"

  prompt_for_input "Registry Namespace" REGISTRY_NAMESPACE "airgap-registry" && export REGISTRY_NAMESPACE
  prompt_for_input "Registry Storage Class" REGISTRY_STORAGE_CLASS "ibmc-block-gold" && export REGISTRY_STORAGE_CLASS
  prompt_for_input "Registry Storage Capacity" REGISTRY_STORAGE_CAPACITY "2000Gi" && export REGISTRY_STORAGE_CAPACITY
  prompt_for_input "Registry Service Type" REGISTRY_SERVICE_TYPE "loadbalancer" && export REGISTRY_SERVICE_TYPE

  echo
  echo_h2 "Configure Authentication"

  prompt_for_input "Mirror Registry Username" REGISTRY_USERNAME && export REGISTRY_USERNAME
  prompt_for_secret "Mirror Registry Password" REGISTRY_PASSWORD "Re-use saved registry password?" && export REGISTRY_PASSWORD

  prompt_for_confirm "Proceed with these settings" || exit 0

  echo
  echo_h2 "Run Installation"
  ansible-playbook ibm.mas_devops.deploy_private_registry
}
