#!/bin/bash

function update_help() {
  [[ -n "$1" ]] && echo_warning "$1"
  reset_colors
  cat << EOM
Usage:
  mas update [options]
Where ${COLOR_YELLOW}specified${TEXT_RESET} each option may also be defined by setting the appropriate environment variable.
When no options are specified on the command line, interactive-mode will be enabled by default.

Maximo Operator Catalog Selection (Required):
  -c, --catalog ${COLOR_YELLOW}MAS_CATALOG_VERSION${TEXT_RESET}     Maximo Operator Catalog Version (e.g. v8-221129)

Update Dependencies (Optional):
  --db2u-namespace ${COLOR_YELLOW}DB2_NAMESPACE${TEXT_RESET}          DB2 namespace where instances update will be performed
  --mongodb-namespace ${COLOR_YELLOW}MONGODB_NAMESPACE${TEXT_RESET}   Namespace where MongoCE operator and instance will be updated
  --mongodb-v5-upgrade ${COLOR_YELLOW}MONGODB_V5_UPGRADE${TEXT_RESET} Confirms that Mongo can be upgraded to version 5 if needed as part of the update
  --kafka-namespace ${COLOR_YELLOW}KAFKA_NAMESPACE${TEXT_RESET}       Namespace where Kafka operator and instance will be updated
  --kafka-provider ${COLOR_YELLOW}KAFKA_PROVIDER${TEXT_RESET}         Set Kafka provider. Supported options are 'redhat' (Red Hat AMQ Streams), or 'strimzi'

Other Commands:
      --no-confirm                      Launch the update without prompting for confirmation
  -h, --help                            Show this help message
EOM
  [[ -n "$1" ]] && exit 1 || exit 0
}

# Auto-detect Certificate Manager
# -----------------------------------------------------------------------------
# Validates the existance of installed IBM Certificate Manager in the target cluster
# If so, then set parameters to prepare the migration to Red Hat Certificate Manager
function validate_existing_cert_manager() {

  # We just check current MongoDB version and warn about Mongo upgrade if MAS catalog is more recent than January 2024
  MAS_CATALOG_DATE=${MAS_CATALOG_VERSION:3:6}

  if [[ $MAS_CATALOG_DATE -ge 240130 ]]; then
    # Lookup existing Certificate Manager instance
      if [ -z "$CERT_MANAGER_NAMESPACE" ]; then
        CERT_MANAGER_NAMESPACE=`oc get pods -A | grep cert-manager-cainjector | awk '{print $1}'`
      fi

    # Check that Certificate Manager instance is running in the cluster
      count=`echo $CERT_MANAGER_NAMESPACE | wc -w`
      if [ $count -eq 0 ]
      then
        CERT_MANAGER_ACTION=install
        CERT_MANAGER_PROVIDER=redhat
        echo -e "${COLOR_YELLOW}Certificate Manager is not installed yet! Red Hat Certificate Manager will be installed.${COLOR_RESET}"
    # Check that there's only one Certificate Manager instance running in the cluster
      elif [ $count -eq 1 ]
      then
      # if the running Certificate Manager is the one from IBM Cloud Pak Foundational Services, let users know it will be migrated to Red Hat
        if [ "$CERT_MANAGER_NAMESPACE" == "ibm-common-services" ]; then
          CERT_MANAGER_ACTION=install
          CERT_MANAGER_PROVIDER=redhat
          echo -e "${COLOR_YELLOW}Certificate Manager is currently running in namespace ${CERT_MANAGER_NAMESPACE}."
          echo -e "${COLOR_YELLOW}The existing Certificate Manager will be uninstalled and migrated to Red Hat Certificate Manager.${COLOR_RESET}"
        fi
      elif [ $count -ge 1 ]
      then
      # if multiple Certificate Manager instances, just alert user and skip Certificate Manager update
          echo -e "${COLOR_YELLOW}There are multiple instances of Certificate Manager running in the cluster.${COLOR_RESET}"
          echo -e "${COLOR_YELLOW}Make sure you just have one Certificate Manager instance running.${COLOR_RESET}"
          echo -e "${COLOR_YELLOW}Certificate Manager namespaces identified: $CERT_MANAGER_NAMESPACE${COLOR_RESET}"
      fi
    echo
  fi
}

# Auto-detect MongoDB
# -----------------------------------------------------------------------------
# Validates the existance of installed MongoDB Community Edition in the target cluster
# and prints a warning message if MongoDB is supposed to be upgraded

function validate_existing_mongo() {

  if [ -z "$MONGODB_NAMESPACE" ]; then
    MONGODB_NAMESPACE=`oc get mongodbcommunity.mongodbcommunity.mongodb.com -A -o jsonpath='{.items[0].metadata.namespace}' 2> /dev/null`
  fi

  # We just check current MongoDB version and warn about Mongo upgrade if MAS catalog is more recent than November 2023
  MAS_CATALOG_DATE=${MAS_CATALOG_VERSION:3:6}

  if [[ $MAS_CATALOG_DATE -ge 231128 ]]; then
    # Lookup existing MongoDb instance
    MONGODB_CURRENT_VERSION=`oc get mongodbcommunity.mongodbcommunity.mongodb.com -A -o jsonpath='{.items[0].status.version}' 2> /dev/null`
    MONGODB_REQUIRED_VERSION="5.0.21" # required version for Nov 2023 catalog
    
    # If existing MongoDb instance version is lower than the minimum version required, then let users know that Mongo will be upgraded
    if [ ! "$(printf '%s\n' "$MONGODB_REQUIRED_VERSION" "$MONGODB_CURRENT_VERSION" | sort -V | head -n1)" = "$MONGODB_REQUIRED_VERSION" ]; then
      echo
      echo -e "${COLOR_YELLOW}MongoDB Community Edition is currently running on version ${MONGODB_CURRENT_VERSION} and will be upgraded to version ${MONGODB_REQUIRED_VERSION}.${COLOR_RESET}"
      echo -e "${COLOR_YELLOW}It is recommended that you backup your MongoDB instance before proceeding:${COLOR_RESET}"
      echo -e "${COLOR_YELLOW}https://www.ibm.com/docs/en/mas-cd/continuous-delivery?topic=suite-backing-up-mongodb-maximo-application ${COLOR_RESET}"
      echo
      MONGODB_V5_UPGRADE=true
    fi
  fi
}

# Validate UDS to DRO Migration
# -----------------------------------------------------------------------------

function validate_dro_migration(){
  # warn about DRO migration if UDS is running and MAS catalog is January 2024 or newer
  MAS_CATALOG_DATE=${MAS_CATALOG_VERSION:3:6}

  if [[ $MAS_CATALOG_DATE -ge 240130 ]] || [[ $DRO_TEST == "true"]]; then
    # If Jan catalog is detected, set DRO_MIGRATION Flag to True
    UDS_NAMESPACE="ibm-common-services"
    UDS_CSV=`oc get csv | grep user-data-services  | awk '{print $1}'`
    UDS_STATUS=`oc get csv -n "${UDS_NAMESPACE}" "${UDS_CSV}" -o jsonpath='{.status.phase}'`
    if [[ $UDS_STATUS = *'Succeeded'* ]]; then
      DRO_MIGRATION="true"
      echo -e "${COLOR_YELLOW}UDS is currently running in namespace ${UDS_NAMESPACE}."
      echo -e "${COLOR_YELLOW}The existing UDS will be uninstalled and migrated to DRO (Data Reporter Operator).${COLOR_RESET}"
    fi
  else
    DRO_MIGRATION="false"
  fi

}
# Validate Selected Catalog
# -----------------------------------------------------------------------------
# Validates that the selected catalog version is one that is suitable to use
# based on the currently installed catalog source
#
# - You can't update to an older catalog source
# - The dynamic catalog can only be updated to the most recent static catalog
#
# Note: We don't currently support conversion from static to dynamic
#
function validate_update() {
  if [[ "$catalogVersion" != "" ]] && [[ "$catalogId" > "$MAS_CATALOG_VERSION" ]]; then
    echo
    if [[ "$catalogIsDynamic" == "true" ]];
      then echo_warning "Selected catalog is older than the currently installed catalog.  Dynamic catalog can only be updated to the latest static catalog ($MOST_RECENT_CATALOG)"
      else echo_warning "Selected catalog is older than the currently installed catalog.  Unable to update catalog from $catalogId to $MAS_CATALOG_VERSION"
    fi
    echo
    exit 1
  fi

  # Validates Red Hat Cerficate Manager migration only if January catalog or more recent used
  validate_existing_cert_manager

  # Validates MongoDB upgrade is confirmed while using November catalog
  MAS_CATALOG_DATE=${MAS_CATALOG_VERSION:3:6}
  if [[ $MAS_CATALOG_DATE -ge 231128 ]]; then # checks if MAS catalog >= November 2023
    if [[ -z "$NO_CONFIRM" ]] ; then # if 'mas update -c v8-231128-amd64', then we proceed and check existing mongo and warn user of the mongodb upgrade
      validate_existing_mongo
    else
      if [[ -z "$MONGODB_V5_UPGRADE" ]] ; then # if 'mas update -c v8-231128-amd64 --no-confirm' but no '--mongodb-v5-upgrade' then we fail as user must consent about the mongodb upgrade
        echo
        echo -e "${COLOR_RED}By choosing '$MAS_CATALOG_VERSION' catalog, you must confirm MongoDB upgrade to version 5.${TEXT_RESET}"
        echo -e "${COLOR_RED}Add '--mongodb-v5-upgrade' argument to the 'mas update' command in order to continue.${TEXT_RESET}"
        exit 1
      else # if 'mas update -c v8-231128-amd64 --mongodb-v5-upgrade --no-confirm' then we proceed and check existing mongo and warn user of the mongodb upgrade
        validate_existing_mongo
      fi
    fi
  fi

  # Validates UDS to DRO migration only if UDS is running and January catalog or more recent is used
  validate_dro_migration

  # Lookup for OCP console route
  if [[ -z "$OCP_CONSOLE_ROUTE" ]]; then
    OCP_CONSOLE_ROUTE=$(oc -n openshift-console get route console -o=jsonpath='{.spec.host}') # lookup ocp url regardless
  fi

}

# Inspect Installed Catalog
# -----------------------------------------------------------------------------
# Lookup details of the installed catalog source to determine:
#
# - Whether a dynamic or static catalog source is in use
# - The version of the catalog source in use
#
# This information is shown the user, along with a message indicating that
# this command would switch a dynamic catalog install to a static catalog install
# if they proceed.
#
# If we cannot determine the version of the catalog we show an error message
# but allow the install to proceed as this is not a fatal issue.
#
function show_current_catalog() {
  catalogDisplayName=$(oc -n openshift-marketplace get catalogsource ibm-operator-catalog -o yaml | yq -r ".spec.displayName")
  catalogImage=$(oc -n openshift-marketplace get catalogsource ibm-operator-catalog -o yaml | yq -r ".spec.image")

  echo
  echo_h2 "Review Installed Catalog"
  echo "${catalogDisplayName}"
  echo -e "   ${COLOR_CYAN}${TEXT_UNDERLINE}${catalogImage}"
  reset_colors

  if [[ "$catalogDisplayName" =~ .+(v8-[0-9]+-amd64) ]]; then
    # catalogId = v8-yymmdd-amd64
    # catalogVersion = yymmdd
    catalogId=$(sed -E "s/.+\\((v8-[0-9]+-amd64)\\)/\1/" <<< $catalogDisplayName)
    catalogVersion=$(sed -E "s/.+\\(v8-([0-9]+)-amd64\\)/\1/" <<< $catalogDisplayName)
    catalogIsDynamic=false
  elif [[ "$catalogDisplayName" =~ .+(v8-amd64) ]]; then
    catalogId=$MOST_RECENT_CATALOG
    catalogVersion=$(sed -E "s/.+\\(v8-([0-9]+)-amd64\\)/\1/" <<< $MOST_RECENT_CATALOG)
    catalogIsDynamic=true

    echo
    echo "Automatic catalog updates are currently enabled on this cluster, completing this update will switch to a manually managed catalog source"
    echo "For more information refer to: ${COLOR_CYAN}${TEXT_UNDERLINE}https://ibm-mas.github.io/cli/guides/choosing-the-right-catalog/"
    reset_colors
  else
    echo
    echo_warning "Unable to determine identity & version of currently installed ibm-maximo-operator-catalog"
  fi
}


# Perform non-interative update
# -----------------------------------------------------------------------------
function update_noninteractive() {
  detect_airgap
  while [[ $# -gt 0 ]]
  do
    key="$1"
    shift
    case $key in
      -c|--catalog)
        MAS_CATALOG_VERSION=$1 && shift
        ;;
      --db2u-namespace)
        DB2_NAMESPACE=$1 && shift
        ;;
      --mongodb-namespace)
        MONGODB_NAMESPACE=$1 && shift
        ;;
      --mongodb-v5-upgrade)
        MONGODB_V5_UPGRADE=true
        ;;
      --kafka-namespace)
        KAFKA_NAMESPACE=$1 && shift
        ;;
      --kafka-provider)
        KAFKA_PROVIDER=$1 && shift
        ;;
      --no-confirm)
        NO_CONFIRM=true
        ;;
      -h|--help)
        update_help
        ;;
      *)
        # unknown option
        echo -e "${COLOR_RED}Usage Error: Unsupported option \"${key}\"${TEXT_RESET}\n"
        update_help
        exit 1
        ;;
      esac
  done

  # Check all args have been set
  [[ -z "$MAS_CATALOG_VERSION" ]] && update_help "MAS_CATALOG_VERSION is not set"

  show_current_catalog
  validate_update
}


# Perform interative update
# -----------------------------------------------------------------------------
function update_interactive() {
  connect
  detect_airgap

  show_current_catalog

  echo
  echo_h2 "Select IBM Maximo Operator Catalog Version"
  choose_catalog_version
  echo
  validate_update

  # Auto-detect Db2
  # ---------------------------------------------------------------------------
  if [ -z "$DB2_NAMESPACE" ]; then
    DB2_NAMESPACE=`oc get db2ucluster.db2u.databases.ibm.com -A -o jsonpath='{.items[0].metadata.namespace}' 2> /dev/null`
  fi

  oc get Operator db2u-operator.ibm-common-services > /dev/null 2>&1
  if [ "$?" == "0" ]; then
    prompt_for_input "Db2u Universal Operator detected. Db2u namespace to update?" DB2_NAMESPACE "db2u"
    echo
  fi

  # Detect Kafka in cluster and set namespace
  # Auto-detect Kafka
  # ---------------------------------------------------------------------------
  if [ -z "$KAFKA_NAMESPACE" ]; then
    KAFKA_NAMESPACE=`oc get Kafka.kafka.strimzi.io -A -o jsonpath='{.items[0].metadata.namespace}' 2> /dev/null`
  fi

  if [ -z "$KAFKA_PROVIDER" ] && [ -n "$KAFKA_NAMESPACE" ]; then
    KAFKA_OPERATOR=`oc get subscription -n $KAFKA_NAMESPACE -o jsonpath='{.items[0].spec.name}' 2> /dev/null`
    if [ "$?" == "0" ]; then
      if [ "$KAFKA_OPERATOR" == "amq-streams" ]; then
        KAFKA_PROVIDER="redhat"
        KAFKA_PROVIDER_NAME="AMQ Streams) ........................"
      elif [ "$KAFKA_OPERATOR" == "strimzi-kafka-operator" ]; then
        KAFKA_PROVIDER="strimzi"
        KAFKA_PROVIDER_NAME="Strimzi) ............................"
      fi
    fi
  fi
}

# Main function
# -----------------------------------------------------------------------------
function update() {
  # Take the first parameter off (it will be "update")
  shift
  if [[ $# -gt 0 ]]; then
    update_noninteractive "$@"
  else
    update_interactive
  fi

  export MAS_CATALOG_VERSION
  export DB2_NAMESPACE
  export MONGODB_NAMESPACE
  export MONGODB_STORAGE_CLASS
  export MONGODB_V5_UPGRADE
  export KAFKA_NAMESPACE
  export KAFKA_PROVIDER
  export CERT_MANAGER_PROVIDER
  export CERT_MANAGER_ACTION

  echo_h2 "Review Settings"

  echo "${TEXT_DIM}"
  echo_h4 "IBM Operator Catalog" "    "
  echo_reset_dim "Current Catalog Version .................... ${COLOR_MAGENTA}${catalogId:-unknown}${TEXT_RESET}"
  echo_reset_dim "Updated Catalog Version .................... ${COLOR_MAGENTA}${MAS_CATALOG_VERSION}${TEXT_RESET}"
  echo "${TEXT_DIM}"
  echo_h4 "Updates" "    "
  echo_reset_dim "IBM Maximo Application Suite ............... ${COLOR_GREEN}Yes (all MAS instances)${TEXT_RESET}"
  echo_reset_dim "IBM Cloud Pak Foundational Services ........ ${COLOR_GREEN}Yes (ibm-common-services)${TEXT_RESET}"

  # Certificate Manager
  if [ "$CERT_MANAGER_PROVIDER" == "redhat" ]; then
    echo_reset_dim "Certificate Manager ........................ ${COLOR_GREEN}Yes (cert-manager)"
  else
    echo_reset_dim "Certificate Manager ........................ ${COLOR_RED}No${TEXT_RESET}"
  fi

  # Detect OCS/ODF Storage Cluster in cluster and set action
  oc get StorageCluster -A > /dev/null 2>&1
  if [ "$?" == "0" ]; then
    echo_reset_dim "OpenShift Data Foundation  ................. ${COLOR_GREEN}Yes${TEXT_RESET}"
  else
    echo_reset_dim "OpenShift Data Foundation  ................. ${COLOR_RED}No${TEXT_RESET}"
  fi

  # IBM Db2
  if [ "$DB2_NAMESPACE" != "" ]; then
    echo_reset_dim "IBM Db2 Universal Operator ................. ${COLOR_GREEN}Yes ($DB2_NAMESPACE)${TEXT_RESET}"
  else
    echo_reset_dim "IBM Db2 Universal Operator ................. ${COLOR_RED}No${TEXT_RESET}"
  fi

  # MongoDB Community Edition
  if [ "$MONGODB_NAMESPACE" != "" ]; then
    echo_reset_dim "MongoDb Community Edition .................. ${COLOR_GREEN}Yes ($MONGODB_NAMESPACE)${TEXT_RESET}"
  else
    echo_reset_dim "MongoDb Community Edition .................. ${COLOR_RED}No${TEXT_RESET}"
  fi

  # Kafka (Strimzi/AMQ Streams)
  if [ "$KAFKA_NAMESPACE" != "" ]; then
    echo_reset_dim "Kafka ($KAFKA_PROVIDER_NAME ${COLOR_GREEN}Yes ($KAFKA_NAMESPACE)${TEXT_RESET}"
  else
    echo_reset_dim "Kafka ...................................... ${COLOR_RED}No${TEXT_RESET}"
  fi

  # In SLS 3.8.0 registry was changed to icr.io/cpopen, however
  # when updating from a previous version it would not automatically
  # change the value from cp.icr.io/cp hence we need to patch it
  if [[ "$MAS_CATALOG_VERSION" == "v8-230926-amd64" ]]; then
    UPDATE_SLS_REGISTRY="true"
  else
    UPDATE_SLS_REGISTRY="false"
  fi

  echo
  reset_colors
  if [[ "$NO_CONFIRM" != "true" ]]; then
    prompt_for_confirm "Proceed with these settings" || exit 0
  fi

  echo
  echo_h2 "Launch Update"

  # Create namespace, install MAS Tekton definitions, configure RBAC
  pipelines_install_tasks_shared_namespace || exit 1

  # Replace ALL environment variables in templates
  eval "echo \"$(cat $CLI_DIR/templates/pipelinerun-update.yaml)\"" > $CONFIG_DIR/pipelinerun-update.yaml

  # Start pipeline execution
  oc -n mas-pipelines create -f $CONFIG_DIR/pipelinerun-update.yaml &>> $LOGFILE || exit 1
  echo -e "${COLOR_GREEN}Update started successfully${TEXT_RESET}"
  echo -e "\nView progress:\n  ${COLOR_CYAN}${TEXT_UNDERLINE}https://${OCP_CONSOLE_ROUTE}/pipelines/ns/mas-pipelines${TEXT_RESET}${TEXT_RESET}"
  echo

}
