---
apiVersion: v1
kind: Namespace
metadata:
  name: mas-{{ mas_instance_id }}-core
---
apiVersion: v1
kind: Namespace
metadata:
  name: mas-{{ mas_instance_id }}-pipelines
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: eck
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana5
---
apiVersion: v1
kind: Namespace
metadata:
  name: ibm-sls
---
apiVersion: v1
kind: Namespace
metadata:
  name: sls-{{ mas_instance_id }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: mongoce
---
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-pipelines
---
apiVersion: v1
kind: Namespace
metadata:
  name: db2u
---
apiVersion: v1
kind: Namespace
metadata:
  name: mas-{{ mas_instance_id }}-manage
---
apiVersion: v1
kind: Namespace
metadata:
  name: mas-{{ mas_instance_id }}-monitor
---
apiVersion: v1
kind: Namespace
metadata:
  name: mas-{{ mas_instance_id }}-health
---
apiVersion: v1
kind: Namespace
metadata:
  name: mas-{{ mas_instance_id }}-predict
---
apiVersion: v1
kind: Namespace
metadata:
  name: mas-{{ mas_instance_id }}-assist
---
apiVersion: v1
kind: Namespace
metadata:
  name: mas-{{ mas_instance_id }}-visualinspection
---
apiVersion: v1
kind: Namespace
metadata:
  name: mas-{{ mas_instance_id }}-iot
