#!/bin/bash

# This file contains all the code that needs to change whenever a new catalog is released
# Make sure to update every function in this file when adding support for a new catalog

# This is used when determining whether a user can convert from the dynamic catalog to
# a static catalog.  We only support converting from v8-amd64 to the latest static catalog
# because any other change would be a downgrade and would result in the HEAD bundle in
# our packages regressing, which would confuse OLM.
MOST_RECENT_CATALOG=v8-240405-amd64

# Choose a catalog only
# -----------------------------------------------------------------------------
# Currently only used in the mas update function.  The user does not need to select
# the version of MAS, only the version of the catalog to update to.
function choose_catalog_version() {
  echo -e "${COLOR_YELLOW}Select MAS Catalog:"
  echo "  1) April 05 2024 Update (MAS 8.11.9 & 8.10.11)"
  echo "  2) February 27 2024 Update (MAS 8.11.7 & 8.10.10)"
  echo "  3) January 30 2024 Update (MAS 8.11.6 & 8.10.9)"
  echo "  4) December 28 2023 Update (MAS 8.11.5 & 8.10.8)"
  reset_colors

  echo
  prompt_for_input "Select Catalog Version" MAS_CATALOG_SELECTION "1"

  case $MAS_CATALOG_SELECTION in
    1)
      MAS_CATALOG_VERSION=v8-240405-amd64
      ;;
    2)
      MAS_CATALOG_VERSION=v8-240227-amd64
      ;;
    3)
      MAS_CATALOG_VERSION=v8-240130-amd64
      ;;
    4)
      MAS_CATALOG_VERSION=v8-231228-amd64
      ;;
    *)
      echo_warning "Invalid selection"
      exit 1
      ;;
  esac
}

#TODO: UPDATE BELOW

# Choose a catalog and the MAS channel
# -----------------------------------------------------------------------------
# Currently only in the mas install and mirror-images functions.  The user must
# select both a version of the catalog and a version of MAS within the catalog.
function choose_mas_version() {
  b="│"
  header=" ┌───┬──────────────┬────────┬────────┬───────┬────────┬─────────┬───────────┬─────────┬────────────┐"
  divider=" ├───┼──────────────┼────────┼────────┼───────┼────────┼─────────┼───────────┼─────────┼────────────┤"
  footer=" └───┴──────────────┴────────┴────────┴───────┴────────┴─────────┴───────────┴─────────┴────────────┘"
  echo ""
  echo -e "$header"
  echo -e " $b # $b Catalog      $b  Core   $b Assist $b   IoT   $b Manage $b Monitor $b Optimizer $b Predict $b Inspection $b"
  echo -e "$divider"
  echo -e " $b 1 $b Apr 05 2024  $b 8.11.9  $b 8.8.2  $b 8.8.6   $b 8.7.6  $b 8.11.5  $b   8.5.3   $b  8.9.2  $b   8.9.1    $b"
  echo -e " $b 2 $b              $b 8.10.11 $b 8.7.3  $b 8.7.10  $b 8.6.11 $b 8.10.8  $b   8.4.4   $b  8.8.2  $b   8.8.2    $b"
  echo -e "$divider"
  echo -e " $b 3 $b Feb 27 2024  $b 8.11.7  $b 8.8.2  $b 8.8.5   $b 8.7.5  $b 8.11.4  $b   8.5.2   $b  8.9.2  $b   8.9.1    $b"
  echo -e " $b 4 $b              $b 8.10.10 $b 8.7.3  $b 8.7.9   $b 8.6.10 $b 8.10.7  $b   8.4.3   $b  8.8.2  $b   8.8.2    $b"
  echo -e "$divider"
  echo -e " $b 5 $b Jan 30 2024  $b 8.11.6  $b 8.8.1  $b 8.8.4   $b 8.7.4  $b 8.11.3  $b   8.5.1   $b  8.9.1  $b   8.9.0    $b"
  echo -e " $b 6 $b              $b 8.10.9  $b 8.7.2  $b 8.7.8   $b 8.6.9  $b 8.10.6  $b   8.4.2   $b  8.8.2  $b   8.8.1    $b"
  echo -e "$divider"
  echo -e " $b 7 $b Dec 28 2023  $b 8.11.5  $b 8.8.1  $b 8.8.3   $b 8.7.3  $b 8.11.2  $b   8.5.1   $b  8.9.0  $b   8.9.0    $b"
  echo -e " $b 8 $b              $b 8.10.8  $b 8.7.2  $b 8.7.7   $b 8.6.8  $b 8.10.6  $b   8.4.2   $b  8.8.2  $b   8.8.1    $b"
  echo -e "$divider"
  reset_colors
  echo
  prompt_for_input "Select Catalog Source" MAS_CHANNEL_SELECTION "1"

  case $MAS_CHANNEL_SELECTION in
    # April 2024
    1)
      MAS_CHANNEL=8.11.x
      MAS_CATALOG_VERSION=v8-240405-amd64
      ;;
    2)
      MAS_CHANNEL=8.10.x
      MAS_CATALOG_VERSION=v8-240405-amd64
      ;;
    # February 2024
    3)
      MAS_CHANNEL=8.11.x
      MAS_CATALOG_VERSION=v8-240227-amd64
      ;;
    4)
      MAS_CHANNEL=8.10.x
      MAS_CATALOG_VERSION=v8-240227-amd64
      ;;
    # January 2024
    5)
      MAS_CHANNEL=8.11.x
      MAS_CATALOG_VERSION=v8-240130-amd64
      ;;
    6)
      MAS_CHANNEL=8.10.x
      MAS_CATALOG_VERSION=v8-240130-amd64
      ;;
    # December 2023
    7)
      MAS_CHANNEL=8.11.x
      MAS_CATALOG_VERSION=v8-231228-amd64
      ;;
    8)
      MAS_CHANNEL=8.10.x
      MAS_CATALOG_VERSION=v8-231228-amd64
      ;;
    # Invalid Selection
    *)
      echo_warning "Invalid selection"
      exit 1
      ;;
  esac
}

# Determine whether UDS or DRO Operator to use
# -----------------------------------------------------------------------------
# We automatically select the UDS or DRO operator to install in the
# cluster based on the version of the catalog that is being used
function uds_action_selection() {
  MAS_CATALOG_DATE=${MAS_CATALOG_VERSION:3:6}
  if [[ ($MAS_CATALOG_DATE -ge 240227) || ($MAS_CATALOG_DATE == "amd64") || ($MAS_CATALOG_DATE == "master") ]]; then
    UDS_ACTION="install-dro"
  else
    UDS_ACTION="install"
  fi
}

# Determine the version of Db2u Operator to use
# -----------------------------------------------------------------------------
# We automatically select the version of the Db2u operator to install in the
# cluster based on the version of the catalog that is being used
function db2_channel_selection() {
  case $MAS_CATALOG_VERSION in
    # Db2 Channel selection
    # -------------------------------------------------------------------------
    v8-amd64|v8-231228-amd64|v8-240130-amd64|v8-240227-amd64|v8-240326-amd64|v8-240405-amd64)
      DB2_CHANNEL=v110508.0
      ;;
    v8-230111-amd64|v8-230217-amd64|v8-230314-amd64|v8-230328-amd64)
      DB2_CHANNEL=v2.2
      ;;
    *)
      DB2_CHANNEL="" # The default channel will be used
      ;;
  esac
}


# Determine the version of Cloud Pak for Data to use
# -----------------------------------------------------------------------------
# We automatically select the version of CP4D to install in the
# cluster based on the version of the catalog that is being used
function cp4d_channel_selection() {
  case $MAS_CATALOG_VERSION in
    # CP4D v4.6.6 was added in the September 2023 catalog update
    v8-amd64|v8-230926-amd64|v8-231004-amd64|v8-231031-amd64|v8-231128-amd64|v8-231228-amd64|v8-240130-amd64|v8-240227-amd64|v8-240326-amd64|v8-240405-amd64)
      CP4D_VERSION=4.6.6
      ;;
    # CP4D v4.6.4 was added in the June 2023 catalog update
    v8-230616-amd64|v8-230627-amd64|v8-230721-amd64|v8-230725-amd64|v8-230829-amd64)
      CP4D_VERSION=4.6.4
      ;;
    # CP4D v4.6.3 was added in the April 2023 catalog update
    v8-230414-amd64|v8-230518-amd64|v8-230526-amd64)
      CP4D_VERSION=4.6.3
      ;;
    # CP4D v4.6.0 was added in the February 2023 catalog update
    v8-230217-amd64|v8-230314-amd64)
      CP4D_VERSION=4.6.0
      ;;
    # Versions of the catalog older than February 2023 support up to CP4D v4.5.2
    v8-230111-amd64)
      CP4D_VERSION=4.5.2
      ;;
    *)
      echo
      echo "One or more selected applications require Cloud Pak for Data"
      prompt_for_input 'Cloud Pak for Data product version' CP4D_VERSION "4.6.4"
      ;;
  esac
}

# Determine the prompts for SLS
# -----------------------------------------------------------------------------
# We automatically select the version of SLS to install in the
# cluster based on the version of the catalog that is being used
# We use the following vars to make version specific prompts
function sls_prompt_selection() {
  case $MAS_CATALOG_VERSION in
    # SLS 3.8.x and up
    v8-amd64|v8-230926-amd64|v8-231004-amd64|v8-231031-amd64|v8-231128-amd64|v8-231228-amd64|v8-240130-amd64|v8-240227-amd64|v8-240326-amd64|v8-240405-amd64)
      SLS_PROMPT_LICENSE_ID="false"
      SLS_PROMPT_ICR_CP="false"
      ;;
    # SLS 3.7.0
    v8-230518-amd64|v8-230627-amd64|v8-230725-amd64|v8-230829-amd64)
      SLS_PROMPT_LICENSE_ID="false"
      SLS_PROMPT_ICR_CP="true"
      ;;
    *)
      SLS_PROMPT_LICENSE_ID="true"
      SLS_PROMPT_ICR_CP="true"
      ;;
  esac
}

# Determine the Certificate Manager provider to use
# -----------------------------------------------------------------------------
# With January 2024 catalog source, Red Hat Certificate Manager
# will be used as default Certificate Manager provider
# Older catalog source will continue to use IBM Certificate Manager
# provided by IBM Cloud Pak Foundational Services

function cert_manager_selection() {
  case $MAS_CATALOG_VERSION in
    # Cert-Manager Channel selection
    # -------------------------------------------------------------------------
    v8-amd64|v8-240130-amd64|v8-240227-amd64|v8-240326-amd64|v8-240405-amd64)
      CERT_MANAGER_PROVIDER=redhat
      CERT_MANAGER_ACTION=install
      ;;
    *)
      CERT_MANAGER_PROVIDER=ibm
      CERT_MANAGER_ACTION=install
      ;;
  esac
}