#!/bin/bash

# This file contains all the code that needs to change whenever a new catalog is released
# Make sure to update every function in this file when adding support for a new catalog

# This is used when determining whether a user can convert from the dynamic catalog to
# a static catalog.  We only support converting from v8-amd64 to the latest static catalog
# because any other change would be a downgrade and would result in the HEAD bundle in
# our packages regressing, which would confuse OLM.
MOST_RECENT_CATALOG=v8-231031-amd64

# Choose a catalog only
# -----------------------------------------------------------------------------
# Currently only used in the mas update function.  The user does not need to select
# the version of MAS, only the version of the catalog to update to.
function choose_catalog_version() {
  echo -e "${COLOR_YELLOW}Select MAS Catalog:"
  echo "  1) October 31 2023 Update (MAS 8.11.2 & 8.10.6)"
  echo "  2) October 04 2023 Update (MAS 8.11.1 & 8.10.5)"
  echo "  3) August 29 2023 Update (MAS 8.10.4 & 8.9.9)"
  reset_colors
  echo
  echo "Note: Due to a severe bug in the 8.11.0 version of the Core Platform we have released an important update (8.11.1) and the 4 October catalog has replaced the 26 September catalog option."

  echo
  prompt_for_input "Select Catalog Version" MAS_CATALOG_SELECTION "1"

  case $MAS_CATALOG_SELECTION in
    1)
      MAS_CATALOG_VERSION=v8-231031-amd64
      ;;
    2)
      MAS_CATALOG_VERSION=v8-231004-amd64
      ;;
    3)
      MAS_CATALOG_VERSION=v8-230829-amd64
      ;;
    *)
      echo_warning "Invalid selection"
      exit 1
      ;;
  esac
}


# Choose a catalog and the MAS channel
# -----------------------------------------------------------------------------
# Currently only in the mas install and mirror-images functions.  The user must
# select both a version of the catalog and a version of MAS within the catalog.
function choose_mas_version() {
  echo ""
  echo " ┌───┬──────────────┬────────┬──────────────────────────────────────────────────────────────────────┐"
  echo " │ # │ Catalog      │  Core  │ Assist |  IoT  | Manage | Monitor | Optimizer | Predict | Inspection |"
  echo " ├───┼──────────────┼────────┼────────┤───────┼────────┼─────────┼───────────┼─────────┼────────────┤"
  echo " │ 1 │ Oct 31 2023  | 8.11.2 │ 8.8.1  | 8.8.1 | 8.7.1  | 8.11.1  |   8.5.0   |  8.9.0  |   8.9.0    |"
  echo " │ 2 │              │ 8.10.6 │ 8.7.2  | 8.7.5 | 8.6.6  | 8.10.4  |   8.4.1   |  8.8.2  |   8.8.1    |"
  echo " ├───┼──────────────┼────────┼────────┤───────┼────────┼─────────┼───────────┼─────────┼────────────┤"
  echo " │ 3 │ Oct 04 2023  | 8.11.1 │ 8.8.0  | 8.8.0 | 8.7.0  | 8.11.0  |   8.5.0   |  8.9.0  |   8.9.0    |"
  echo " │ 4 │              │ 8.10.5 │ 8.7.2  | 8.7.4 | 8.6.5  | 8.10.4  |   8.4.1   |  8.8.2  |   8.8.1    |"
  echo " ├───┼──────────────┼────────┼────────┤───────┼────────┼─────────┼───────────┼─────────┼────────────┤"
  echo " │ 5 │ Aug 29 2023  | 8.10.4 │ 8.7.2  | 8.7.4 | 8.6.4  | 8.10.4  |   8.4.1   |  8.8.2  |   8.8.1    |"
  echo " │ 6 │              │ 8.9.9  │ 8.6.5  | 8.6.9 | 8.5.8  | 8.9.6   |   8.3.3   |  8.7.2  |   8.7.1    |"
  echo " ├───┼──────────────┼────────┼────────┤───────┼────────┼─────────┼───────────┼─────────┼────────────┤"
  reset_colors
  echo
  echo "Note: Due to a breaking change introduced to a package in the Red Hat Certified Operator Catalog in July 2023 we can not currently recommend the use of any catalogs prior to the July 21 release, which contains critical compatibility updates to IBM User Data Services.  If you need to use older catalogs you can use an earlier release of this CLI, but may face issues when used in conjunction with the latest versions of the Red Hat Operator Catalogs."
  echo
  prompt_for_input "Select Catalog Source" MAS_CHANNEL_SELECTION "1"

  case $MAS_CHANNEL_SELECTION in
    # October 2023
    1)
      MAS_CHANNEL=8.11.x
      MAS_CATALOG_VERSION=v8-231031-amd64
      ;;
    2)
      MAS_CHANNEL=8.10.x
      MAS_CATALOG_VERSION=v8-231031-amd64
      ;;
    3)
      MAS_CHANNEL=8.11.x
      MAS_CATALOG_VERSION=v8-231004-amd64
      ;;
    4)
      MAS_CHANNEL=8.10.x
      MAS_CATALOG_VERSION=v8-231004-amd64
      ;;
    # August 2023
    5)
      MAS_CHANNEL=8.10.x
      MAS_CATALOG_VERSION=v8-230829-amd64
      ;;
    6)
      MAS_CHANNEL=8.9.x
      MAS_CATALOG_VERSION=v8-230829-amd64
      ;;

    # Invalid Selection
    *)
      echo_warning "Invalid selection"
      exit 1
      ;;
  esac
}

# Determine whether UDS or DRO Operator to use
# -----------------------------------------------------------------------------
# We automatically select the UDS or DRO operator to install in the
# cluster based on the version of the catalog that is being used
# TODO: Need to know the latest catalog version name
function uds_dro_selection() {
  case $MAS_CATALOG_VERSION in
    # UDS/DRO selection
    # -------------------------------------------------------------------------
    v8-240111-amd64)
      BAS_PROVIDER="DRO"
      ;;
    *)
      BAS_PROVIDER="UDS" # The default channel will be used
      ;;
  esac
}

# Determine the version of Db2u Operator to use
# -----------------------------------------------------------------------------
# We automatically select the version of the Db2u operator to install in the
# cluster based on the version of the catalog that is being used
function db2_channel_selection() {
  case $MAS_CATALOG_VERSION in
    # Db2 Channel selection
    # -------------------------------------------------------------------------
    v8-amd64|v8-230414-amd64|v8-230518-amd64|v8-230526-amd64|v8-230616-amd64|v8-230627-amd64|v8-230721-amd64|v8-230725-amd64|v8-230829-amd64|v8-230926-amd64|v8-231004-amd64|v8-231031-amd64)
      DB2_CHANNEL=v110508.0
      ;;
    v8-230111-amd64|v8-230217-amd64|v8-230314-amd64|v8-230328-amd64)
      DB2_CHANNEL=v2.2
      ;;
    *)
      DB2_CHANNEL="" # The default channel will be used
      ;;
  esac
}


# Determine the version of Cloud Pak for Data to use
# -----------------------------------------------------------------------------
# We automatically select the version of CP4D to install in the
# cluster based on the version of the catalog that is being used
function cp4d_channel_selection() {
  case $MAS_CATALOG_VERSION in
    # CP4D v4.6.6 was added in the September 2023 catalog update
    v8-amd64|v8-230926-amd64|v8-231004-amd64|v8-231031-amd64)
      CP4D_VERSION=4.6.6
      ;;
    # CP4D v4.6.4 was added in the June 2023 catalog update
    v8-230616-amd64|v8-230627-amd64|v8-230721-amd64|v8-230725-amd64|v8-230829-amd64)
      CP4D_VERSION=4.6.4
      ;;
    # CP4D v4.6.3 was added in the April 2023 catalog update
    v8-230414-amd64|v8-230518-amd64|v8-230526-amd64)
      CP4D_VERSION=4.6.3
      ;;
    # CP4D v4.6.0 was added in the February 2023 catalog update
    v8-230217-amd64|v8-230314-amd64)
      CP4D_VERSION=4.6.0
      ;;
    # Versions of the catalog older than February 2023 support up to CP4D v4.5.2
    v8-230111-amd64)
      CP4D_VERSION=4.5.2
      ;;
    *)
      echo
      echo "One or more selected applications require Cloud Pak for Data"
      prompt_for_input 'Cloud Pak for Data product version' CP4D_VERSION "4.6.4"
      ;;
  esac
}

# Determine the prompts for SLS
# -----------------------------------------------------------------------------
# We automatically select the version of SLS to install in the
# cluster based on the version of the catalog that is being used
# We use the following vars to make version specific prompts
function sls_prompt_selection() {
  case $MAS_CATALOG_VERSION in
    # SLS 3.8.x and up
    v8-amd64|v8-230926-amd64|v8-231004-amd64|v8-231031-amd64)
      SLS_PROMPT_LICENSE_ID="false"
      SLS_PROMPT_ICR_CP="false"
      ;;
    # SLS 3.7.0
    v8-230518-amd64|v8-230627-amd64|v8-230725-amd64|v8-230829-amd64)
      SLS_PROMPT_LICENSE_ID="false"
      SLS_PROMPT_ICR_CP="true"
      ;;
    *)
      SLS_PROMPT_LICENSE_ID="true"
      SLS_PROMPT_ICR_CP="true"
      ;;
  esac
}