#!/bin/bash

# when SNO_MODE is detected, we have a couple of parameters that need to be set.
function install_config_sno() {
  if [[ "$SNO_MODE" == "true" ]]; then
    echo ""
    # SNO Mode -- Set environment variables MONGODB_REPLICAS=1
    echo_highlight "Single Node OpenShift detected"
    export MONGODB_REPLICAS=1
    export MONGODB_CPU_REQUESTS=500m
    export MAS_APP_SETTINGS_AIO_FLAG=false
    export DB2_CPU_REQUESTS=300m ##default value is 2000m
    export DB2_META_STORAGE_ACCESSMODE=ReadWriteOnce
    export DB2_BACKUP_STORAGE_ACCESSMODE=ReadWriteOnce
    export DB2_META_STORAGE_ACCESSMODE=ReadWriteOnce
    export DB2_BACKUP_STORAGE_ACCESSMODE=ReadWriteOnce
    export DB2_DATA_STORAGE_ACCESSMODE=ReadWriteOnce
    export DB2_LOGS_STORAGE_ACCESSMODE=ReadWriteOnce
  fi
}
