#!/bin/bash

function install_pipelinerun_create() {
  echo
  echo_h2 "Launch Installation"
  # Start pipeline execution
  oc -n mas-$MAS_INSTANCE_ID-pipelines create -f $CONFIG_DIR/pipelinerun-$MAS_INSTANCE_ID.yaml &>> $LOGFILE || exit 1
  echo -e "${COLOR_GREEN}Installation started successfully${TEXT_RESET}"
  echo -e "\nView progress:\n  ${COLOR_CYAN}${TEXT_UNDERLINE}https://${OCP_CONSOLE_ROUTE}/pipelines/ns/mas-$MAS_INSTANCE_ID-pipelines${TEXT_RESET}${TEXT_RESET}"
  echo
}
