#!/bin/bash


function install_config_additional_configs() {
  if [[ -z "$NON_INTERACTIVE" ]]; then
    echo
    echo_h2 "Additional Configuration"
    echo "${TEXT_DIM}Additional resource definitions can be applied to the OpenShift Cluster during the MAS configuration step."
    echo "The primary purpose of this is to apply configuration for Maximo Application Suite itself, but you can use this to deploy ANY additional resource into your cluster."
    echo
    reset_colors

    if [[ -z "$LOCAL_MAS_CONFIG_DIR_ALREADY_CHOSEN" ]]; then
      # Ask the user if they want to load additional configs
      if prompt_for_confirm "Use additional configurations?"; then
        # Select local MAS_CONFIG_DIR
        prompt_for_input "+ Local config directory" LOCAL_MAS_CONFIG_DIR && export LOCAL_MAS_CONFIG_DIR
        echo
        use_additional_configs=yes
        if [[ ! -d "$LOCAL_MAS_CONFIG_DIR" ]]; then
          echo_warning "Error: The directory $LOCAL_MAS_CONFIG_DIR does not exist"
          if prompt_for_confirm "Create directory $LOCAL_MAS_CONFIG_DIR instead?"; then
            mkdir $LOCAL_MAS_CONFIG_DIR
            echo "Directory $LOCAL_MAS_CONFIG_DIR has been created"
            echo
          else
            exit 1
          fi
        fi
      fi
    else
      # If the user has already generated a config then we will lose additional configs
      use_additional_configs=yes
    fi
  fi

  if [[ "$use_additional_configs" == "yes" ]]; then
    ADDITIONAL_CONFIG_FILES=$LOCAL_MAS_CONFIG_DIR/*.yaml
    if [ "$ADDITIONAL_CONFIG_FILES" == "" ]; then
      echo_warning "No configuration files (*.yaml) were found in $LOCAL_MAS_CONFIG_DIR"
      exit 1
    fi

    echo "The following additional configurations will be applied:"
    for FILE in $ADDITIONAL_CONFIG_FILES; do
      echo " - $(basename $FILE)"
    done

    echo
    if [[ "$NO_CONFIRM" != true ]]; then
      # if NO_CONFIRM is not true, prompt to confirm configuration files to apply
      if prompt_for_confirm "Are these the correct configuration files to apply?"; then
        COPY_ADDITIONAL_CONFIGS=true
      else
        echo_warning "Additional configuration files were not confirmed! Aborting ..."
        exit 0
      fi
    else
      # if NO_CONFIRM is true, no need to prompt to confirm
      COPY_ADDITIONAL_CONFIGS=true
    fi
    if [[ "$COPY_ADDITIONAL_CONFIGS" == true ]]; then
      cp $CLI_DIR/templates/additional-configs.yaml $CONFIG_DIR/additional-configs-$MAS_INSTANCE_ID.yaml
      python3 $CLI_DIR/tools/cfgmgr add $CONFIG_DIR/additional-configs-$MAS_INSTANCE_ID.yaml $LOCAL_MAS_CONFIG_DIR
    fi
  else
    LOCAL_MAS_CONFIG_DIR=""
  fi
}