CREATE TABLESPACE "TRIDATA_DATA"
DATAFILE '/u01/app/oracle/oradata/ORCL/TRIDATA_DATA_01.dbf'
SIZE 4096M AUTOEXTEND ON
NEXT 256M MAXSIZE UNLIMITED
LOGGING EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO
;
-- from OEM creating a tablespace for TRIRIGA 4GB initial size, extend 256MB unlimited file size
CREATE TABLESPACE "TRIDATA_INDX"
DATAFILE '/u01/app/oracle/oradata/ORCL/TRIDATA_INDX_01.dbf'
SIZE 4096M AUTOEXTEND ON
NEXT 256M MAXSIZE UNLIMITED
LOGGING EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO
;