CREATE USER $dbuser$ IDENTIFIED BY $dbpassword$
  DEFAULT TABLESPACE TRIDATA_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT;
ALTER USER  $dbuser$ QUOTA UNLIMITED ON TRIDATA_DATA;
ALTER USER  $dbuser$ QUOTA UNLIMITED ON TRIDATA_INDX;

GRANT ANALYZE ANY TO $dbuser$;
GRANT CREATE VIEW TO $dbuser$;
GRANT CREATE TABLE TO $dbuser$;
GRANT ALTER SESSION TO $dbuser$;
GRANT CREATE SESSION TO $dbuser$;
GRANT CREATE SYNONYM TO $dbuser$;
GRANT CREATE TRIGGER TO $dbuser$;
GRANT CREATE SEQUENCE TO $dbuser$;
GRANT CREATE PROCEDURE TO $dbuser$;
GRANT DROP PUBLIC SYNONYM TO $dbuser$;
GRANT CREATE PUBLIC SYNONYM TO $dbuser$;
GRANT CONNECT TO $dbuser$;

ALTER USER $dbuser$ DEFAULT ROLE CONNECT;