#!/bin/bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

NAMESPACE=$1
OUTPUT_DIR=$2

# Collect Kubernetes Resources
# -----------------------------------------------------------------------------
for RESOURCE in mongodbcommunity pvc statefulset
do
  $DIR/mg-collect-resources -n $NAMESPACE -r $RESOURCE -d $OUTPUT_DIR/resources
done

$DIR/mg-collect-pods $NAMESPACE true $OUTPUT_DIR/resources

exit 0
