#!/bin/bash
set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

NAMESPACE=$1
OUTPUT_DIR=$2

# Collect Reconcile Logs
# -----------------------------------------------------------------------------
echo_h4 "Collect Reconcile Logs"
# Main Operator
$DIR/mg-collect-reconcile-logs $NAMESPACE control-plane ibm-mas-predict $OUTPUT_DIR

# Truststore
$DIR/mg-collect-reconcile-logs $NAMESPACE operator ibm-truststore-mgr $OUTPUT_DIR

# Aiexpts
$DIR/mg-collect-reconcile-logs $NAMESPACE app aiexpts-service $OUTPUT_DIR

# Mat service
$DIR/mg-collect-reconcile-logs $NAMESPACE io.kompose.service mat-service $OUTPUT_DIR

# Predict API
$DIR/mg-collect-reconcile-logs $NAMESPACE mas.ibm.com/appType predict-api $OUTPUT_DIR

# Workspace Operator
$DIR/mg-collect-reconcile-logs $NAMESPACE mas.ibm.com/appType entitymgr-ws-operator $OUTPUT_DIR

exit 0
