#!/bin/bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

NAMESPACE=$1
OUTPUT_DIR=$2

# Collect Tekton Resources
# -----------------------------------------------------------------------------
for RESOURCE in tasks taskruns pipelines pipelineruns
do
  $DIR/mg-collect-resources -n $NAMESPACE -r $RESOURCE -d $OUTPUT_DIR/resources
done


exit 0