#!/bin/bash

echo "IBM Maximo Application Suite - Optimizer Application"
echo "--------------------------------------------------------------------------------"
oc get optimizerapp -n $1
echo ""

exit 0
