#!/bin/bash

echo "IBM Maximo Application Suite - Manage Application"
echo "--------------------------------------------------------------------------------"
oc get manageapp -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Manage Workspace Configuration"
echo "--------------------------------------------------------------------------------"
oc get manageworkspace -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Manage Build"
echo "--------------------------------------------------------------------------------"
oc get managebuild -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Manage Deployment"
echo "--------------------------------------------------------------------------------"
oc get managedeployment -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Server Bundle"
echo "--------------------------------------------------------------------------------"
oc get manageserverbundle -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Manage Status Checker"
echo "--------------------------------------------------------------------------------"
oc get managestatuschecker -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Maximo Health Application"
echo "--------------------------------------------------------------------------------"
oc get healthapp -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Maximo Health Workspace"
echo "--------------------------------------------------------------------------------"
oc get healthworkspace -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Maximo Healthext Workspace"
echo "--------------------------------------------------------------------------------"
oc get healthextworkspace -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Image Stitching"
echo "--------------------------------------------------------------------------------"
oc get imagestitching -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Open Telemetry Deployment"
echo "--------------------------------------------------------------------------------"
oc get opentelemetrydeployment -n $1
echo ""

exit 0
