#!/bin/bash

echo "IBM Maximo Application Suite - Manage Application"
echo "--------------------------------------------------------------------------------"
oc get manageapp -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Manage Workspace Configuration"
echo "--------------------------------------------------------------------------------"
oc get manageworkspace -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Manage Build"
echo "--------------------------------------------------------------------------------"
oc get managebuild -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Manage Deployment"
echo "--------------------------------------------------------------------------------"
oc get managedeployment -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Server Bundle"
echo "--------------------------------------------------------------------------------"
oc get manageserverbundle -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Manage Status Checker"
echo "--------------------------------------------------------------------------------"
oc get managestatuschecker -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Maximo Healthext application"
echo "--------------------------------------------------------------------------------"
oc get healthextapp -n $1
echo ""

echo ""
echo "IBM Maximo Application Suite - Maximo Healthext Workspace"
echo "--------------------------------------------------------------------------------"
oc get healthextworkspace -n $1
echo ""

exit 0
