#!/bin/bash
set -e

# Load common functions
# -----------------------------------------------------------------------------
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
. $DIR/image/installer/bin/functions/utils

# Set Target
# -----------------------------------------------------------------------------
function set_target_roks() {
  if [[ -z "$IBMCLOUD_APIKEY" ]]; then
    echo ""
    echo_h2 "IBM Cloud API Key"
    echo "Provide your IBMCloud API key (if you have not set the IBMCLOUD_APIKEY"
    echo "environment variable) which will be used to provision a ROKS instance."
    echo ""
    prompt_for_input "IBM Cloud API Key" IBMCLOUD_APIKEY
  fi

  echo ""
  echo_h2 "IBM Cloud ROKS Cluster Configuration"
  echo "Select your worker node flavour and the number of worker nodes to provision."
  echo "We recommend the 'b3c.8x32' worker node flavour to provide the best balance of"
  echo "performance, flexibility, and cost.  Larger MAS installations will require more"
  echo "worker nodes.  You can easily add and remove worker nodes to the cluster after"
  echo "provision so do not worry too much if you are not sure how many worker nodes "
  echo "you need as this can easily be adjusted at any time."
  echo ""
  if [[ ! -z "$1" ]]; then
    CLUSTER_NAME=$1
  fi

  prompt_for_input "Cluster Name" CLUSTER_NAME && export CLUSTER_NAME
  export CLUSTER_TYPE=roks

  echo
  echo "OCP Version:"
  echo "  1. 4.10 EUS (MAS 8.8)"
  echo "  2. 4.8 EUS  (MAS 8.6-8.8)"
  prompt_for_input "Select Version" OCP_VERSION_SELECTION "2"

  case $OCP_VERSION_SELECTION in
    1|4.10|4.10\ EUS)
      export OCP_VERSION=4.10_openshift
      ;;

    2|4.8|4.8\ EUS)
      export OCP_VERSION=4.8_openshift
      ;;

    *)
      export OCP_VERSION=$OCP_VERSION_SELECTION
      ;;
  esac


  prompt_for_input "Datacenter" ROKS_ZONE "lon02" && export ROKS_ZONE
  prompt_for_input "Worker Node Type" ROKS_FLAVOR "b3c.8x32" && export ROKS_FLAVOR
  prompt_for_input "Number of Worker Nodes" ROKS_WORKERS "3" && export ROKS_WORKERS

  export OCP_PROVISION_GPU=false
  echo ""
  echo_h2 "Bare Metal GPU Worker Support"
  echo "GPU worker nodes with flavour, mg4c.32x384.2xp100, can be added to the cluster"
  echo "for applications that require complex mathematical computations.  If you intnd"
  echo "to install the IBM Visual Inspection application you should answer 'yes' at"
  echo "the prompt below."
  echo ""
  prompt_for_confirm "Provision GPU worker nodes in cluster" && export OCP_PROVISION_GPU=true

  if [[ $OCP_PROVISION_GPU == "true" ]]; then
    prompt_for_input "Number of GPU Nodes" GPU_WORKERS "1" && export GPU_WORKERS
    prompt_for_input "GPU Worker Pool Name" GPU_WORKERPOOL_NAME "gpu" && export GPU_WORKERPOOL_NAME
  fi

  export REBOOT_WORKER_NODES=false
  echo ""
  echo_h2 "IBM CloudPak for Data Support"
  echo "IBM CloudPak for Data (CP4D) requires your IBM entitlement key to be set as a "
  echo "global image pull secret.  In IBMCloud ROKS this requires a reboot of all "
  echo "worker nodes to take place.  If you intend to install CP4D in this cluster you"
  echo "should answer 'yes' at the prompt below."
  echo ""
  prompt_for_confirm "Configure IBM Entitlement Key as Global Image Pull Secret" && export REBOOT_WORKER_NODES=true

  if [[ $REBOOT_WORKER_NODES == "true" ]]; then
    prompt_for_input "IBM Entitlement Key" CPD_ENTITLEMENT_KEY "$IBM_ENTITLEMENT_KEY" && export CPD_ENTITLEMENT_KEY
  fi

  export UPGRADE_IMAGE_REGISTRY_STORAGE=false
  echo ""
  echo_h2 "Upgrade Image Registry Capacity"
  echo "IBM CloudPak for Data (CP4D) requires a significant amount of storage in your"
  echo "container registry, by default IBMCloud ROKS only provisions 100GB of storage."
  echo "If you intend to install multiple CP4D services in this cluster you should "
  echo "answer 'yes' at the prompt below to upgrade the storage capacity to 400GB."
  echo ""
  prompt_for_confirm "Upgrade Image Registry Storage from 100GB to 400GB" && export UPGRADE_IMAGE_REGISTRY_STORAGE=true

  true
}


# Show Target
# -----------------------------------------------------------------------------
function show_target_roks() {
  echo ""
  echo_h2 "Summary"
  echo "IBMCloud API Key .......... ${IBMCLOUD_APIKEY:0:8}..."
  echo "Cluster Name .............. $CLUSTER_NAME"
  echo "OCP Version ............... $OCP_VERSION"
  echo "Worker Flavour ............ $ROKS_FLAVOR"
  echo "Worker Nodes .............. $ROKS_WORKERS"
  echo "Add GPU Worker Nodes ...... $OCP_PROVISION_GPU"
  if [[ $OCP_PROVISION_GPU == "true" ]]; then
    echo "GPU Worker Nodes .......... $GPU_WORKERS"
    echo "GPU Worker Pool Name ...... $GPU_WORKERPOOL_NAME"
  fi
  echo "Restart Worker Nodes ...... $REBOOT_WORKER_NODES"
  if [[ $REBOOT_WORKER_NODES == "true" ]]; then
    echo "CP4D Entitlement Key ...... ${CPD_ENTITLEMENT_KEY:0:8}..."
  fi
  echo "Upgrade Registry Storage .. $UPGRADE_IMAGE_REGISTRY_STORAGE"
}


set_target_roks $1
show_target_roks

echo ""
confirm "Proceed with these settings [y/N]" || exit 0

if [[ "$DEV_MODE" == "true" ]]; then
  build_and_install_local
else
  install
fi

ansible-playbook ibm.mas_devops.ocp_roks_provision

echo ""
echo "IBM Cloud ROKS cluster is ready to use"
OCP_CONSOLE_ROUTE=$(oc -n openshift-console get route console -o=jsonpath='{.spec.host}')
echo "Connected to OCP cluster: https://$OCP_CONSOLE_ROUTE"

exit 0
