name: Verify CLI Image

on:
  pull_request:
    branches: [ "master" ]

# Ensure only one build at a time for any branch, cancelling any in-progress builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: '! github.event.pull_request.draft'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
